/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * Authentication return value, including a JSON Web Token.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("AuthPayload")
public class AuthPayload {

	public AuthPayload() {
	}

	/**
	 * The JWT authentication token.
	 */
	@GraphQLScalar(fieldName = "token", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String token;

	/**
	 * The authenticated user.
	 */
	@GraphQLNonScalar(fieldName = "user", graphQLTypeSimpleName = "User", javaClass = User.class, listDepth = 0)
	User user;

	/**
	 * The JWT authentication token.
	 */
	public void setToken(String token) {
		this.token = token;
	}

	/**
	 * The JWT authentication token.
	 */
	public String getToken() {
		return this.token;
	}

	/**
	 * The authenticated user.
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * The authenticated user.
	 */
	public User getUser() {
		return this.user;
	}

	public String toString() {
		return "AuthPayload {" //
			+ "token: " + this.token //
			+ ", " //
			+ "user: " + this.user //
			+ "}"; //
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {

		private String token;
		private User user;

		/**
		 * The JWT authentication token.
		 */
		public Builder withToken(String tokenParam) {
			this.token = tokenParam;
			return this;
		}

		/**
		 * The authenticated user.
		 */
		public Builder withUser(User userParam) {
			this.user = userParam;
			return this;
		}

		public AuthPayload build() {
			AuthPayload _object = new AuthPayload();
			_object.setToken(this.token);
			_object.setUser(this.user);
			return _object;
		}

	}

}
