/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import java.net.URL;
import java.time.LocalDate;

import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorValue;
import jakarta.persistence.Entity;
import jakarta.persistence.PrimaryKeyJoinColumn;

/**
 * A public declaration or open letter made in respect of given topic(s).
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@Entity
@PrimaryKeyJoinColumn(name = "id")
@DiscriminatorValue("DEC")
@GraphQLObjectType("Declaration")
public class Declaration extends AbstractLinkableEntity {

	/**
	 * The kind of declaration.
	 */
	@GraphQLScalar(fieldName = "kind", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String kind;

	/**
	 * The declaration name or title.
	 */
	@GraphQLScalar(fieldName = "title", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String title;

	/**
	 * The date the declaration was published.
	 */
	@GraphQLScalar(fieldName = "date", graphQLTypeSimpleName = "Date", javaClass = LocalDate.class, listDepth = 0)
	LocalDate date;

	/**
	 * The country to which the declaration relates.
	 */
	@GraphQLScalar(fieldName = "country", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	@Column(name = "country_code")
	String country;

	/**
	 * The URL for the declaration online.
	 */
	@GraphQLScalar(fieldName = "url", graphQLTypeSimpleName = "URL", javaClass = URL.class, listDepth = 0)
	URL url;

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@GraphQLScalar(fieldName = "cached", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class, listDepth = 0)
	Boolean cached;

	/**
	 * Names of persons who signed the declaration, one per line.
	 */
	@GraphQLScalar(fieldName = "signatories", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String signatories;

	/**
	 * The number of signatories.
	 */
	@GraphQLScalar(fieldName = "signatoryCount", graphQLTypeSimpleName = "Int", javaClass = Integer.class,
		listDepth = 0)
	Integer signatoryCount;

	/**
	 * Added notes about the declaration.
	 */
	@GraphQLScalar(fieldName = "notes", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String notes;

	@Override
	public String getEntityKind() {
		return EntityKind.DEC.name();
	}

	/**
	 * The kind of declaration.
	 */
	public void setKind(String kind) {
		this.kind = kind;
	}

	/**
	 * The kind of declaration.
	 */
	public String getKind() {
		return this.kind;
	}

	/**
	 * The declaration name or title.
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * The declaration name or title.
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * The date the declaration was published.
	 */
	public void setDate(LocalDate date) {
		this.date = date;
	}

	/**
	 * The date the declaration was published.
	 */
	public LocalDate getDate() {
		return this.date;
	}

	/**
	 * The country to which the declaration relates.
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * The country to which the declaration relates.
	 */
	public String getCountry() {
		return this.country;
	}

	/**
	 * The URL for the declaration online.
	 */
	public void setUrl(URL url) {
		this.url = url;
	}

	/**
	 * The URL for the declaration online.
	 */
	public URL getUrl() {
		return this.url;
	}

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	public void setCached(Boolean cached) {
		this.cached = cached;
	}

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	public Boolean getCached() {
		return this.cached;
	}

	/**
	 * Names of persons who signed the declaration, one per line.
	 */
	public void setSignatories(String signatories) {
		this.signatories = signatories;
	}

	/**
	 * Names of persons who signed the declaration, one per line.
	 */
	public String getSignatories() {
		return this.signatories;
	}

	/**
	 * The number of signatories.
	 */
	public void setSignatoryCount(Integer signatoryCount) {
		this.signatoryCount = signatoryCount;
	}

	/**
	 * The number of signatories.
	 */
	public Integer getSignatoryCount() {
		return this.signatoryCount;
	}

	/**
	 * Added notes about the declaration.
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * Added notes about the declaration.
	 */
	public String getNotes() {
		return this.notes;
	}

	public String toString() {
		return "Declaration {" //
			+ "id: " + this.id //
			+ ", " //
			+ "entityKind: " + this.getEntityKind() //
			+ ", " //
			+ "status: " + this.status //
			+ ", " //
			+ "rating: " + this.rating //
			+ ", " //
			+ "created: " + this.created //
			+ ", " //
			+ "createdByUser: " + this.createdByUser //
			+ ", " //
			+ "updated: " + this.updated //
			+ ", " //
			+ "updatedByUser: " + this.updatedByUser //
			+ ", " //
			+ "log: " + this.log //
			+ ", " //
			+ "fromEntityLinks: " + this.fromEntityLinks //
			+ ", " //
			+ "toEntityLinks: " + this.toEntityLinks //
			+ ", " //
			+ "kind: " + this.kind //
			+ ", " //
			+ "title: " + this.title //
			+ ", " //
			+ "date: " + this.date //
			+ ", " //
			+ "country: " + this.country //
			+ ", " //
			+ "url: " + this.url //
			+ ", " //
			+ "cached: " + this.cached //
			+ ", " //
			+ "signatories: " + this.signatories //
			+ ", " //
			+ "signatoryCount: " + this.signatoryCount //
			+ ", " //
			+ "notes: " + this.notes //
			+ "}"; //
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractLinkableEntity.Builder<Builder, Declaration> {

		private String kind;
		private String title;
		private LocalDate date;
		private String country;
		private URL url;
		private Boolean cached;
		private String signatories;
		private Integer signatoryCount;
		private String notes;

		/**
		 * The kind of declaration.
		 */
		public Builder withKind(String kindParam) {
			this.kind = kindParam;
			return this;
		}

		/**
		 * The declaration name or title.
		 */
		public Builder withTitle(String titleParam) {
			this.title = titleParam;
			return this;
		}

		/**
		 * The date the declaration was published.
		 */
		public Builder withDate(java.time.LocalDate dateParam) {
			this.date = dateParam;
			return this;
		}

		/**
		 * The country to which the declaration relates.
		 */
		public Builder withCountry(String countryParam) {
			this.country = countryParam;
			return this;
		}

		/**
		 * The URL for the declaration online.
		 */
		public Builder withUrl(URL urlParam) {
			this.url = urlParam;
			return this;
		}

		/**
		 * Flag to indicate that url content is cached on this application server.
		 */
		public Builder withCached(Boolean cachedParam) {
			this.cached = cachedParam;
			return this;
		}

		/**
		 * Names of persons who signed the declaration, one per line.
		 */
		public Builder withSignatories(String signatoriesParam) {
			this.signatories = signatoriesParam;
			return this;
		}

		/**
		 * The number of signatories.
		 */
		public Builder withSignatoryCount(Integer signatoryCountParam) {
			this.signatoryCount = signatoryCountParam;
			return this;
		}

		/**
		 * Added notes about the declaration.
		 */
		public Builder withNotes(String notesParam) {
			this.notes = notesParam;
			return this;
		}

		@Override
		public Declaration build() {
			Declaration _object = build(new Declaration());
			_object.setKind(this.kind);
			_object.setTitle(this.title);
			_object.setDate(this.date);
			_object.setCountry(this.country);
			_object.setUrl(this.url);
			_object.setCached(this.cached);
			_object.setSignatories(this.signatories);
			_object.setSignatoryCount(this.signatoryCount);
			_object.setNotes(this.notes);
			return _object;
		}

	}

}
