/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import java.util.List;

import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * Holds aggregated field audit information.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("FieldAudit")
public class FieldAudit implements IFieldAudit {

	/**
	 * The individual field audit entries.
	 */
	@GraphQLNonScalar(fieldName = "fields", graphQLTypeSimpleName = "FieldAuditEntry",
		javaClass = FieldAuditEntry.class, listDepth = 1)
	List<FieldAuditEntry> fields;

	/**
	 * Field group audit entries.
	 */
	@GraphQLNonScalar(fieldName = "groups", graphQLTypeSimpleName = "FieldGroupAuditEntry",
		javaClass = FieldGroupAuditEntry.class, listDepth = 1)
	List<FieldGroupAuditEntry> groups;

	/**
	 * Whether the fields meet the standard required for publication.
	 */
	@GraphQLScalar(fieldName = "pass", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class, listDepth = 0)
	Boolean pass;

	/**
	 * The individual field audit entries.
	 */
	public void setFields(List<FieldAuditEntry> fields) {
		this.fields = fields;
	}

	/**
	 * The individual field audit entries.
	 */
	@Override
	public List<FieldAuditEntry> getFields() {
		return this.fields;
	}

	/**
	 * Field group audit entries.
	 */
	public void setGroups(List<FieldGroupAuditEntry> groups) {
		this.groups = groups;
	}

	/**
	 * Field group audit entries.
	 */
	public List<FieldGroupAuditEntry> getGroups() {
		return this.groups;
	}

	/**
	 * Whether the fields meet the standard required for publication.
	 */
	@Override
	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	/**
	 * Whether the fields meet the standard required for publication.
	 */
	@Override
	public Boolean getPass() {
		return this.pass;
	}

	public String toString() {
		return "FieldAudit {" //
			+ "fields: " + this.fields //
			+ ", " //
			+ "groups: " + this.groups //
			+ ", " //
			+ "pass: " + this.pass //
			+ "}"; //
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {

		private List<FieldAuditEntry> fields;
		private List<FieldGroupAuditEntry> groups;
		private Boolean pass;

		/**
		 * The individual field audit entries.
		 */
		public Builder withFields(List<FieldAuditEntry> fieldsParam) {
			this.fields = fieldsParam;
			return this;
		}

		/**
		 * Field group audit entries.
		 */
		public Builder withGroups(List<FieldGroupAuditEntry> groupsParam) {
			this.groups = groupsParam;
			return this;
		}

		/**
		 * Whether the fields meet the standard required for publication.
		 */
		public Builder withPass(Boolean passParam) {
			this.pass = passParam;
			return this;
		}

		public FieldAudit build() {
			FieldAudit _object = new FieldAudit();
			_object.setFields(this.fields);
			_object.setGroups(this.groups);
			_object.setPass(this.pass);
			return _object;
		}

	}

}
