/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import java.net.URL;

import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * An input for creating or updating a journal.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("JournalInput")
public class JournalInput {

	/**
	 * The abreviation identifier, required if updating an existing record.
	 */
	@GraphQLScalar(fieldName = "id", graphQLTypeSimpleName = "ID", javaClass = Long.class, listDepth = 0)
	Long id;

	/**
	 * The full journal title.
	 */
	@GraphQLScalar(fieldName = "title", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String title;

	/**
	 * The official abbreviation.
	 */
	@GraphQLScalar(fieldName = "abbreviation", graphQLTypeSimpleName = "String", javaClass = String.class,
		listDepth = 0)
	String abbreviation;

	@GraphQLScalar(fieldName = "url", graphQLTypeSimpleName = "URL", javaClass = URL.class, listDepth = 0)
	URL url;

	/**
	 * The International Standard Serial Number.
	 */
	@GraphQLScalar(fieldName = "issn", graphQLTypeSimpleName = "ISSN", javaClass = String.class, listDepth = 0)
	String issn;

	/**
	 * The ID of the journal publisher.
	 */
	@GraphQLScalar(fieldName = "publisherId", graphQLTypeSimpleName = "Long", javaClass = Long.class, listDepth = 0)
	Long publisherId;

	/**
	 * Notes about the journal.
	 */
	@GraphQLScalar(fieldName = "notes", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String notes;

	/**
	 * The abreviation identifier, required if updating an existing record.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * The abreviation identifier, required if updating an existing record.
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * The full journal title.
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * The full journal title.
	 */
	public String getTitle() {
		return this.title;
	}

	/**
	 * The official abbreviation.
	 */
	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	/**
	 * The official abbreviation.
	 */
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setUrl(URL url) {
		this.url = url;
	}

	public java.net.URL getUrl() {
		return this.url;
	}

	/**
	 * The International Standard Serial Number.
	 */
	public void setIssn(String issn) {
		this.issn = issn;
	}

	/**
	 * The International Standard Serial Number.
	 */
	public String getIssn() {
		return this.issn;
	}

	/**
	 * The ID of the journal publisher.
	 */
	public void setPublisherId(Long publisherId) {
		this.publisherId = publisherId;
	}

	/**
	 * The ID of the journal publisher.
	 */
	public Long getPublisherId() {
		return this.publisherId;
	}

	/**
	 * Notes about the journal.
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * Notes about the journal.
	 */
	public String getNotes() {
		return this.notes;
	}

	public String toString() {
		return "JournalInput {" //$NON-NLS-1$
			+ "id: " + this.id //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "title: " + this.title //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "abbreviation: " + this.abbreviation //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "url: " + this.url //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "issn: " + this.issn //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "publisherId: " + this.publisherId //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "notes: " + this.notes //$NON-NLS-1$
			+ "}"; //$NON-NLS-1$
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {
		private Long id;
		private String title;
		private String abbreviation;
		private URL url;
		private String issn;
		private Long publisherId;
		private String notes;

		/**
		 * The abreviation identifier, required if updating an existing record.
		 */
		public Builder withId(Long idParam) {
			this.id = idParam;
			return this;
		}

		/**
		 * The full journal title.
		 */
		public Builder withTitle(String titleParam) {
			this.title = titleParam;
			return this;
		}

		/**
		 * The official abbreviation.
		 */
		public Builder withAbbreviation(String abbreviationParam) {
			this.abbreviation = abbreviationParam;
			return this;
		}

		public Builder withUrl(URL urlParam) {
			this.url = urlParam;
			return this;
		}

		/**
		 * The International Standard Serial Number.
		 */
		public Builder withIssn(String issnParam) {
			this.issn = issnParam;
			return this;
		}

		/**
		 * The ID of the journal publisher.
		 */
		public Builder withPublisherId(Long publisherIdParam) {
			this.publisherId = publisherIdParam;
			return this;
		}

		/**
		 * Notes about the journal.
		 */
		public Builder withNotes(String notesParam) {
			this.notes = notesParam;
			return this;
		}

		public JournalInput build() {
			JournalInput _object = new JournalInput();
			_object.setId(this.id);
			_object.setTitle(this.title);
			_object.setAbbreviation(this.abbreviation);
			_object.setUrl(this.url);
			_object.setIssn(this.issn);
			_object.setPublisherId(this.publisherId);
			_object.setNotes(this.notes);
			return _object;
		}
	}

}
