/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import java.util.List;

import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * Holds link group audit information. At least one link in the group must be present.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("LinkGroupAuditEntry")
public class LinkGroupAuditEntry implements ILinkAudit {

	/**
	 * Link group audit entries.
	 */
	@GraphQLNonScalar(fieldName = "links", graphQLTypeSimpleName = "LinkAuditEntry", javaClass = LinkAuditEntry.class,
		listDepth = 1)
	List<LinkAuditEntry> links;

	/**
	 * Whether the link group meets the standard required for publication.
	 */
	@GraphQLScalar(fieldName = "pass", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class, listDepth = 0)
	Boolean pass;

	/**
	 * Link group audit entries.
	 */
	public void setLinks(List<LinkAuditEntry> links) {
		this.links = links;
	}

	/**
	 * Link group audit entries.
	 */
	public List<LinkAuditEntry> getLinks() {
		return this.links;
	}

	/**
	 * Whether the link group meets the standard required for publication.
	 */
	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	/**
	 * Whether the link group meets the standard required for publication.
	 */
	public Boolean getPass() {
		return this.pass;
	}

	public String toString() {
		return "LinkGroupAuditEntry {" //
			+ "links: " + this.links //
			+ ", " //
			+ "pass: " + this.pass //
			+ "}"; //
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {

		private List<LinkAuditEntry> links;
		private Boolean pass;

		/**
		 * Link group audit entries.
		 */
		public Builder withLinks(List<LinkAuditEntry> linksParam) {
			this.links = linksParam;
			return this;
		}

		/**
		 * Whether the link group meets the standard required for publication.
		 */
		public Builder withPass(Boolean passParam) {
			this.pass = passParam;
			return this;
		}

		public LinkGroupAuditEntry build() {
			LinkGroupAuditEntry _object = new LinkGroupAuditEntry();
			_object.setLinks(this.links);
			_object.setPass(this.pass);
			return _object;
		}

	}

}
