/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import com.graphql_java_generator.annotation.GraphQLDirective;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * Available mutations.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("Mutation")
public class Mutation {

	/**
	 * Creates a new claim.
	 */
	@GraphQLNonScalar(fieldName = "createClaim", graphQLTypeSimpleName = "Claim", javaClass = Claim.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	Claim createClaim;

	/**
	 * Updates an existing claim.
	 */
	@GraphQLNonScalar(fieldName = "updateClaim", graphQLTypeSimpleName = "Claim", javaClass = Claim.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Claim updateClaim;

	/**
	 * Deletes an existing claim.
	 */
	@GraphQLScalar(fieldName = "deleteClaim", graphQLTypeSimpleName = "Claim", javaClass = Claim.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	Claim deleteClaim;

	/**
	 * Creates a new declaration.
	 */
	@GraphQLNonScalar(fieldName = "createDeclaration", graphQLTypeSimpleName = "Declaration",
		javaClass = Declaration.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	Declaration createDeclaration;

	/**
	 * Updates an existing declaration.
	 */
	@GraphQLNonScalar(fieldName = "updateDeclaration", graphQLTypeSimpleName = "Declaration",
		javaClass = Declaration.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Declaration updateDeclaration;

	/**
	 * Deletes an existing declaration.
	 */
	@GraphQLScalar(fieldName = "deleteDeclaration", graphQLTypeSimpleName = "Declaration",
		javaClass = Declaration.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	Declaration deleteDeclaration;

	/**
	 * Creates an entity link.
	 */
	@GraphQLNonScalar(fieldName = "createEntityLink", graphQLTypeSimpleName = "EntityLink",
		javaClass = EntityLink.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	EntityLink createEntityLink;

	/**
	 * Updates an existing entity link.
	 */
	@GraphQLNonScalar(fieldName = "updateEntityLink", graphQLTypeSimpleName = "EntityLink",
		javaClass = EntityLink.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	EntityLink updateEntityLink;

	/**
	 * Deletes an entity link.
	 */
	@GraphQLNonScalar(fieldName = "deleteEntityLink", graphQLTypeSimpleName = "EntityLink",
		javaClass = EntityLink.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	EntityLink deleteEntityLink;

	/**
	 * Create a new journal.
	 */
	@GraphQLNonScalar(fieldName = "createJournal", graphQLTypeSimpleName = "Journal", javaClass = Journal.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	Journal createJournal;

	/**
	 * Updates an existing journal.
	 */
	@GraphQLNonScalar(fieldName = "updateJournal", graphQLTypeSimpleName = "Journal", javaClass = Journal.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Journal updateJournal;

	/**
	 * Deletes an existing journal.
	 */
	@GraphQLScalar(fieldName = "deleteJournal", graphQLTypeSimpleName = "Journal", javaClass = Journal.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	Journal deleteJournal;

	/**
	 * Creates a new person.
	 */
	@GraphQLNonScalar(fieldName = "createPerson", graphQLTypeSimpleName = "Person", javaClass = Person.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	Person createPerson;

	/**
	 * Updates an existing person.
	 */
	@GraphQLNonScalar(fieldName = "updatePerson", graphQLTypeSimpleName = "Person", javaClass = Person.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Person updatePerson;

	/**
	 * Deletes an existing person.
	 */
	@GraphQLScalar(fieldName = "deletePerson", graphQLTypeSimpleName = "Person", javaClass = Person.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	Person deletePerson;

	/**
	 * Creates a new publication.
	 */
	@GraphQLNonScalar(fieldName = "createPublication", graphQLTypeSimpleName = "Publication",
		javaClass = Publication.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	Publication createPublication;

	/**
	 * Updates an existing publication.
	 */
	@GraphQLNonScalar(fieldName = "updatePublication", graphQLTypeSimpleName = "Publication",
		javaClass = Publication.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Publication updatePublication;

	/**
	 * Deletes an existing publication.
	 */
	@GraphQLScalar(fieldName = "deletePublication", graphQLTypeSimpleName = "Publication",
		javaClass = Publication.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	Publication deletePublication;

	/**
	 * Creates a new publisher.
	 */
	@GraphQLNonScalar(fieldName = "createPublisher", graphQLTypeSimpleName = "Publisher", javaClass = Publisher.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	Publisher createPublisher;

	/**
	 * Updates an existing publisher.
	 */
	@GraphQLNonScalar(fieldName = "updatePublisher", graphQLTypeSimpleName = "Publisher", javaClass = Publisher.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Publisher updatePublisher;

	/**
	 * Deletes an existing publisher.
	 */
	@GraphQLScalar(fieldName = "deletePublisher", graphQLTypeSimpleName = "Publisher", javaClass = Publisher.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	Publisher deletePublisher;

	/**
	 * Creates a new quotation.
	 */
	@GraphQLNonScalar(fieldName = "createQuotation", graphQLTypeSimpleName = "Quotation", javaClass = Quotation.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	Quotation createQuotation;

	/**
	 * Updates an existing quotation.
	 */
	@GraphQLNonScalar(fieldName = "updateQuotation", graphQLTypeSimpleName = "Quotation", javaClass = Quotation.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Quotation updateQuotation;

	/**
	 * Deletes an existing quotation.
	 */
	@GraphQLScalar(fieldName = "deleteQuotation", graphQLTypeSimpleName = "Quotation", javaClass = Quotation.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	Quotation deleteQuotation;

	/**
	 * Creates a new topic.
	 */
	@GraphQLNonScalar(fieldName = "createTopic", graphQLTypeSimpleName = "Topic", javaClass = Topic.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	Topic createTopic;

	/**
	 * Updates an existing topic.
	 */
	@GraphQLNonScalar(fieldName = "updateTopic", graphQLTypeSimpleName = "Topic", javaClass = Topic.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Topic updateTopic;

	/**
	 * Deletes an existing topic.
	 */
	@GraphQLScalar(fieldName = "deleteTopic", graphQLTypeSimpleName = "Topic", javaClass = Topic.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	Topic deleteTopic;

	/**
	 * Sets entity status.
	 */
	@GraphQLScalar(fieldName = "setEntityStatus", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	Boolean setEntityStatus;

	/**
	 * Creates a new user.
	 */
	@GraphQLNonScalar(fieldName = "createUser", graphQLTypeSimpleName = "User", javaClass = User.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	User createUser;

	/**
	 * Updates an existing user.
	 */
	@GraphQLNonScalar(fieldName = "updateUser", graphQLTypeSimpleName = "User", javaClass = User.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	User updateUser;

	/**
	 * Updates an existing user.
	 */
	@GraphQLScalar(fieldName = "deleteUser", graphQLTypeSimpleName = "User", javaClass = User.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	User deleteUser;

	/**
	 * Grants authorities to a user. The specified authorities are added to any existing ones.
	 */
	@GraphQLNonScalar(fieldName = "grantUserAuthorities", graphQLTypeSimpleName = "User", javaClass = User.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	User grantUserAuthorities;

	/**
	 * Revokes authorities from a user. The specified authorities are removed from the user; other authorities remain
	 * intact.
	 */
	@GraphQLNonScalar(fieldName = "revokeUserAuthorities", graphQLTypeSimpleName = "User", javaClass = User.class,
		listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	User revokeUserAuthorities;

	/**
	 * Creates a new group.
	 */
	@GraphQLNonScalar(fieldName = "createGroup", graphQLTypeSimpleName = "Group", javaClass = Group.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	Group createGroup;

	/**
	 * Updates an existing group.
	 */
	@GraphQLNonScalar(fieldName = "updateGroup", graphQLTypeSimpleName = "Group", javaClass = Group.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	Group updateGroup;

	/**
	 * Deletes an existing group.
	 */
	@GraphQLNonScalar(fieldName = "deleteGroup", graphQLTypeSimpleName = "Group", javaClass = Group.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	Group deleteGroup;

	/**
	 * Adds a user to a group.
	 */
	@GraphQLNonScalar(fieldName = "addGroupMember", graphQLTypeSimpleName = "Group", javaClass = Group.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	Group addGroupMember;

	/**
	 * Removes a user from a group.
	 */
	@GraphQLNonScalar(fieldName = "removeGroupMember", graphQLTypeSimpleName = "Group", javaClass = Group.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	Group removeGroupMember;

	/**
	 * Grants authorities to a group. The specified authorities are added to any
	 * existing ones.
	 */
	@GraphQLNonScalar(fieldName = "grantGroupAuthorities", graphQLTypeSimpleName = "Group", javaClass = Group.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	Group grantGroupAuthorities;

	/**
	 * Revokes authorities from a group. The specified authorities are removed from
	 * the group; other authorities remain intact.
	 */
	@GraphQLNonScalar(fieldName = "revokeGroupAuthorities", graphQLTypeSimpleName = "Group", javaClass = Group.class, listDepth = 0)
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	Group revokeGroupAuthorities;

	/**
	 * Creates a new claim.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public void setCreateClaim(Claim createClaim) {
		this.createClaim = createClaim;
	}

	/**
	 * Creates a new claim.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public Claim getCreateClaim() {
		return this.createClaim;
	}

	/**
	 * Updates an existing claim.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setUpdateClaim(Claim updateClaim) {
		this.updateClaim = updateClaim;
	}

	/**
	 * Updates an existing claim.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Claim getUpdateClaim() {
		return this.updateClaim;
	}

	/**
	 * Deletes an existing claim.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public void setDeleteClaim(Claim deleteClaim) {
		this.deleteClaim = deleteClaim;
	}

	/**
	 * Deletes an existing claim.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public Claim getDeleteClaim() {
		return this.deleteClaim;
	}

	/**
	 * Creates a new declaration.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public void setCreateDeclaration(Declaration createDeclaration) {
		this.createDeclaration = createDeclaration;
	}

	/**
	 * Creates a new declaration.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public Declaration getCreateDeclaration() {
		return this.createDeclaration;
	}

	/**
	 * Updates an existing declaration.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setUpdateDeclaration(Declaration updateDeclaration) {
		this.updateDeclaration = updateDeclaration;
	}

	/**
	 * Updates an existing declaration.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Declaration getUpdateDeclaration() {
		return this.updateDeclaration;
	}

	/**
	 * Deletes an existing declaration.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public void setDeleteDeclaration(Declaration deleteDeclaration) {
		this.deleteDeclaration = deleteDeclaration;
	}

	/**
	 * Deletes an existing declaration.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public Declaration getDeleteDeclaration() {
		return this.deleteDeclaration;
	}

	/**
	 * Creates an entity link.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	public void setCreateEntityLink(EntityLink createEntityLink) {
		this.createEntityLink = createEntityLink;
	}

	/**
	 * Creates an entity link.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	public EntityLink getCreateEntityLink() {
		return this.createEntityLink;
	}

	/**
	 * Updates an existing entity link.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	public void setUpdateEntityLink(EntityLink updateEntityLink) {
		this.updateEntityLink = updateEntityLink;
	}

	/**
	 * Updates an existing entity link.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	public EntityLink getUpdateEntityLink() {
		return this.updateEntityLink;
	}

	/**
	 * Deletes an entity link.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	public void setDeleteEntityLink(EntityLink deleteEntityLink) {
		this.deleteEntityLink = deleteEntityLink;
	}

	/**
	 * Deletes an entity link.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[LNK]" })
	public EntityLink getDeleteEntityLink() {
		return this.deleteEntityLink;
	}

	/**
	 * Create a new journal.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public void setCreateJournal(Journal createJournal) {
		this.createJournal = createJournal;
	}

	/**
	 * Create a new journal.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public Journal getCreateJournal() {
		return this.createJournal;
	}

	/**
	 * Updates an existing journal.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setUpdateJournal(Journal updateJournal) {
		this.updateJournal = updateJournal;
	}

	/**
	 * Updates an existing journal.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Journal getUpdateJournal() {
		return this.updateJournal;
	}

	/**
	 * Deletes an existing journal.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public void setDeleteJournal(Journal deleteJournal) {
		this.deleteJournal = deleteJournal;
	}

	/**
	 * Deletes an existing journal.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public Journal getDeleteJournal() {
		return this.deleteJournal;
	}

	/**
	 * Creates a new person.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public void setCreatePerson(Person createPerson) {
		this.createPerson = createPerson;
	}

	/**
	 * Creates a new person.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public Person getCreatePerson() {
		return this.createPerson;
	}

	/**
	 * Updates an existing person.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setUpdatePerson(Person updatePerson) {
		this.updatePerson = updatePerson;
	}

	/**
	 * Updates an existing person.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Person getUpdatePerson() {
		return this.updatePerson;
	}

	/**
	 * Deletes an existing person.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public void setDeletePerson(Person deletePerson) {
		this.deletePerson = deletePerson;
	}

	/**
	 * Deletes an existing person.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public Person getDeletePerson() {
		return this.deletePerson;
	}

	/**
	 * Creates a new publication.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public void setCreatePublication(Publication createPublication) {
		this.createPublication = createPublication;
	}

	/**
	 * Creates a new publication.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public Publication getCreatePublication() {
		return this.createPublication;
	}

	/**
	 * Updates an existing publication.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setUpdatePublication(Publication updatePublication) {
		this.updatePublication = updatePublication;
	}

	/**
	 * Updates an existing publication.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Publication getUpdatePublication() {
		return this.updatePublication;
	}

	/**
	 * Deletes an existing publication.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public void setDeletePublication(Publication deletePublication) {
		this.deletePublication = deletePublication;
	}

	/**
	 * Deletes an existing publication.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public Publication getDeletePublication() {
		return this.deletePublication;
	}

	/**
	 * Creates a new publisher.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public void setCreatePublisher(Publisher createPublisher) {
		this.createPublisher = createPublisher;
	}

	/**
	 * Creates a new publisher.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public Publisher getCreatePublisher() {
		return this.createPublisher;
	}

	/**
	 * Updates an existing publisher.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setUpdatePublisher(Publisher updatePublisher) {
		this.updatePublisher = updatePublisher;
	}

	/**
	 * Updates an existing publisher.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Publisher getUpdatePublisher() {
		return this.updatePublisher;
	}

	/**
	 * Deletes an existing publisher.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public void setDeletePublisher(Publisher deletePublisher) {
		this.deletePublisher = deletePublisher;
	}

	/**
	 * Deletes an existing publisher.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public Publisher getDeletePublisher() {
		return this.deletePublisher;
	}

	/**
	 * Creates a new quotation.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public void setCreateQuotation(Quotation createQuotation) {
		this.createQuotation = createQuotation;
	}

	/**
	 * Creates a new quotation.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public Quotation getCreateQuotation() {
		return this.createQuotation;
	}

	/**
	 * Updates an existing quotation.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setUpdateQuotation(Quotation updateQuotation) {
		this.updateQuotation = updateQuotation;
	}

	/**
	 * Updates an existing quotation.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Quotation getUpdateQuotation() {
		return this.updateQuotation;
	}

	/**
	 * Deletes an existing quotation.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public void setDeleteQuotation(Quotation deleteQuotation) {
		this.deleteQuotation = deleteQuotation;
	}

	/**
	 * Deletes an existing quotation.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public Quotation getDeleteQuotation() {
		return this.deleteQuotation;
	}

	/**
	 * Creates a new topic.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public void setCreateTopic(Topic createTopic) {
		this.createTopic = createTopic;
	}

	/**
	 * Creates a new topic.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[CRE]" })
	public Topic getCreateTopic() {
		return this.createTopic;
	}

	/**
	 * Updates an existing topic.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setUpdateTopic(Topic updateTopic) {
		this.updateTopic = updateTopic;
	}

	/**
	 * Updates an existing topic.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Topic getUpdateTopic() {
		return this.updateTopic;
	}

	/**
	 * Deletes an existing topic.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public void setDeleteTopic(Topic deleteTopic) {
		this.deleteTopic = deleteTopic;
	}

	/**
	 * Deletes an existing topic.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[DEL]" })
	public Topic getDeleteTopic() {
		return this.deleteTopic;
	}

	/**
	 * Sets entity status.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public void setSetEntityStatus(Boolean setEntityStatus) {
		this.setEntityStatus = setEntityStatus;
	}

	/**
	 * Sets entity status.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[UPD]" })
	public Boolean getSetEntityStatus() {
		return this.setEntityStatus;
	}

	/**
	 * Creates a new user.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public void setCreateUser(User createUser) {
		this.createUser = createUser;
	}

	/**
	 * Creates a new user.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public User getCreateUser() {
		return this.createUser;
	}

	/**
	 * Updates an existing user.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public void setUpdateUser(User updateUser) {
		this.updateUser = updateUser;
	}

	/**
	 * Updates an existing user.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public User getUpdateUser() {
		return this.updateUser;
	}

	/**
	 * Deletes an existing user.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public void setDeleteUser(User deleteUser) {
		this.deleteUser = deleteUser;
	}

	/**
	 * Deletes an existing user.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public User getDeleteUser() {
		return this.deleteUser;
	}

	/**
	 * Grants authorities to a user. The specified authorities are added to any existing ones.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public void setGrantUserAuthorities(User grantUserAuthorities) {
		this.grantUserAuthorities = grantUserAuthorities;
	}

	/**
	 * Grants authorities to a user. The specified authorities are added to any existing ones.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public User getGrantUserAuthorities() {
		return this.grantUserAuthorities;
	}

	/**
	 * Revokes authorities from a user. The specified authorities are removed from the user; other authorities remain
	 * intact.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public void setRevokeUserAuthorities(User revokeUserAuthorities) {
		this.revokeUserAuthorities = revokeUserAuthorities;
	}

	/**
	 * Revokes authorities from a user. The specified authorities are removed from the user; other authorities remain
	 * intact.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = { "[AuthorityKind!]" },
		parameterValues = { "[ADM]" })
	public User getRevokeUserAuthorities() {
		return this.revokeUserAuthorities;
	}

	/**
	 * Creates a new group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public void setCreateGroup(Group createGroup) {
		this.createGroup = createGroup;
	}

	/**
	 * Creates a new group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public Group getCreateGroup() {
		return this.createGroup;
	}

	/**
	 * Updates an existing group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public void setUpdateGroup(Group updateGroup) {
		this.updateGroup = updateGroup;
	}

	/**
	 * Updates an existing group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public Group getUpdateGroup() {
		return this.updateGroup;
	}

	/**
	 * Deletes an existing group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public void setDeleteGroup(Group deleteGroup) {
		this.deleteGroup = deleteGroup;
	}

	/**
	 * Deletes an existing group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public Group getDeleteGroup() {
		return this.deleteGroup;
	}

	/**
	 * Adds a user to a group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public void setAddGroupMember(Group addGroupMember) {
		this.addGroupMember = addGroupMember;
	}

	/**
	 * Adds a user to a group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public Group getAddGroupMember() {
		return this.addGroupMember;
	}

	/**
	 * Removes a user from a group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public void setRemoveGroupMember(Group removeGroupMember) {
		this.removeGroupMember = removeGroupMember;
	}

	/**
	 * Removes a user from a group.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public Group getRemoveGroupMember() {
		return this.removeGroupMember;
	}

	/**
	 * Grants authorities to a group. The specified authorities are added to any
	 * existing ones.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public void setGrantGroupAuthorities(Group grantGroupAuthorities) {
		this.grantGroupAuthorities = grantGroupAuthorities;
	}

	/**
	 * Grants authorities to a group. The specified authorities are added to any
	 * existing ones.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public Group getGrantGroupAuthorities() {
		return this.grantGroupAuthorities;
	}

	/**
	 * Revokes authorities from a group. The specified authorities are removed from
	 * the group; other authorities remain intact.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public void setRevokeGroupAuthorities(Group revokeGroupAuthorities) {
		this.revokeGroupAuthorities = revokeGroupAuthorities;
	}

	/**
	 * Revokes authorities from a group. The specified authorities are removed from
	 * the group; other authorities remain intact.
	 */
	@GraphQLDirective(name = "@auth", parameterNames = { "authority" }, parameterTypes = {
			"[AuthorityKind!]" }, parameterValues = { "[ADM]" })
	public Group getRevokeGroupAuthorities() {
		return this.revokeGroupAuthorities;
	}

	public String toString() {
		return "Mutation {" //$NON-NLS-1$
				+ "createClaim: " + this.createClaim //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updateClaim: " + this.updateClaim //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deleteClaim: " + this.deleteClaim //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createDeclaration: " + this.createDeclaration //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updateDeclaration: " + this.updateDeclaration //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deleteDeclaration: " + this.deleteDeclaration //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createEntityLink: " + this.createEntityLink //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updateEntityLink: " + this.updateEntityLink //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deleteEntityLink: " + this.deleteEntityLink //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createJournal: " + this.createJournal //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updateJournal: " + this.updateJournal //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deleteJournal: " + this.deleteJournal //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createPerson: " + this.createPerson //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updatePerson: " + this.updatePerson //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deletePerson: " + this.deletePerson //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createPublication: " + this.createPublication //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updatePublication: " + this.updatePublication //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deletePublication: " + this.deletePublication //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createPublisher: " + this.createPublisher //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updatePublisher: " + this.updatePublisher //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deletePublisher: " + this.deletePublisher //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createQuotation: " + this.createQuotation //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updateQuotation: " + this.updateQuotation //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deleteQuotation: " + this.deleteQuotation //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createTopic: " + this.createTopic //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updateTopic: " + this.updateTopic //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deleteTopic: " + this.deleteTopic //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "setEntityStatus: " + this.setEntityStatus //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createUser: " + this.createUser //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updateUser: " + this.updateUser //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deleteUser: " + this.deleteUser //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "grantUserAuthorities: " + this.grantUserAuthorities //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "revokeUserAuthorities: " + this.revokeUserAuthorities //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "createGroup: " + this.createGroup //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "updateGroup: " + this.updateGroup //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "deleteGroup: " + this.deleteGroup //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "addGroupMember: " + this.addGroupMember //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "removeGroupMember: " + this.removeGroupMember //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "grantGroupAuthorities: " + this.grantGroupAuthorities //$NON-NLS-1$
				+ ", " //$NON-NLS-1$
				+ "revokeGroupAuthorities: " + this.revokeGroupAuthorities //$NON-NLS-1$
				+ "}"; //$NON-NLS-1$
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {

		private Claim createClaim;
		private Claim updateClaim;
		private Claim deleteClaim;
		private Declaration createDeclaration;
		private Declaration updateDeclaration;
		private Declaration deleteDeclaration;
		private EntityLink createEntityLink;
		private EntityLink updateEntityLink;
		private EntityLink deleteEntityLink;
		private Journal createJournal;
		private Journal updateJournal;
		private Journal deleteJournal;
		private Person createPerson;
		private Person updatePerson;
		private Person deletePerson;
		private Publication createPublication;
		private Publication updatePublication;
		private Publication deletePublication;
		private Publisher createPublisher;
		private Publisher updatePublisher;
		private Publisher deletePublisher;
		private Quotation createQuotation;
		private Quotation updateQuotation;
		private Quotation deleteQuotation;
		private Topic createTopic;
		private Topic updateTopic;
		private Topic deleteTopic;
		private Boolean setEntityStatus;
		private User createUser;
		private User updateUser;
		private User deleteUser;
		private User grantUserAuthorities;
		private User revokeUserAuthorities;
		private Group createGroup;
		private Group updateGroup;
		private Group deleteGroup;
		private Group addGroupMember;
		private Group removeGroupMember;
		private Group grantGroupAuthorities;
		private Group revokeGroupAuthorities;

		/**
		 * Creates a new claim.
		 */
		public Builder withCreateClaim(Claim createClaimParam) {
			this.createClaim = createClaimParam;
			return this;
		}

		/**
		 * Updates an existing claim.
		 */
		public Builder withUpdateClaim(Claim updateClaimParam) {
			this.updateClaim = updateClaimParam;
			return this;
		}

		/**
		 * Deletes an existing claim.
		 */
		public Builder withDeleteClaim(Claim deleteClaimParam) {
			this.deleteClaim = deleteClaimParam;
			return this;
		}

		/**
		 * Creates a new declaration.
		 */
		public Builder withCreateDeclaration(Declaration createDeclarationParam) {
			this.createDeclaration = createDeclarationParam;
			return this;
		}

		/**
		 * Updates an existing declaration.
		 */
		public Builder withUpdateDeclaration(Declaration updateDeclarationParam) {
			this.updateDeclaration = updateDeclarationParam;
			return this;
		}

		/**
		 * Deletes an existing declaration.
		 */
		public Builder withDeleteDeclaration(Declaration deleteDeclarationParam) {
			this.deleteDeclaration = deleteDeclarationParam;
			return this;
		}

		/**
		 * Creates an entity link.
		 */
		public Builder withCreateEntityLink(EntityLink createEntityLinkParam) {
			this.createEntityLink = createEntityLinkParam;
			return this;
		}

		/**
		 * Updates an existing entity link.
		 */
		public Builder withUpdateEntityLink(EntityLink updateEntityLinkParam) {
			this.updateEntityLink = updateEntityLinkParam;
			return this;
		}

		/**
		 * Deletes an entity link.
		 */
		public Builder withDeleteEntityLink(EntityLink deleteEntityLinkParam) {
			this.deleteEntityLink = deleteEntityLinkParam;
			return this;
		}

		/**
		 * Create a new journal.
		 */
		public Builder withCreateJournal(Journal createJournalParam) {
			this.createJournal = createJournalParam;
			return this;
		}

		/**
		 * Updates an existing journal.
		 */
		public Builder withUpdateJournal(Journal updateJournalParam) {
			this.updateJournal = updateJournalParam;
			return this;
		}

		/**
		 * Deletes an existing journal.
		 */
		public Builder withDeleteJournal(Journal deleteJournalParam) {
			this.deleteJournal = deleteJournalParam;
			return this;
		}

		/**
		 * Creates a new person.
		 */
		public Builder withCreatePerson(Person createPersonParam) {
			this.createPerson = createPersonParam;
			return this;
		}

		/**
		 * Updates an existing person.
		 */
		public Builder withUpdatePerson(Person updatePersonParam) {
			this.updatePerson = updatePersonParam;
			return this;
		}

		/**
		 * Deletes an existing person.
		 */
		public Builder withDeletePerson(Person deletePersonParam) {
			this.deletePerson = deletePersonParam;
			return this;
		}

		/**
		 * Creates a new publication.
		 */
		public Builder withCreatePublication(Publication createPublicationParam) {
			this.createPublication = createPublicationParam;
			return this;
		}

		/**
		 * Updates an existing publication.
		 */
		public Builder withUpdatePublication(Publication updatePublicationParam) {
			this.updatePublication = updatePublicationParam;
			return this;
		}

		/**
		 * Deletes an existing publication.
		 */
		public Builder withDeletePublication(Publication deletePublicationParam) {
			this.deletePublication = deletePublicationParam;
			return this;
		}

		/**
		 * Creates a new publisher.
		 */
		public Builder withCreatePublisher(Publisher createPublisherParam) {
			this.createPublisher = createPublisherParam;
			return this;
		}

		/**
		 * Updates an existing publisher.
		 */
		public Builder withUpdatePublisher(Publisher updatePublisherParam) {
			this.updatePublisher = updatePublisherParam;
			return this;
		}

		/**
		 * Deletes an existing publisher.
		 */
		public Builder withDeletePublisher(Publisher deletePublisherParam) {
			this.deletePublisher = deletePublisherParam;
			return this;
		}

		/**
		 * Creates a new quotation.
		 */
		public Builder withCreateQuotation(Quotation createQuotationParam) {
			this.createQuotation = createQuotationParam;
			return this;
		}

		/**
		 * Updates an existing quotation.
		 */
		public Builder withUpdateQuotation(Quotation updateQuotationParam) {
			this.updateQuotation = updateQuotationParam;
			return this;
		}

		/**
		 * Deletes an existing quotation.
		 */
		public Builder withDeleteQuotation(Quotation deleteQuotationParam) {
			this.deleteQuotation = deleteQuotationParam;
			return this;
		}

		/**
		 * Creates a new topic.
		 */
		public Builder withCreateTopic(Topic createTopicParam) {
			this.createTopic = createTopicParam;
			return this;
		}

		/**
		 * Updates an existing topic.
		 */
		public Builder withUpdateTopic(Topic updateTopicParam) {
			this.updateTopic = updateTopicParam;
			return this;
		}

		/**
		 * Deletes an existing topic.
		 */
		public Builder withDeleteTopic(Topic deleteTopicParam) {
			this.deleteTopic = deleteTopicParam;
			return this;
		}

		/**
		 * Sets entity status.
		 */
		public Builder withSetEntityStatus(Boolean setEntityStatusParam) {
			this.setEntityStatus = setEntityStatusParam;
			return this;
		}

		/**
		 * Creates a new user.
		 */
		public Builder withCreateUser(User createUserParam) {
			this.createUser = createUserParam;
			return this;
		}

		/**
		 * Updates an existing user.
		 */
		public Builder withUpdateUser(User updateUserParam) {
			this.updateUser = updateUserParam;
			return this;
		}

		/**
		 * Updates an existing user.
		 */
		public Builder withDeleteUser(User deleteUserParam) {
			this.deleteUser = deleteUserParam;
			return this;
		}

		/**
		 * Grants authorities to a user. The specified authorities are added to any existing ones.
		 */
		public Builder withGrantUserAuthorities(User grantUserAuthoritiesParam) {
			this.grantUserAuthorities = grantUserAuthoritiesParam;
			return this;
		}

		/**
		 * Revokes authorities from a user. The specified authorities are removed from the user; other authorities
		 * remain intact.
		 */
		public Builder withRevokeUserAuthorities(User revokeUserAuthoritiesParam) {
			this.revokeUserAuthorities = revokeUserAuthoritiesParam;
			return this;
		}

		/**
		 * Creates a new group.
		 */
		public Builder withCreateGroup(Group createGroupParam) {
			this.createGroup = createGroupParam;
			return this;
		}

		/**
		 * Updates an existing group.
		 */
		public Builder withUpdateGroup(Group updateGroupParam) {
			this.updateGroup = updateGroupParam;
			return this;
		}

		/**
		 * Deletes an existing group.
		 */
		public Builder withDeleteGroup(Group deleteGroupParam) {
			this.deleteGroup = deleteGroupParam;
			return this;
		}

		/**
		 * Adds a user to a group.
		 */
		public Builder withAddGroupMember(Group addGroupMemberParam) {
			this.addGroupMember = addGroupMemberParam;
			return this;
		}

		/**
		 * Removes a user from a group.
		 */
		public Builder withRemoveGroupMember(Group removeGroupMemberParam) {
			this.removeGroupMember = removeGroupMemberParam;
			return this;
		}

		/**
		 * Grants authorities to a group. The specified authorities are added to any
		 * existing ones.
		 */
		public Builder withGrantGroupAuthorities(Group grantGroupAuthoritiesParam) {
			this.grantGroupAuthorities = grantGroupAuthoritiesParam;
			return this;
		}

		/**
		 * Revokes authorities from a group. The specified authorities are removed from
		 * the group; other authorities remain intact.
		 */
		public Builder withRevokeGroupAuthorities(Group revokeGroupAuthoritiesParam) {
			this.revokeGroupAuthorities = revokeGroupAuthoritiesParam;
			return this;
		}

		public Mutation build() {
			Mutation _object = new Mutation();
			_object.setCreateClaim(this.createClaim);
			_object.setUpdateClaim(this.updateClaim);
			_object.setDeleteClaim(this.deleteClaim);
			_object.setCreateDeclaration(this.createDeclaration);
			_object.setUpdateDeclaration(this.updateDeclaration);
			_object.setDeleteDeclaration(this.deleteDeclaration);
			_object.setCreateEntityLink(this.createEntityLink);
			_object.setUpdateEntityLink(this.updateEntityLink);
			_object.setDeleteEntityLink(this.deleteEntityLink);
			_object.setCreateJournal(this.createJournal);
			_object.setUpdateJournal(this.updateJournal);
			_object.setDeleteJournal(this.deleteJournal);
			_object.setCreatePerson(this.createPerson);
			_object.setUpdatePerson(this.updatePerson);
			_object.setDeletePerson(this.deletePerson);
			_object.setCreatePublication(this.createPublication);
			_object.setUpdatePublication(this.updatePublication);
			_object.setDeletePublication(this.deletePublication);
			_object.setCreatePublisher(this.createPublisher);
			_object.setUpdatePublisher(this.updatePublisher);
			_object.setDeletePublisher(this.deletePublisher);
			_object.setCreateQuotation(this.createQuotation);
			_object.setUpdateQuotation(this.updateQuotation);
			_object.setDeleteQuotation(this.deleteQuotation);
			_object.setCreateTopic(this.createTopic);
			_object.setUpdateTopic(this.updateTopic);
			_object.setDeleteTopic(this.deleteTopic);
			_object.setSetEntityStatus(this.setEntityStatus);
			_object.setCreateUser(this.createUser);
			_object.setUpdateUser(this.updateUser);
			_object.setDeleteUser(this.deleteUser);
			_object.setGrantUserAuthorities(this.grantUserAuthorities);
			_object.setRevokeUserAuthorities(this.revokeUserAuthorities);
			_object.setCreateGroup(this.createGroup);
			_object.setUpdateGroup(this.updateGroup);
			_object.setDeleteGroup(this.deleteGroup);
			_object.setAddGroupMember(this.addGroupMember);
			_object.setRemoveGroupMember(this.removeGroupMember);
			_object.setGrantGroupAuthorities(this.grantGroupAuthorities);
			_object.setRevokeGroupAuthorities(this.revokeGroupAuthorities);
			return _object;
		}

	}

}
