/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import java.net.URL;

import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * An input for creating or updating a publisher.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("PublisherInput")
public class PublisherInput extends AbstractTrackedEntityInput {

	/**
	 * The publisher name.
	 */
	@GraphQLScalar(fieldName = "name", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String name;

	/**
	 * The publisher location.
	 */
	@GraphQLScalar(fieldName = "location", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String location;

	/**
	 * The ISO-3166-1 alpha-2 code for the publisher's country.
	 */
	@GraphQLScalar(fieldName = "country", graphQLTypeSimpleName = "Country", javaClass = String.class, listDepth = 0)
	String country;

	/**
	 * URL of publisher's home page.
	 */
	@GraphQLScalar(fieldName = "url", graphQLTypeSimpleName = "URL", javaClass = URL.class, listDepth = 0)
	URL url;

	/**
	 * The number of journals published.
	 */
	@GraphQLScalar(fieldName = "journalCount", graphQLTypeSimpleName = "Int", javaClass = Integer.class, listDepth = 0)
	Integer journalCount;

	/**
	 * Notes on the publisher.
	 */
	@GraphQLScalar(fieldName = "notes", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String notes;

	/**
	 * The publisher name.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * The publisher name.
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * The publisher location.
	 */
	public void setLocation(String location) {
		this.location = location;
	}

	/**
	 * The publisher location.
	 */
	public String getLocation() {
		return this.location;
	}

	/**
	 * The ISO-3166-1 alpha-2 code for the publisher's country.
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * The ISO-3166-1 alpha-2 code for the publisher's country.
	 */
	public String getCountry() {
		return this.country;
	}

	/**
	 * URL of publisher's home page.
	 */
	public void setUrl(URL url) {
		this.url = url;
	}

	/**
	 * URL of publisher's home page.
	 */
	public URL getUrl() {
		return this.url;
	}

	/**
	 * The number of journals published.
	 */
	public void setJournalCount(Integer journalCount) {
		this.journalCount = journalCount;
	}

	/**
	 * The number of journals published.
	 */
	public Integer getJournalCount() {
		return this.journalCount;
	}

	/**
	 * Notes on the publisher.
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * Notes on the publisher.
	 */
	public String getNotes() {
		return this.notes;
	}

	public String toString() {
		return "PublisherInput {" //
			+ "id: " + this.id //
			+ ", " //
			+ "rating: " + this.rating //
			+ ", " //
			+ "name: " + this.name //
			+ ", " //
			+ "location: " + this.location //
			+ ", " //
			+ "country: " + this.country //
			+ ", " //
			+ "url: " + this.url //
			+ ", " //
			+ "journalCount: " + this.journalCount //
			+ ", " //
			+ "notes: " + this.notes //
			+ "}"; //
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractTrackedEntityInput.Builder<Builder, PublisherInput> {

		private String name;
		private String location;
		private String country;
		private URL url;
		private Integer journalCount;
		private String notes;

		/**
		 * The publisher name.
		 */
		public Builder withName(String nameParam) {
			this.name = nameParam;
			return this;
		}

		/**
		 * The publisher location.
		 */
		public Builder withLocation(String locationParam) {
			this.location = locationParam;
			return this;
		}

		/**
		 * The ISO-3166-1 alpha-2 code for the publisher's country.
		 */
		public Builder withCountry(String countryParam) {
			this.country = countryParam;
			return this;
		}

		/**
		 * URL of publisher's home page.
		 */
		public Builder withUrl(URL urlParam) {
			this.url = urlParam;
			return this;
		}

		/**
		 * The number of journals published.
		 */
		public Builder withJournalCount(Integer journalCountParam) {
			this.journalCount = journalCountParam;
			return this;
		}

		/**
		 * Notes on the publisher.
		 */
		public Builder withNotes(String notesParam) {
			this.notes = notesParam;
			return this;
		}

		@Override
		public PublisherInput build() {
			PublisherInput _object = build(new PublisherInput());
			_object.setName(this.name);
			_object.setLocation(this.location);
			_object.setCountry(this.country);
			_object.setUrl(this.url);
			_object.setJournalCount(this.journalCount);
			_object.setNotes(this.notes);
			return _object;
		}

	}

}
