/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server and web client.
 * Copyright © 2024 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import java.net.URI;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

import org.dataloader.DataLoader;

import graphql.schema.DataFetchingEnvironment;

import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Transient;
import java.util.List;

import com.graphql_java_generator.annotation.GraphQLDirective;

/**
 * An association between a topic and an entity record.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@Entity
@GraphQLObjectType("TopicRef")
// @Transactional
@SuppressWarnings("unused")
public class TopicRef implements IBaseEntity {

	// NOTE: only necessary because graphql-java-generator emits code with errors (missing ctor) if there is no ID
	// field.
	/**
	 * The unique topic ref identifier.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@GraphQLScalar(fieldName = "id", graphQLTypeSimpleName = "ID", javaClass = Long.class, listDepth = 0)
	Long id;

	/**
	 * The associated topic.
	 */
	@GraphQLNonScalar(fieldName = "topic", graphQLTypeSimpleName = "Topic", javaClass = Topic.class, listDepth = 0)
	@ManyToOne(fetch = FetchType.LAZY, optional = false)
	@JoinColumn(name = "topic_id", nullable = false)
	Topic topic;

	/**
	 * The associated entity kind.
	 */
	@GraphQLScalar(fieldName = "entityKind", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String entityKind;

	// TODO: consider whether to return the identifier or the entity record.
	/**
	 * The unique identifier of the associated record.
	 */
	@GraphQLScalar(fieldName = "entityId", graphQLTypeSimpleName = "Long", javaClass = Long.class, listDepth = 0)
	Long entityId;

	/**
	 * The associated record.
	 */
	@Transient
	@GraphQLNonScalar(fieldName = "entity", graphQLTypeSimpleName = "ITopicalEntity", javaClass = ITopicalEntity.class,
		listDepth = 0)
	ITopicalEntity entity;

	/**
	 * The locations within the associated record, one per line.
	 */
	@Transient
	@GraphQLScalar(fieldName = "locations", graphQLTypeSimpleName = "URI", javaClass = URI.class, listDepth = 1)
	List<URI> locations;

	// NOTE: only necessary because graphql-java-generator emits code with errors (missing ctor) if there is no ID
	// field.
	/**
	 * The unique topic ref identifier.
	 */
	@Override
	public void setId(Long id) {
		this.id = id;
	}

	// NOTE: only necessary because graphql-java-generator emits code with errors (missing ctor) if there is no ID
	// field.
	/**
	 * The unique topic ref identifier.
	 */
	@Override
	public Long getId() {
		return this.id;
	}

	/**
	 * The associated topic.
	 */
	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	/**
	 * The associated topic.
	 */
	public Topic getTopic() {
		return this.topic;
	}

	/**
	 * The associated entity kind.
	 */
	public void setEntityKind(String entityKind) {
		this.entityKind = entityKind;
	}

	/**
	 * The associated entity kind.
	 */
	public String getEntityKind() {
		return this.entityKind;
	}

	// TODO: consider whether to return the identifier or the entity record.
	/**
	 * The unique identifier of the associated record.
	 */
	public void setEntityId(Long entityId) {
		this.entityId = entityId;
	}

	// TODO: consider whether to return the identifier or the entity record.
	/**
	 * The unique identifier of the associated record.
	 */
	public Long getEntityId() {
		return this.entityId;
	}

	/**
	 * The associated record.
	 */
	public void setEntity(ITopicalEntity entity) {
		this.entity = entity;
	}

	/**
	 * The associated record.
	 */
	public ITopicalEntity getEntity() {
		return this.entity;
	}

	/**
	 * The locations within the associated record, one per line.
	 */
	public void setLocations(List<URI> locations) {
		this.locations = locations;
	}

	/**
	 * The locations within the associated record, one per line.
	 */
	public List<URI> getLocations() {
		return this.locations;
	}

	public String toString() {
		return "TopicRef {" //$NON-NLS-1$
			+ "id: " + this.id //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			// + "topic_id: " + this.topic_id //$NON-NLS-1$
			// + ", " //$NON-NLS-1$
			+ "topic: " + this.topic //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "entityKind: " + this.entityKind //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "entityId: " + this.entityId //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "entity: " + this.entity //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "locations: " + this.locations //$NON-NLS-1$
			+ "}"; //$NON-NLS-1$
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {

		private Long id;
		private Topic topic;
		private String entityKind;
		private Long entityId;
		private ITopicalEntity entity;
		private List<URI> locations;

		// NOTE: only necessary because graphql-java-generator emits code with errors (missing ctor) if there is no ID
		// field.
		/**
		 * The unique topic ref identifier.
		 */
		public Builder withId(Long idParam) {
			this.id = idParam;
			return this;
		}

		/**
		 * The associated topic.
		 */
		public Builder withTopic(Topic topicParam) {
			this.topic = topicParam;
			return this;
		}

		/**
		 * The associated entity kind.
		 */
		public Builder withEntityKind(String entityKindParam) {
			this.entityKind = entityKindParam;
			return this;
		}

		// TODO: consider whether to return the identifier or the entity record.
		/**
		 * The unique identifier of the associated record.
		 */
		public Builder withEntityId(Long entityIdParam) {
			this.entityId = entityIdParam;
			return this;
		}

		/**
		 * The associated record.
		 */
		public Builder withEntity(ITopicalEntity entityParam) {
			this.entity = entityParam;
			return this;
		}

		/**
		 * The locations within the associated record, one per line.
		 */
		public Builder withLocations(List<URI> locationsParam) {
			this.locations = locationsParam;
			return this;
		}

		public TopicRef build() {
			TopicRef _object = new TopicRef();
			_object.setId(this.id);
			// _object.setTopic_id(this.topic_id);
			_object.setTopic(this.topic);
			_object.setEntityKind(this.entityKind);
			_object.setEntityId(this.entityId);
			_object.setEntity(this.entity);
			_object.setLocations(this.locations);
			return _object;
		}

	}

}
