/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

/**
 * An association between a topic and an entity record.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@Entity
@GraphQLObjectType("TopicRef")
public class TopicRef implements IBaseEntity {

	// NOTE: only necessary because graphql-java-generator emits code with errors (missing ctor) if there is no ID
	// field.
	/**
	 * The unique topic ref identifier.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@GraphQLScalar(fieldName = "id", graphQLTypeSimpleName = "ID", javaClass = Long.class, listDepth = 0)
	Long id;

	/**
	 * The unique identifier of the associated topic.
	 */
	@GraphQLScalar(fieldName = "topicId", graphQLTypeSimpleName = "Long", javaClass = Long.class, listDepth = 0)
	Long topicId;

	/**
	 * The unique identifier of the associated entity record.
	 */
	@GraphQLScalar(fieldName = "entityId", graphQLTypeSimpleName = "Long", javaClass = Long.class, listDepth = 0)
	Long entityId;

	/**
	 * The associated entity kind.
	 */ 
	@GraphQLScalar(fieldName = "entityKind", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String entityKind;

	/**
	 * The locations within the associated record, one per line.
	 */
	@GraphQLScalar(fieldName = "locations", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String locations;

	// NOTE: only necessary because graphql-java-generator emits code with errors (missing ctor) if there is no ID
	// field.
	/**
	 * The unique topic ref identifier.
	 */
	@Override
	public void setId(Long id) {
		this.id = id;
	}

	// NOTE: only necessary because graphql-java-generator emits code with errors (missing ctor) if there is no ID
	// field.
	/**
	 * The unique topic ref identifier.
	 */
	@Override
	public Long getId() {
		return this.id;
	}

	/**
	 * The unique identifier of the associated topic.
	 */
	public void setTopicId(Long topicId) {
		this.topicId = topicId;
	}

	/**
	 * The unique identifier of the associated topic.
	 */
	public Long getTopicId() {
		return this.topicId;
	}

	/**
	 * The unique identifier of the associated entity record.
	 */
	public void setEntityId(Long entityId) {
		this.entityId = entityId;
	}

	/**
	 * The unique identifier of the associated entity record.
	 */
	public Long getEntityId() {
		return this.entityId;
	}

	/**
	 * The associated entity kind.
	 */
	public void setEntityKind(String entityKind) {
		this.entityKind = entityKind;
	}

	/**
	 * The associated entity kind.
	 */
	public String getEntityKind() {
		return this.entityKind;
	}

	/**
	 * The locations within the associated record, one per line.
	 */
	public void setLocations(String locations) {
		this.locations = locations;
	}

	/**
	 * The locations within the associated record, one per line.
	 */
	public String getLocations() {
		return this.locations;
	}

	public String toString() {
		return "TopicRef {" //$NON-NLS-1$
			+ "id: " + this.id //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			// + "topic_id: " + this.topic_id //$NON-NLS-1$
			// + ", " //$NON-NLS-1$
			+ "topicId: " + this.topicId //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "entityId: " + this.entityId //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "entityKind: " + this.entityKind //$NON-NLS-1$
			+ ", " //$NON-NLS-1$
			+ "locations: " + this.locations //$NON-NLS-1$
			+ "}"; //$NON-NLS-1$
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {

		private Long id;
		private Long topicId;
		private Long entityId;
		private String entityKind;
		private String locations;

		// NOTE: only necessary because graphql-java-generator emits code with errors (missing ctor) if there is no ID
		// field.
		/**
		 * The unique topic ref identifier.
		 */
		public Builder withId(Long idParam) {
			this.id = idParam;
			return this;
		}

		/**
		 * The unique identifier of the associated topic.
		 */
		public Builder withTopicId(Long topicIdParam) {
			this.topicId = topicIdParam;
			return this;
		}

		/**
		 * The unique identifier of the associated record.
		 */
		public Builder withEntityId(Long entityIdParam) {
			this.entityId = entityIdParam;
			return this;
		}

		/**
		 * The associated entity kind.
		 */ 
		public Builder withEntityKind(String entityKindParam) {
			this.entityKind = entityKindParam;
			return this;
		}	

		/**
		 * The locations within the associated record, one per line.
		 */
		public Builder withLocations(String locationsParam) {
			this.locations = locationsParam;
			return this;
		}

		public TopicRef build() {
			TopicRef _object = new TopicRef();
			_object.setId(this.id);
			_object.setTopicId(this.topicId);
			_object.setEntityId(this.entityId);
			_object.setEntityKind(this.entityKind);
			_object.setLocations(this.locations);
			return _object;
		}

	}

}
