/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.model;

import java.util.List;

import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * Parameters to filter an {@code ITrackedEntity} query.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("TrackedEntityQueryFilter")
public class TrackedEntityQueryFilter {

	/**
	 * Return only records with these status codes (default: ALL).
	 */
	@GraphQLScalar(fieldName = "status", graphQLTypeSimpleName = "StatusKind", javaClass = StatusKind.class,
		listDepth = 1)
	List<StatusKind> status;

	/**
	 * Free text search string.
	 */
	@GraphQLScalar(fieldName = "text", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String text;

	/**
	 * Whether to search {@code text} in advanced (boolean) mode.
	 */
	@GraphQLScalar(fieldName = "advancedSearch", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
		listDepth = 0)
	Boolean advancedSearch = false;

	/**
	 * The identifier of the single record to return.
	 */
	@GraphQLScalar(fieldName = "recordId", graphQLTypeSimpleName = "ID", javaClass = Long.class, listDepth = 0)
	Long recordId;

	/**
	 * Return only records with these status codes (default: ALL).
	 */
	public final void setStatus(List<StatusKind> status) {
		this.status = status;
	}

	/**
	 * Return only records with these status codes (default: ALL).
	 */
	public final List<StatusKind> getStatus() {
		return this.status;
	}

	/**
	 * Free text search string.
	 */
	public final void setText(String text) {
		this.text = text;
	}

	/**
	 * Free text search string.
	 */
	public final String getText() {
		return this.text;
	}

	/**
	 * Whether to search {@code text} in advanced (boolean) mode.
	 */
	public final void setAdvancedSearch(Boolean advancedSearch) {
		this.advancedSearch = advancedSearch;
	}

	/**
	 * Whether to search {@code text} in advanced (boolean) mode.
	 */
	public final Boolean getAdvancedSearch() {
		return this.advancedSearch;
	}

	/**
	 * The identifier of the single record to return.
	 */
	public final void setRecordId(Long recordId) {
		this.recordId = recordId;
	}

	/**
	 * The identifier of the single record to return.
	 */
	public final Long getRecordId() {
		return recordId;
	}

	public String toString() {
		return "TrackedEntityQueryFilter {" //
			+ "status: " + this.status //
			+ ", " //
			+ "text: " + this.text //
			+ ", " //
			+ "advancedSearch: " + this.advancedSearch //
			+ ", " //
			+ "recordId: " + this.recordId //
			+ "}"; //
	}

	public static Builder builderForTrackedEntityQueryFilter() {
		return new Builder();
	}

	@SuppressWarnings("unchecked")
	abstract static class AbstractBuilder<B extends AbstractBuilder<B, T>, T extends TrackedEntityQueryFilter> {

		private List<StatusKind> status;
		private String text;
		private Boolean advancedSearch;
		private Long recordId;

		/**
		 * Return only records with these status codes (default: ALL).
		 */
		public final B withStatus(List<StatusKind> statusParam) {
			this.status = statusParam;
			return (B)this;
		}

		/**
		 * Free text search string.
		 */
		public final B withText(String textParam) {
			this.text = textParam;
			return (B)this;
		}

		/**
		 * Whether to search {@code text} in advanced (boolean) mode.
		 */
		public final B withAdvancedSearch(Boolean advancedSearch) {
			this.advancedSearch = advancedSearch;
			return (B)this;
		}

		/**
	 	 * The identifier of the single record to return.
		 */
		public final B withRecordId(Long recordId) {
			this.recordId = recordId;
			return (B)this;
		}

		T build(T _object) {
			_object.setStatus(this.status);
			_object.setText(this.text);
			_object.setAdvancedSearch(this.advancedSearch);
			_object.setRecordId(this.recordId);
			return _object;
		}

		public abstract T build();

	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class by calling the
	 * {@link #builderForTrackedEntityQueryFilter()} method.
	 */
	public static class Builder extends AbstractBuilder<Builder, TrackedEntityQueryFilter> {

		public TrackedEntityQueryFilter build() {
			return build(new TrackedEntityQueryFilter());
		}

	}

}
