# ----------------------------------------------------------------------------------------------------------------------
# Evidence Engine: A system for managing evidence on arbitrary scientific topics.
# Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
# Copyright © 2024-26 Adrian Price. All rights reserved.
#
# This file is part of Evidence Engine.
#
# Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
# GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
# If not, see <https://www.gnu.org/licenses/>. 
# ----------------------------------------------------------------------------------------------------------------------

# Settings for integration-test Spring profile: server launched normally but using H2 in-memory database.

# APPLICATION (integration-test mode)
server.servlet.context-path=/api
spring.application.name=ee-server (integration test)
spring.profiles.active=integration-test
web.server.url=http://localhost:3000
data.server.url=http://localhost:8080
# NOTE: setting it to /tmp doesn't work, because Tomcat's systemd configuration has PrivateTmp=yes, which isn't visible to MariaDB.
# NOR does setting it to /opt/evidence-engine, even with tomcat service configured with ReadWritePaths=/opt/evidence-engine, as
# ProtectSystem=on mounts /opt as read-only, which cannot be overridden for a sub-directory.
data.server.tmpdir=/var/lib/evidence-engine

# GRAPHQL
spring.graphql.http.path=/graphql
spring.graphql.websocket.path=/graphql
spring.graphql.graphiql.path=/graphiql
spring.graphql.graphiql.enabled=true
spring.graphql.schema.printer.enabled=true

# JPA
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:evidence_engine;DB_CLOSE_DELAY=-1
# spring.datasource.url=jdbc:h2:file:/home/adrian/Documents/Databases/H2/evidence_engine
# spring.datasource.url=jdbc:h2:file:/home/adrian/Documents/Databases/H2/evidence_engine-integration-test
spring.datasource.username=admin
spring.datasource.password=xxxxxxxx
# Without this line you get an error relating to unknown dialect,
# but with it you get a warning relating to auto-detection of dialect.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.sql.init.schema-locations=classpath:db/schema-h2.sql
spring.sql.init.data-locations=classpath:db/data.sql

# We maintain the DDL manually, so we don't want Hibernate to try to create or update the schema automatically.
#spring.jpa.properties.hibernate.ddl-auto=none|validate|update|create|create-drop
spring.jpa.properties.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=none

# Is this a viable solution to JPA lazy fetch not working?
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# This is necessary because H2 (for testing) doesn't recognise unquoted lowercase table names.
# HOWEVER, MariaDB (for dev & prod) needs sql_mode to include ANSI_QUOTES in order to accept the double quotes.
spring.jpa.hibernate.naming.physical-strategy=io.github.demonfiddler.ee.server.util.PhysicalNamingStrategyQuotedSnakeCaseImpl

# Sends SQL unconditionally to STDOUT:
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.server-url=http://localhost:8080/api
jwt.header=Authorization
jwt.prefix=Bearer
# Generate with node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
jwt.secret=b84eff52e9dbbf04752201e61ee7e8ebf246f9b618cfcafd8ade090ec7f2cc8a
# JWT token lifetime of 4 hours = 4 x 60 x 60 x 1000
jwt.duration-ms=14400000
# Note: "groups", "roles" and "entitlements" are IANA-registered JWT claim names.
jwt.authority-claim=entitlements

# LOGGING
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.orm.jdbc.bind=TRACE
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# logging.group.repository=io.github.demonfiddler.ee.server.repository
# logging.level.io.github.demonfiddler.ee.server.util=DEBUG
# logging.level.io.github.demonfiddler.ee.server.repository=TRACE
# logging.level.io.github.demonfiddler.ee.server.rest.api=TRACE
# logging.level.org.springframework.boot.autoconfigure.security=DEBUG
# logging.level.org.springframework.security=DEBUG

# SESSION CONTROL
management.endpoints.web.exposure.include=*
management.endpoint.shutdown.access=unrestricted
