-- Static lookup tables
CALL export_table_to_csv('abbreviation', CONCAT(:out_dir, 'abbreviation.csv'));
CALL export_table_to_csv('authority_kind', CONCAT(:out_dir, 'authority_kind.csv'));
CALL export_table_to_csv('country', CONCAT(:out_dir, 'country.csv'));
CALL export_table_to_csv('declaration_kind', CONCAT(:out_dir, 'declaration_kind.csv'));
CALL export_table_to_csv('entity_kind', CONCAT(:out_dir, 'entity_kind.csv'));
CALL export_table_to_csv('publication_kind', CONCAT(:out_dir, 'publication_kind.csv'));
CALL export_table_to_csv('status_kind', CONCAT(:out_dir, 'status_kind.csv'));
CALL export_table_to_csv('transaction_kind', CONCAT(:out_dir, 'transaction_kind.csv'));

-- Application data tables
CALL export_table_to_csv('claim', CONCAT(:out_dir, 'claim.csv'));
CALL export_table_to_csv('comment', CONCAT(:out_dir, 'comment.csv'));
CALL export_table_to_csv('declaration', CONCAT(:out_dir, 'declaration.csv'));
CALL export_table_to_csv('entity', CONCAT(:out_dir, 'entity.csv'));
CALL export_table_to_csv('entity_link', CONCAT(:out_dir, 'entity_link.csv'));
CALL export_table_to_csv('group', CONCAT(:out_dir, 'group.csv'));
CALL export_table_to_csv('group_authority', CONCAT(:out_dir, 'group_authority.csv'));
CALL export_table_to_csv('group_user', CONCAT(:out_dir, 'group_user.csv'));
CALL export_table_to_csv('journal', CONCAT(:out_dir, 'journal.csv'));
CALL export_table_to_csv('log', CONCAT(:out_dir, 'log.csv'));
CALL export_table_to_csv('person', CONCAT(:out_dir, 'person.csv'));
CALL export_table_to_csv('publication', CONCAT(:out_dir, 'publication.csv'));
CALL export_table_to_csv('publisher', CONCAT(:out_dir, 'publisher.csv'));
CALL export_table_to_csv('quotation', CONCAT(:out_dir, 'quotation.csv'));
CALL export_table_to_csv('topic', CONCAT(:out_dir, 'topic.csv'));
CALL export_table_to_csv('user', CONCAT(:out_dir, 'user.csv'));
CALL export_table_to_csv('user_authority', CONCAT(:out_dir, 'user_authority.csv'));