/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

plugins {
	id 'java'
	alias(libs.plugins.springBootPlugin)
	alias(libs.plugins.graphqlJavaGeneratorPlugin)
	alias(libs.plugins.openapiGeneratorPlugin)
	// alias(libs.plugins.netflixDgsCodegenPlugin)
}

dependencies {
	implementation project(':common')

	// Spring Boot platform
	implementation(platform(libs.springBootBom))

	// REVIEW: do we really need all these dependencies for code generation alone?
	implementation libs.springBootStarterDataJpa
	implementation libs.springBootStarterLogging
	implementation libs.springGraphql
	implementation libs.jacksonAnnotations
	implementation libs.jacksonCore
	implementation libs.jacksonDatabind

	implementation libs.bundles.graphqlJavaGeneratorClientRuntimeImpl

	implementation libs.bundles.graphqlJavaGeneratorServerRuntimeImpl // only if copyRuntimeSources = false
	compileOnly libs.bundles.graphqlJavaGeneratorServerRuntimeCompileOnly

	implementation libs.graphqlJavaExtScalars
	implementation libs.openapiGenerator
	implementation libs.openapiGeneratorCli
}

// We just want to generate the sources, not compile them, so disable the Java compile, jar and bootJar tasks.
tasks.withType(JavaCompile).configureEach {
    enabled = false
}

tasks.named('bootJar') {
    enabled = false
}

tasks.named('jar') {
    enabled = false
}

tasks.named('test') {
    useJUnitPlatform()
}

// Netflix DGS code generator configuration. See https://netflix.github.io/dgs/generating-code-from-schema/.
/*
generateJava{
	schemaPaths = ["${projectDir}/src/main/resources/graphql"] // List of directories containing schema files
	packageName = 'io.github.demonfiddler.ee.server' // The package name to use to generate sources
	// subPackageNameClient = client
	// subPackageNameDatafetchers = datafetchers
	// subPackageNameTypes = types
	// language = java
	// typeMapping (A Map where each key is a GraphQL type, and the value the FQN of a Java class)
	// generateBoxedTypes = false
	generateServer = true // false
	// generateDataTypes = true
	// generateInterfaces = false
	// generatedSourcesDir = build
	// includeQueries = [...]
	// includeMutations = [...]
	// includeSubscriptions= [...]
	// skipEntityQueries = false
	// shortProjectionNames = false
	// maxProjectionDepth = 10
	// includeEnumImports = (map)
	// includeImports = mapOf(Pair('validator', 'com.test.validator')),
	// includeClassImports = mapOf('ValidPerson' to mapOf(Pair('BasicValidation', 'com.test.validator.groups')))
	// generateCustomAnnotations = false
	// addGeneratedAnnotation = false
	// disableDatesInGeneratedAnnotation = false
}
*/

openApiGenerate {
    generatorName.set('spring')
    inputSpec.set(file("$rootDir/server/src/main/resources/rest/openapi.yaml"))
    outputDir.set(layout.buildDirectory.dir('generated/sources/openapiServer'))
	packageName.set('io.github.demonfiddler.ee.server.rest')
    apiPackage.set('io.github.demonfiddler.ee.server.rest.api')
    invokerPackage.set('io.github.demonfiddler.ee.server.rest.invoker')
    modelPackage.set('io.github.demonfiddler.ee.server.rest.model')
    configOptions.put('dateLibrary', 'java8')
}

openApiValidate {
    inputSpec.set(file("$rootDir/server/src/main/resources/rest/openapi.yaml"))
}

apply from: 'graphql-codegen.gradle'
