/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>.
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.server.datafetcher;

import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

import io.github.demonfiddler.ee.server.model.AbstractLinkableEntity;
import io.github.demonfiddler.ee.server.model.AbstractTrackedEntity;
import io.github.demonfiddler.ee.server.model.IBaseEntity;

/**
 * Logs each DataFetchersDelegate Spring component. It's used by POJO, when the handle data fetchers members. For
 * instance with this GraphQL type:
 * 
 * <PRE>
 * type Member {
 *     name(uppercase: Boolean): String
 * }
 * </PRE>
 * 
 * A <code>name(String)</code> data fetcher method is created in the generated Member POJO. It needs to call the
 * <code>name(String)</code> of the Member DataFetchersDelegate.<br/>
 * Since version 2.5
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@Component
public class DataFetchersDelegateRegistry {

	// This singleton is used by POJO to access to the DataFetchersDelegateMyQueryType created by Spring.
	public static DataFetchersDelegateRegistry dataFetchersDelegateRegistry;

	@SuppressWarnings("unused")
	private final ApplicationContext ctx;
	private final DataFetchersDelegateClaim dataFetchersDelegateClaim;
	private final DataFetchersDelegateClaimPage dataFetchersDelegateClaimPage;
	private final DataFetchersDelegateDeclaration dataFetchersDelegateDeclaration;
	private final DataFetchersDelegateDeclarationPage dataFetchersDelegateDeclarationPage;
	private final DataFetchersDelegateEntityLink dataFetchersDelegateEntityLink;
	private final DataFetchersDelegateEntityLinkPage dataFetchersDelegateEntityLinkPage;
	private final DataFetchersDelegateJournal dataFetchersDelegateJournal;
	private final DataFetchersDelegateJournalPage dataFetchersDelegateJournalPage;
	private final DataFetchersDelegateLog dataFetchersDelegateLog;
	private final DataFetchersDelegateLogPage dataFetchersDelegateLogPage;
	private final DataFetchersDelegatePerson dataFetchersDelegatePerson;
	private final DataFetchersDelegatePersonPage dataFetchersDelegatePersonPage;
	private final DataFetchersDelegatePublication dataFetchersDelegatePublication;
	private final DataFetchersDelegatePublicationPage dataFetchersDelegatePublicationPage;
	private final DataFetchersDelegatePublisher dataFetchersDelegatePublisher;
	private final DataFetchersDelegatePublisherPage dataFetchersDelegatePublisherPage;
	private final DataFetchersDelegateQuotation dataFetchersDelegateQuotation;
	private final DataFetchersDelegateQuotationPage dataFetchersDelegateQuotationPage;
	private final DataFetchersDelegateTopic dataFetchersDelegateTopic;
	private final DataFetchersDelegateTopicPage dataFetchersDelegateTopicPage;
	private final DataFetchersDelegateUser dataFetchersDelegateUser;
	private final DataFetchersDelegateUserPage dataFetchersDelegateUserPage;
	private final DataFetchersDelegateAuthPayload dataFetchersDelegateAuthPayload;
	private final DataFetchersDelegateQuery dataFetchersDelegateQuery;
	private final DataFetchersDelegateMutation dataFetchersDelegateMutation;
	private final DataFetchersDelegateITrackedEntity<AbstractTrackedEntity> dataFetchersDelegateITrackedEntity;
	private final DataFetchersDelegateILinkableEntity<AbstractLinkableEntity> dataFetchersDelegateILinkableEntity;
	private final DataFetchersDelegateIBaseEntity<IBaseEntity> dataFetchersDelegateIBaseEntity;
	private final DataFetchersDelegateIPage dataFetchersDelegateIPage;

	public DataFetchersDelegateRegistry(ApplicationContext ctx, DataFetchersDelegateClaim dataFetchersDelegateClaim,
		DataFetchersDelegateClaimPage dataFetchersDelegateClaimPage,
		DataFetchersDelegateDeclaration dataFetchersDelegateDeclaration,
		DataFetchersDelegateDeclarationPage dataFetchersDelegateDeclarationPage,
		DataFetchersDelegateEntityLink dataFetchersDelegateEntityLink,
		DataFetchersDelegateEntityLinkPage dataFetchersDelegateEntityLinkPage,
		DataFetchersDelegateJournal dataFetchersDelegateJournal,
		DataFetchersDelegateJournalPage dataFetchersDelegateJournalPage,
		DataFetchersDelegateLog dataFetchersDelegateLog, DataFetchersDelegateLogPage dataFetchersDelegateLogPage,
		DataFetchersDelegatePerson dataFetchersDelegatePerson,
		DataFetchersDelegatePersonPage dataFetchersDelegatePersonPage,
		DataFetchersDelegatePublication dataFetchersDelegatePublication,
		DataFetchersDelegatePublicationPage dataFetchersDelegatePublicationPage,
		DataFetchersDelegatePublisher dataFetchersDelegatePublisher,
		DataFetchersDelegatePublisherPage dataFetchersDelegatePublisherPage,
		DataFetchersDelegateQuotation dataFetchersDelegateQuotation,
		DataFetchersDelegateQuotationPage dataFetchersDelegateQuotationPage,
		DataFetchersDelegateTopic dataFetchersDelegateTopic,
		DataFetchersDelegateTopicPage dataFetchersDelegateTopicPage, DataFetchersDelegateUser dataFetchersDelegateUser,
		DataFetchersDelegateUserPage dataFetchersDelegateUserPage,
		DataFetchersDelegateAuthPayload dataFetchersDelegateAuthPayload,
		DataFetchersDelegateQuery dataFetchersDelegateQuery, DataFetchersDelegateMutation dataFetchersDelegateMutation,
		DataFetchersDelegateITrackedEntity<AbstractTrackedEntity> dataFetchersDelegateITrackedEntity,
		DataFetchersDelegateILinkableEntity<AbstractLinkableEntity> dataFetchersDelegateILinkableEntity,
		DataFetchersDelegateIBaseEntity<IBaseEntity> dataFetchersDelegateIBaseEntity,
		DataFetchersDelegateIPage dataFetchersDelegateIPage) {

		this.ctx = ctx;
		this.dataFetchersDelegateClaim = dataFetchersDelegateClaim;
		this.dataFetchersDelegateClaimPage = dataFetchersDelegateClaimPage;
		this.dataFetchersDelegateDeclaration = dataFetchersDelegateDeclaration;
		this.dataFetchersDelegateDeclarationPage = dataFetchersDelegateDeclarationPage;
		this.dataFetchersDelegateEntityLink = dataFetchersDelegateEntityLink;
		this.dataFetchersDelegateEntityLinkPage = dataFetchersDelegateEntityLinkPage;
		this.dataFetchersDelegateJournal = dataFetchersDelegateJournal;
		this.dataFetchersDelegateJournalPage = dataFetchersDelegateJournalPage;
		this.dataFetchersDelegateLog = dataFetchersDelegateLog;
		this.dataFetchersDelegateLogPage = dataFetchersDelegateLogPage;
		this.dataFetchersDelegatePerson = dataFetchersDelegatePerson;
		this.dataFetchersDelegatePersonPage = dataFetchersDelegatePersonPage;
		this.dataFetchersDelegatePublication = dataFetchersDelegatePublication;
		this.dataFetchersDelegatePublicationPage = dataFetchersDelegatePublicationPage;
		this.dataFetchersDelegatePublisher = dataFetchersDelegatePublisher;
		this.dataFetchersDelegatePublisherPage = dataFetchersDelegatePublisherPage;
		this.dataFetchersDelegateQuotation = dataFetchersDelegateQuotation;
		this.dataFetchersDelegateQuotationPage = dataFetchersDelegateQuotationPage;
		this.dataFetchersDelegateTopic = dataFetchersDelegateTopic;
		this.dataFetchersDelegateTopicPage = dataFetchersDelegateTopicPage;
		this.dataFetchersDelegateUser = dataFetchersDelegateUser;
		this.dataFetchersDelegateUserPage = dataFetchersDelegateUserPage;
		this.dataFetchersDelegateAuthPayload = dataFetchersDelegateAuthPayload;
		this.dataFetchersDelegateQuery = dataFetchersDelegateQuery;
		this.dataFetchersDelegateMutation = dataFetchersDelegateMutation;
		this.dataFetchersDelegateITrackedEntity = dataFetchersDelegateITrackedEntity;
		this.dataFetchersDelegateILinkableEntity = dataFetchersDelegateILinkableEntity;
		this.dataFetchersDelegateIBaseEntity = dataFetchersDelegateIBaseEntity;
		this.dataFetchersDelegateIPage = dataFetchersDelegateIPage;
		DataFetchersDelegateRegistry.dataFetchersDelegateRegistry = this;
	}

	public DataFetchersDelegateClaim getDataFetchersDelegateClaim() {
		return this.dataFetchersDelegateClaim;
	}

	public DataFetchersDelegateClaimPage getDataFetchersDelegateClaimPage() {
		return this.dataFetchersDelegateClaimPage;
	}

	public DataFetchersDelegateDeclaration getDataFetchersDelegateDeclaration() {
		return this.dataFetchersDelegateDeclaration;
	}

	public DataFetchersDelegateDeclarationPage getDataFetchersDelegateDeclarationPage() {
		return this.dataFetchersDelegateDeclarationPage;
	}

	public DataFetchersDelegateEntityLink getDataFetchersDelegateEntityLink() {
		return this.dataFetchersDelegateEntityLink;
	}

	public DataFetchersDelegateEntityLinkPage getDataFetchersDelegateEntityLinkPage() {
		return this.dataFetchersDelegateEntityLinkPage;
	}

	public DataFetchersDelegateJournal getDataFetchersDelegateJournal() {
		return this.dataFetchersDelegateJournal;
	}

	public DataFetchersDelegateJournalPage getDataFetchersDelegateJournalPage() {
		return this.dataFetchersDelegateJournalPage;
	}

	public DataFetchersDelegateLog getDataFetchersDelegateLog() {
		return this.dataFetchersDelegateLog;
	}

	public DataFetchersDelegateLogPage getDataFetchersDelegateLogPage() {
		return this.dataFetchersDelegateLogPage;
	}

	public DataFetchersDelegatePerson getDataFetchersDelegatePerson() {
		return this.dataFetchersDelegatePerson;
	}

	public DataFetchersDelegatePersonPage getDataFetchersDelegatePersonPage() {
		return this.dataFetchersDelegatePersonPage;
	}

	public DataFetchersDelegatePublication getDataFetchersDelegatePublication() {
		return this.dataFetchersDelegatePublication;
	}

	public DataFetchersDelegatePublicationPage getDataFetchersDelegatePublicationPage() {
		return this.dataFetchersDelegatePublicationPage;
	}

	public DataFetchersDelegatePublisher getDataFetchersDelegatePublisher() {
		return this.dataFetchersDelegatePublisher;
	}

	public DataFetchersDelegatePublisherPage getDataFetchersDelegatePublisherPage() {
		return this.dataFetchersDelegatePublisherPage;
	}

	public DataFetchersDelegateQuotation getDataFetchersDelegateQuotation() {
		return this.dataFetchersDelegateQuotation;
	}

	public DataFetchersDelegateQuotationPage getDataFetchersDelegateQuotationPage() {
		return this.dataFetchersDelegateQuotationPage;
	}

	public DataFetchersDelegateTopic getDataFetchersDelegateTopic() {
		return this.dataFetchersDelegateTopic;
	}

	public DataFetchersDelegateTopicPage getDataFetchersDelegateTopicPage() {
		return this.dataFetchersDelegateTopicPage;
	}

	public DataFetchersDelegateUser getDataFetchersDelegateUser() {
		return this.dataFetchersDelegateUser;
	}

	public DataFetchersDelegateUserPage getDataFetchersDelegateUserPage() {
		return this.dataFetchersDelegateUserPage;
	}

	public DataFetchersDelegateAuthPayload getDataFetchersDelegateAuthPayload() {
		return this.dataFetchersDelegateAuthPayload;
	}

	public DataFetchersDelegateQuery getDataFetchersDelegateQuery() {
		return this.dataFetchersDelegateQuery;
	}

	public DataFetchersDelegateMutation getDataFetchersDelegateMutation() {
		return this.dataFetchersDelegateMutation;
	}

	public DataFetchersDelegateIBaseEntity<IBaseEntity> getDataFetchersDelegateIBaseEntity() {
		return this.dataFetchersDelegateIBaseEntity;
	}

	public DataFetchersDelegateITrackedEntity<AbstractTrackedEntity> getDataFetchersDelegateITrackedEntity() {
		return this.dataFetchersDelegateITrackedEntity;
	}

	public DataFetchersDelegateILinkableEntity<AbstractLinkableEntity> getDataFetchersDelegateILinkableEntity() {
		return this.dataFetchersDelegateILinkableEntity;
	}

	public DataFetchersDelegateIPage getDataFetchersDelegateIPage() {
		return this.dataFetchersDelegateIPage;
	}

}
