/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("__InputValue")
@JsonInclude(Include.NON_NULL)
public class __InputValue extends AbstractGraphQLEntity {

	public __InputValue() {
	}

	@JsonProperty("name")
	@GraphQLScalar(fieldName = "name", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String name;

	@JsonProperty("description")
	@GraphQLScalar(fieldName = "description", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String description;

	@JsonProperty("type")
	@GraphQLNonScalar(fieldName = "type", graphQLTypeSimpleName = "__Type", javaClass = __Type.class, listDepth = 0)
	__Type type;

	@JsonProperty("defaultValue")
	@GraphQLScalar(fieldName = "defaultValue", graphQLTypeSimpleName = "String", javaClass = String.class,
		listDepth = 0)
	String defaultValue;

	@JsonProperty("isDeprecated")
	@GraphQLScalar(fieldName = "isDeprecated", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
		listDepth = 0)
	Boolean isDeprecated;

	@JsonProperty("deprecationReason")
	@GraphQLScalar(fieldName = "deprecationReason", graphQLTypeSimpleName = "String", javaClass = String.class,
		listDepth = 0)
	String deprecationReason;

	@JsonProperty("name")
	public void setName(String name) {
		this.name = name;
	}

	@JsonProperty("name")
	public String getName() {
		return this.name;
	}

	@JsonProperty("description")
	public void setDescription(String description) {
		this.description = description;
	}

	@JsonProperty("description")
	public String getDescription() {
		return this.description;
	}

	@JsonProperty("type")
	public void setType(__Type type) {
		this.type = type;
	}

	@JsonProperty("type")
	public __Type getType() {
		return this.type;
	}

	@JsonProperty("defaultValue")
	public void setDefaultValue(String defaultValue) {
		this.defaultValue = defaultValue;
	}

	@JsonProperty("defaultValue")
	public String getDefaultValue() {
		return this.defaultValue;
	}

	@JsonProperty("isDeprecated")
	public void setIsDeprecated(Boolean isDeprecated) {
		this.isDeprecated = isDeprecated;
	}

	@JsonProperty("isDeprecated")
	public Boolean getIsDeprecated() {
		return this.isDeprecated;
	}

	@JsonProperty("deprecationReason")
	public void setDeprecationReason(String deprecationReason) {
		this.deprecationReason = deprecationReason;
	}

	@JsonProperty("deprecationReason")
	public String getDeprecationReason() {
		return this.deprecationReason;
	}

	public String toString() {
		return "__InputValue {" //
			+ "name: " + this.name //
			+ ", " //
			+ "description: " + this.description //
			+ ", " //
			+ "type: " + this.type //
			+ ", " //
			+ "defaultValue: " + this.defaultValue //
			+ ", " //
			+ "isDeprecated: " + this.isDeprecated //
			+ ", " //
			+ "deprecationReason: " + this.deprecationReason //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}";
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractGraphQLEntity.Builder<Builder, __InputValue> {

		private String name;
		private String description;
		private __Type type;
		private String defaultValue;
		private Boolean isDeprecated;
		private String deprecationReason;

		public Builder withName(String nameParam) {
			this.name = nameParam;
			return this;
		}

		public Builder withDescription(String descriptionParam) {
			this.description = descriptionParam;
			return this;
		}

		public Builder withType(__Type typeParam) {
			this.type = typeParam;
			return this;
		}

		public Builder withDefaultValue(String defaultValueParam) {
			this.defaultValue = defaultValueParam;
			return this;
		}

		public Builder withIsDeprecated(Boolean isDeprecatedParam) {
			this.isDeprecated = isDeprecatedParam;
			return this;
		}

		public Builder withDeprecationReason(String deprecationReasonParam) {
			this.deprecationReason = deprecationReasonParam;
			return this;
		}

		public __InputValue build() {
			__InputValue _object = build(new __InputValue());
			_object.setName(this.name);
			_object.setDescription(this.description);
			_object.setType(this.type);
			_object.setDefaultValue(this.defaultValue);
			_object.setIsDeprecated(this.isDeprecated);
			_object.setDeprecationReason(this.deprecationReason);
			return _object;
		}

		@Override
		String getTypeName() {
			return "__InputValue";
		}

	}

}
