/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * Holds aggregated audit information for an entity.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("EntityAudit")
@JsonInclude(Include.NON_NULL)
public class EntityAudit extends AbstractGraphQLEntity {

	/**
	 * The entity to which the audit relates.
	 */
	@JsonProperty("entity")
	@GraphQLNonScalar(fieldName = "entity", graphQLTypeSimpleName = "ITrackedEntity", javaClass = ITrackedEntity.class,
		listDepth = 0)
	ITrackedEntity entity;

	/**
	 * Field audit information.
	 */
	@JsonProperty("fieldAudit")
	@GraphQLNonScalar(fieldName = "fieldAudit", graphQLTypeSimpleName = "FieldAudit", javaClass = FieldAudit.class,
		listDepth = 0)
	FieldAudit fieldAudit;

	/**
	 * Link audit information. Only populated if entity is an ILinkableEntity
	 */
	@JsonProperty("linkAudit")
	@GraphQLNonScalar(fieldName = "linkAudit", graphQLTypeSimpleName = "LinkAudit", javaClass = LinkAudit.class,
		listDepth = 0)
	LinkAudit linkAudit;

	/**
	 * Whether the entity meets the standard required for publication.
	 */
	@JsonProperty("pass")
	@GraphQLScalar(fieldName = "pass", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class, listDepth = 0)
	Boolean pass;

	/**
	 * The entity to which the audit relates.
	 */
	@JsonProperty("entity")
	public void setEntity(ITrackedEntity entity) {
		this.entity = entity;
	}

	/**
	 * The entity to which the audit relates.
	 */
	@JsonProperty("entity")
	public ITrackedEntity getEntity() {
		return this.entity;
	}

	/**
	 * Field audit information.
	 */
	@JsonProperty("fieldAudit")
	public void setFieldAudit(FieldAudit fieldAudit) {
		this.fieldAudit = fieldAudit;
	}

	/**
	 * Field audit information.
	 */
	@JsonProperty("fieldAudit")
	public FieldAudit getFieldAudit() {
		return this.fieldAudit;
	}

	/**
	 * Link audit information. Only populated if entity is an ILinkableEntity
	 */
	@JsonProperty("linkAudit")
	public void setLinkAudit(LinkAudit linkAudit) {
		this.linkAudit = linkAudit;
	}

	/**
	 * Link audit information. Only populated if entity is an ILinkableEntity
	 */
	@JsonProperty("linkAudit")
	public LinkAudit getLinkAudit() {
		return this.linkAudit;
	}

	/**
	 * Whether the entity meets the standard required for publication.
	 */
	@JsonProperty("pass")
	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	/**
	 * Whether the entity meets the standard required for publication.
	 */
	@JsonProperty("pass")
	public Boolean getPass() {
		return this.pass;
	}

	public String toString() {
		return "EntityAudit {" //
			+ "entity: " + this.entity //
			+ ", " //
			+ "fieldAudit: " + this.fieldAudit //
			+ ", " //
			+ "linkAudit: " + this.linkAudit //
			+ ", " //
			+ "pass: " + this.pass //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}"; //
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((entity == null) ? 0 : entity.hashCode());
		result = prime * result + ((fieldAudit == null) ? 0 : fieldAudit.hashCode());
		result = prime * result + ((linkAudit == null) ? 0 : linkAudit.hashCode());
		result = prime * result + ((pass == null) ? 0 : pass.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		EntityAudit other = (EntityAudit)obj;
		if (entity == null) {
			if (other.entity != null)
				return false;
		} else if (!entity.equals(other.entity))
			return false;
		if (fieldAudit == null) {
			if (other.fieldAudit != null)
				return false;
		} else if (!fieldAudit.equals(other.fieldAudit))
			return false;
		if (linkAudit == null) {
			if (other.linkAudit != null)
				return false;
		} else if (!linkAudit.equals(other.linkAudit))
			return false;
		if (pass == null) {
			if (other.pass != null)
				return false;
		} else if (!pass.equals(other.pass))
			return false;
		return true;
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractGraphQLEntity.Builder<Builder, EntityAudit> {

		private ITrackedEntity entity;
		private FieldAudit fieldAudit;
		private LinkAudit linkAudit;
		private Boolean pass;

		/**
		 * The entity to which the audit relates.
		 */
		public Builder withEntity(ITrackedEntity entityParam) {
			this.entity = entityParam;
			return this;
		}

		/**
		 * Field audit information.
		 */
		public Builder withFieldAudit(FieldAudit fieldAuditParam) {
			this.fieldAudit = fieldAuditParam;
			return this;
		}

		/**
		 * Link audit information. Only populated if entity is an ILinkableEntity
		 */
		public Builder withLinkAudit(LinkAudit linkAuditParam) {
			this.linkAudit = linkAuditParam;
			return this;
		}

		/**
		 * Whether the entity meets the standard required for publication.
		 */
		public Builder withPass(Boolean passParam) {
			this.pass = passParam;
			return this;
		}

		public EntityAudit build() {
			EntityAudit _object = super.build(new EntityAudit());
			_object.setEntity(this.entity);
			_object.setFieldAudit(this.fieldAudit);
			_object.setLinkAudit(this.linkAudit);
			_object.setPass(this.pass);
			// _object.set__typename("EntityAudit"); //
			return _object;
		}

		@Override
		String getTypeName() {
			return "EntityAudit";
		}

	}

}
