/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * Parameters to filter an entity link query.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("EntityLinkQueryFilter")
@JsonInclude(Include.NON_NULL)
public class EntityLinkQueryFilter extends /*TrackedEntityQueryFilter*/AbstractGraphQLObject {

	public EntityLinkQueryFilter() {
	}

	/**
	 * The ID of the 'linked-from' (master) entity.
	 */
	@JsonProperty("fromEntityId")
	@GraphQLScalar(fieldName = "fromEntityId", graphQLTypeSimpleName = "ID", javaClass = String.class, listDepth = 0)
	Long fromEntityId;

	/**
	 * The kind of the 'linked-from' entity.
	 */
	@JsonProperty("fromEntityKind")
	@GraphQLScalar(fieldName = "fromEntityKind", graphQLTypeSimpleName = "EntityKind", javaClass = EntityKind.class,
		listDepth = 0)
	EntityKind fromEntityKind;

	/**
	 * The ID of the 'linked-to' entity.
	 */
	@JsonProperty("toEntityId")
	@GraphQLScalar(fieldName = "toEntityId", graphQLTypeSimpleName = "ID", javaClass = String.class, listDepth = 0)
	Long toEntityId;

	/**
	 * The kind of the 'linked-to' entity.
	 */
	@JsonProperty("toEntityKind")
	@GraphQLScalar(fieldName = "toEntityKind", graphQLTypeSimpleName = "EntityKind", javaClass = EntityKind.class,
		listDepth = 0)
	EntityKind toEntityKind;

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	* Return only records with these status codes (default: ALL).
	*/
	@JsonProperty("status")
	@GraphQLScalar(fieldName = "status", graphQLTypeSimpleName = "StatusKind", javaClass = StatusKind.class,
	listDepth = 1)
	List<StatusKind> status;

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	* Free text search string (applied to the 'linked-to' entity).
	*/
	@JsonProperty("text")
	@GraphQLScalar(fieldName = "text", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String text;

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	* Whether to search ```text``` in advanced (boolean) mode.
	*/
	@JsonProperty("advancedSearch")
	@GraphQLScalar(fieldName = "advancedSearch", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
	listDepth = 0)
	Boolean advancedSearch;

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * The ID of the 'linked-from' (master) entity.
	 */
	@JsonProperty("fromEntityId")
	public void setFromEntityId(Long fromEntityId) {
		this.fromEntityId = fromEntityId;
	}

	/**
	 * The ID of the 'linked-from' (master) entity.
	 */
	@JsonProperty("fromEntityId")
	public Long getFromEntityId() {
		return this.fromEntityId;
	}

	/**
	 * The kind of the 'linked-from' entity.
	 */
	@JsonProperty("fromEntityKind")
	public void setFromEntityKind(EntityKind fromEntityKind) {
		this.fromEntityKind = fromEntityKind;
	}

	/**
	 * The kind of the 'linked-from' entity.
	 */
	@JsonProperty("fromEntityKind")
	public EntityKind getFromEntityKind() {
		return this.fromEntityKind;
	}

	/**
	 * The ID of the 'linked-to' entity.
	 */
	@JsonProperty("toEntityId")
	public void setToEntityId(Long toEntityId) {
		this.toEntityId = toEntityId;
	}

	/**
	 * The ID of the 'linked-to' entity.
	 */
	@JsonProperty("toEntityId")
	public Long getToEntityId() {
		return this.toEntityId;
	}

	/**
	 * The kind of the 'linked-to' entity.
	 */
	@JsonProperty("toEntityKind")
	public void setToEntityKind(EntityKind toEntityKind) {
		this.toEntityKind = toEntityKind;
	}

	/**
	 * The kind of the 'linked-to' entity.
	 */
	@JsonProperty("toEntityKind")
	public EntityKind getToEntityKind() {
		return this.toEntityKind;
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * Return only records with these status codes (default: ALL).
	 */
	@JsonProperty("status")
	public void setStatus(List<StatusKind> status) {
		this.status = status;
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * Return only records with these status codes (default: ALL).
	 */
	@JsonProperty("status")
	public List<StatusKind> getStatus() {
		return this.status;
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * Free text search string (applied to the 'linked-to' entity).
	 */
	@JsonProperty("text")
	public void setText(String text) {
		this.text = text;
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * Free text search string (applied to the 'linked-to' entity).
	 */
	@JsonProperty("text")
	public String getText() {
		return this.text;
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * Whether to search ```text``` in advanced (boolean) mode.
	 */
	@JsonProperty("advancedSearch")
	public void setAdvancedSearch(Boolean advancedSearch) {
		this.advancedSearch = advancedSearch;
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * Whether to search ```text``` in advanced (boolean) mode.
	 */
	@JsonProperty("advancedSearch")
	public Boolean getAdvancedSearch() {
		return this.advancedSearch;
	}

	public String toString() {
		return "EntityLinkQueryFilter {" //
			+ "fromEntityId: " + this.fromEntityId //
			+ ", " //
			+ "fromEntityKind: " + this.fromEntityKind //
			+ ", " //
			+ "toEntityId: " + this.toEntityId //
			+ ", " //
			+ "toEntityKind: " + this.toEntityKind //
			+ ", " //
			+ "status: " + this.status //
			+ ", " //
			+ "text: " + this.text //
			+ ", " //
			+ "advancedSearch: " + this.advancedSearch //
			+ "}";
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {

		private Long fromEntityId;
		private EntityKind fromEntityKind;
		private Long toEntityId;
		private EntityKind toEntityKind;
		private List<StatusKind> status;
		private String text;
		private Boolean advancedSearch;

		/**
		 * The ID of the 'linked-from' (master) entity.
		 */
		public Builder withFromEntityId(Long fromEntityIdParam) {
			this.fromEntityId = fromEntityIdParam;
			return this;
		}

		/**
		 * The kind of the 'linked-from' entity.
		 */
		public Builder withFromEntityKind(EntityKind fromEntityKindParam) {
			this.fromEntityKind = fromEntityKindParam;
			return this;
		}

		/**
		 * The ID of the 'linked-to' entity.
		 */
		public Builder withToEntityId(Long toEntityIdParam) {
			this.toEntityId = toEntityIdParam;
			return this;
		}

		/**
		 * The kind of the 'linked-to' entity.
		 */
		public Builder withToEntityKind(EntityKind toEntityKindParam) {
			this.toEntityKind = toEntityKindParam;
			return this;
		}

		/**
		 * Return only records with these status codes (default: ALL).
		 */
		public Builder withStatus(List<StatusKind> statusParam) {
			this.status = statusParam;
			return this;
		}

		/**
		 * Free text search string (applied to the 'linked-to' entity).
		 */
		public Builder withText(String textParam) {
			this.text = textParam;
			return this;
		}

		/**
		 * Whether to search ```text``` in advanced (boolean) mode.
		 */
		public Builder withAdvancedSearch(Boolean advancedSearchParam) {
			this.advancedSearch = advancedSearchParam;
			return this;
		}

		public EntityLinkQueryFilter build() {
			EntityLinkQueryFilter _object = new EntityLinkQueryFilter();
			_object.setFromEntityId(this.fromEntityId);
			_object.setFromEntityKind(this.fromEntityKind);
			_object.setToEntityId(this.toEntityId);
			_object.setToEntityKind(this.toEntityKind);
			_object.setStatus(this.status);
			_object.setText(this.text);
			_object.setAdvancedSearch(this.advancedSearch);
			return _object;
		}

	}

	// Commented out, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	// @SuppressWarnings("unchecked")
	// abstract static class AbstractBuilder<B extends AbstractBuilder<B, T>, T extends EntityLinkQueryFilter>
	// 	extends TrackedEntityQueryFilter.AbstractBuilder<B, T> {

	// 	private EntityKind fromEntityKind;
	// 	private Long fromEntityId;
	// 	private EntityKind toEntityKind;
	// 	private Long toEntityId;

	// 	/**
	// 	 * The 'linked-from' entity kind, if a master list is designated.
	// 	 */
	// 	public final B withFromEntityKind(EntityKind fromEntityKindParam) {
	// 		this.fromEntityKind = fromEntityKindParam;
	// 		return (B)this;
	// 	}

	// 	/**
	// 	 * The 'linked-from' entity identifier, if a master list is designated.
	// 	 */
	// 	public final B withFromEntityId(Long fromEntityIdParam) {
	// 		this.fromEntityId = fromEntityIdParam;
	// 		return (B)this;
	// 	}

	// 	/**
	// 	 * The 'linked-from' entity kind, if a master list is designated.
	// 	 */
	// 	public final B withToEntityKind(EntityKind toEntityKindParam) {
	// 		this.toEntityKind = toEntityKindParam;
	// 		return (B)this;
	// 	}

	// 	/**
	// 	 * The 'linked-from' entity identifier, if a master list is designated.
	// 	 */
	// 	public final B withToEntityId(Long toEntityIdParam) {
	// 		this.toEntityId = toEntityIdParam;
	// 		return (B)this;
	// 	}

	// 	T build(T _object) {
	// 		super.build(_object);
	// 		_object.setFromEntityKind(this.fromEntityKind);
	// 		_object.setFromEntityId(this.fromEntityId);
	// 		_object.setToEntityKind(this.toEntityKind);
	// 		_object.setToEntityId(this.toEntityId);
	// 		return _object;
	// 	}

	// }

	// /**
	//  * The Builder that helps building instance of this POJO. You can get an instance of this class by calling the
	//  * {@link #builderForEntityLinkQueryFilter()}
	//  */
	// public static class Builder extends AbstractBuilder<Builder, EntityLinkQueryFilter> {

	// 	@Override
	// 	public EntityLinkQueryFilter build() {
	// 		return build(new EntityLinkQueryFilter());
	// 	}

	// }

}
