/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

import io.github.demonfiddler.ee.client.util.CustomJacksonDeserializers;

/**
 * Holds field group audit information. At least one field in the group must be set.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("FieldGroupAuditEntry")
@JsonInclude(Include.NON_NULL)
public class FieldGroupAuditEntry extends AbstractGraphQLEntity {

	/**
	 * Field group audit entries.
	 */
	@JsonProperty("fields")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListFieldAuditEntry.class)
	@GraphQLNonScalar(fieldName = "fields", graphQLTypeSimpleName = "FieldAuditEntry",
		javaClass = FieldAuditEntry.class, listDepth = 1)
	List<FieldAuditEntry> fields;

	/**
	 * A message about the field group.
	 */
	@JsonProperty("message")
	@GraphQLScalar(fieldName = "message", graphQLTypeSimpleName = "String", javaClass = String.class,
		listDepth = 0)
	String message;

	/**
	 * The message severity level.
	 */
	@JsonProperty("severity")
	@GraphQLScalar(fieldName = "severity", graphQLTypeSimpleName = "SeverityKind",
		javaClass = SeverityKind.class, listDepth = 0)
	SeverityKind severity;

	/**
	 * Whether the field group meets the standard required for publication.
	 */
	@JsonProperty("pass")
	@GraphQLScalar(fieldName = "pass", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
		listDepth = 0)
	Boolean pass;

	/**
	 * Field group audit entries.
	 */
	@JsonProperty("fields")
	public void setFields(List<FieldAuditEntry> fields) {
		this.fields = fields;
	}

	/**
	 * Field group audit entries.
	 */
	@JsonProperty("fields")
	public List<FieldAuditEntry> getFields() {
		return this.fields;
	}

	/**
	 * A message about the field group.
	 */
	@JsonProperty("message")
	public void setMessage(String message) {
		this.message = message;
	}

	/**
	 * A message about the field group.
	 */
	@JsonProperty("message")
	public String getMessage() {
		return this.message;
	}

	/**
	 * The message severity level.
	 */
	@JsonProperty("severity")
	public void setSeverity(SeverityKind severity) {
		this.severity = severity;
	}

	/**
	 * The message severity level.
	 */
	@JsonProperty("severity")
	public SeverityKind getSeverity() {
		return this.severity;
	}

	/**
	 * Whether the field group meets the standard required for publication.
	 */
	@JsonProperty("pass")
	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	/**
	 * Whether the field group meets the standard required for publication.
	 */
	@JsonProperty("pass")
	public Boolean getPass() {
		return this.pass;
	}

	public String toString() {
		return "FieldGroupAuditEntry {" //
			+ "fields: " + this.fields //
			+ ", " //
			+ "message: " + this.message //
			+ ", " //
			+ "severity: " + this.severity //
			+ ", " //
			+ "pass: " + this.pass //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}"; //
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((fields == null) ? 0 : fields.hashCode());
		result = prime * result + ((message == null) ? 0 : message.hashCode());
		result = prime * result + ((severity == null) ? 0 : severity.hashCode());
		result = prime * result + ((pass == null) ? 0 : pass.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		FieldGroupAuditEntry other = (FieldGroupAuditEntry)obj;
		if (fields == null) {
			if (other.fields != null)
				return false;
		} else if (!fields.equals(other.fields))
			return false;
		if (message == null) {
			if (other.message != null)
				return false;
		} else if (!message.equals(other.message))
			return false;
		if (severity != other.severity)
			return false;
		if (pass == null) {
			if (other.pass != null)
				return false;
		} else if (!pass.equals(other.pass))
			return false;
		return true;
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractGraphQLEntity.Builder<Builder, FieldGroupAuditEntry> {

		private List<FieldAuditEntry> fields;
		private String message;
		private SeverityKind severity;
		private Boolean pass;

		/**
		 * Field group audit entries.
		 */
		public Builder withFields(List<FieldAuditEntry> fieldsParam) {
			this.fields = fieldsParam;
			return this;
		}

		/**
		 * A message about the field group.
		 */
		public Builder withMessage(String messageParam) {
			this.message = messageParam;
			return this;
		}

		/**
		 * The message severity level.
		 */
		public Builder withSeverity(SeverityKind severityParam) {
			this.severity = severityParam;
			return this;
		}

		/**
		 * Whether the field group meets the standard required for publication.
		 */
		public Builder withPass(Boolean passParam) {
			this.pass = passParam;
			return this;
		}

		public FieldGroupAuditEntry build() {
			FieldGroupAuditEntry _object = super.build(new FieldGroupAuditEntry());
			_object.setFields(this.fields);
			_object.setMessage(this.message);
			_object.setSeverity(this.severity);
			_object.setPass(this.pass);
			return _object;
		}

		@Override
		String getTypeName() {
			return "FieldGroupAuditEntry";
		}

	}

}
