/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

import io.github.demonfiddler.ee.client.util.CustomJacksonDeserializers;

/**
 * Holds aggregated link audit information.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("LinkAudit")
@JsonInclude(Include.NON_NULL)
public class LinkAudit extends AbstractGraphQLEntity {

	/**
	 * The individual link audit entries.
	 */
	@JsonProperty("links")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListLinkAuditEntry.class)
	@GraphQLNonScalar(fieldName = "links", graphQLTypeSimpleName = "LinkAuditEntry", javaClass = LinkAuditEntry.class,
		listDepth = 1)
	List<LinkAuditEntry> links;

	/**
	 * Link group audit entries.
	 */
	@JsonProperty("groups")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListLinkGroupAuditEntry.class)
	@GraphQLNonScalar(fieldName = "groups", graphQLTypeSimpleName = "LinkGroupAuditEntry",
		javaClass = LinkGroupAuditEntry.class, listDepth = 1)
	List<LinkGroupAuditEntry> groups;

	/**
	 * Whether the links meet the standard required for publication.
	 */
	@JsonProperty("pass")
	@GraphQLScalar(fieldName = "pass", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class, listDepth = 0)
	Boolean pass;

	/**
	 * The individual link audit entries.
	 */
	@JsonProperty("links")
	public void setLinks(List<LinkAuditEntry> links) {
		this.links = links;
	}

	/**
	 * The individual link audit entries.
	 */
	@JsonProperty("links")
	public List<LinkAuditEntry> getLinks() {
		return this.links;
	}

	/**
	 * Link group audit entries.
	 */
	@JsonProperty("groups")
	public void setGroups(List<LinkGroupAuditEntry> groups) {
		this.groups = groups;
	}

	/**
	 * Link group audit entries.
	 */
	@JsonProperty("groups")
	public List<LinkGroupAuditEntry> getGroups() {
		return this.groups;
	}

	/**
	 * Whether the links meet the standard required for publication.
	 */
	@JsonProperty("pass")
	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	/**
	 * Whether the links meet the standard required for publication.
	 */
	@JsonProperty("pass")
	public Boolean getPass() {
		return this.pass;
	}

	public String toString() {
		return "LinkAudit {" //
			+ "links: " + this.links //
			+ ", " //
			+ "groups: " + this.groups //
			+ ", " //
			+ "pass: " + this.pass //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}"; //
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((links == null) ? 0 : links.hashCode());
		result = prime * result + ((groups == null) ? 0 : groups.hashCode());
		result = prime * result + ((pass == null) ? 0 : pass.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		LinkAudit other = (LinkAudit)obj;
		if (links == null) {
			if (other.links != null)
				return false;
		} else if (!links.equals(other.links))
			return false;
		if (groups == null) {
			if (other.groups != null)
				return false;
		} else if (!groups.equals(other.groups))
			return false;
		if (pass == null) {
			if (other.pass != null)
				return false;
		} else if (!pass.equals(other.pass))
			return false;
		return true;
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractGraphQLEntity.Builder<Builder, LinkAudit> {

		private List<LinkAuditEntry> links;
		private List<LinkGroupAuditEntry> groups;
		private Boolean pass;

		/**
		 * The individual link audit entries.
		 */
		public Builder withLinks(List<LinkAuditEntry> linksParam) {
			this.links = linksParam;
			return this;
		}

		/**
		 * Link group audit entries.
		 */
		public Builder withGroups(List<LinkGroupAuditEntry> groupsParam) {
			this.groups = groupsParam;
			return this;
		}

		/**
		 * Whether the links meet the standard required for publication.
		 */
		public Builder withPass(Boolean passParam) {
			this.pass = passParam;
			return this;
		}

		public LinkAudit build() {
			LinkAudit _object = new LinkAudit();
			_object.setLinks(this.links);
			_object.setGroups(this.groups);
			_object.setPass(this.pass);
			return _object;
		}

		@Override
		String getTypeName() {
			return "LinkAudit";
		}

	}

}
