/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

/**
 * An individual link audit entry.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("LinkAuditEntry")
@JsonInclude(Include.NON_NULL)
public class LinkAuditEntry extends AbstractGraphQLEntity {

	/**
	 * The linked entity kind.
	 */
	@JsonProperty("linkedEntityKind")
	@GraphQLInputParameters(names = { "format" }, types = { "FormatKind" }, mandatories = { false }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLScalar(fieldName = "linkedEntityKind", graphQLTypeSimpleName = "String", javaClass = String.class,
		listDepth = 0)
	String linkedEntityKind;

	/**
	 * The required minimum number of links.
	 */
	@JsonProperty("min")
	@GraphQLScalar(fieldName = "min", graphQLTypeSimpleName = "Int", javaClass = Integer.class, listDepth = 0)
	Integer min;

	/**
	 * The actual number of links.
	 */
	@JsonProperty("actual")
	@GraphQLScalar(fieldName = "actual", graphQLTypeSimpleName = "Int", javaClass = Integer.class,
		listDepth = 0)
	Integer actual;

	/**
	 * Whether the link meets the standard required for publication.
	 */
	@JsonProperty("pass")
	@GraphQLScalar(fieldName = "pass", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
		listDepth = 0)
	Boolean pass;

	/**
	 * The linked entity kind.
	 */
	@JsonProperty("linkedEntityKind")
	public void setLinkedEntityKind(String linkedEntityKind) {
		this.linkedEntityKind = linkedEntityKind;
	}

	/**
	 * The linked entity kind.
	 */
	@JsonProperty("linkedEntityKind")
	public String getLinkedEntityKind() {
		return this.linkedEntityKind;
	}

	/**
	 * The required minimum number of links.
	 */
	@JsonProperty("min")
	public void setMin(Integer min) {
		this.min = min;
	}

	/**
	 * The required minimum number of links.
	 */
	@JsonProperty("min")
	public Integer getMin() {
		return this.min;
	}

	/**
	 * The actual number of links.
	 */
	@JsonProperty("actual")
	public void setActual(Integer actual) {
		this.actual = actual;
	}

	/**
	 * The actual number of links.
	 */
	@JsonProperty("actual")
	public Integer getActual() {
		return this.actual;
	}

	/**
	 * Whether the link meets the standard required for publication.
	 */
	@JsonProperty("pass")
	public void setPass(Boolean pass) {
		this.pass = pass;
	}

	/**
	 * Whether the link meets the standard required for publication.
	 */
	@JsonProperty("pass")
	public Boolean getPass() {
		return this.pass;
	}

	public String toString() {
		return "LinkAuditEntry {" //
			+ "linkedEntityKind: " + this.linkedEntityKind //
			+ ", " //
			+ "min: " + this.min //
			+ ", " //
			+ "actual: " + this.actual //
			+ ", " //
			+ "pass: " + this.pass //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}"; //
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((linkedEntityKind == null) ? 0 : linkedEntityKind.hashCode());
		result = prime * result + ((min == null) ? 0 : min.hashCode());
		result = prime * result + ((actual == null) ? 0 : actual.hashCode());
		result = prime * result + ((pass == null) ? 0 : pass.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		LinkAuditEntry other = (LinkAuditEntry)obj;
		if (linkedEntityKind != other.linkedEntityKind)
			return false;
		if (min == null) {
			if (other.min != null)
				return false;
		} else if (!min.equals(other.min))
			return false;
		if (actual == null) {
			if (other.actual != null)
				return false;
		} else if (!actual.equals(other.actual))
			return false;
		if (pass == null) {
			if (other.pass != null)
				return false;
		} else if (!pass.equals(other.pass))
			return false;
		return true;
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractGraphQLEntity.Builder<Builder, LinkAuditEntry> {

		private String linkedEntityKind;
		private Integer min;
		private Integer actual;
		private Boolean pass;

		/**
		 * The linked entity kind.
		 */
		public Builder withLinkedEntityKind(String linkedEntityKindParam) {
			this.linkedEntityKind = linkedEntityKindParam;
			return this;
		}

		/**
		 * The required minimum number of links.
		 */
		public Builder withMin(Integer minParam) {
			this.min = minParam;
			return this;
		}

		/**
		 * The actual number of links.
		 */
		public Builder withActual(Integer actualParam) {
			this.actual = actualParam;
			return this;
		}

		/**
		 * Whether the link meets the standard required for publication.
		 */
		public Builder withPass(Boolean passParam) {
			this.pass = passParam;
			return this;
		}

		public LinkAuditEntry build() {
			LinkAuditEntry _object = new LinkAuditEntry();
			_object.setLinkedEntityKind(this.linkedEntityKind);
			_object.setMin(this.min);
			_object.setActual(this.actual);
			_object.setPass(this.pass);
			return _object;
		}

		@Override
		String getTypeName() {
			return "LinkAuditEntry";
		}

	}

}
