/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.time.OffsetDateTime;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

import io.github.demonfiddler.ee.client.util.CustomJacksonDeserializers;

/**
 * A log entry to show who changed what and when
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("Log")
@JsonInclude(Include.NON_NULL)
public class Log extends AbstractBaseEntity {

	public Log() {
	}

	/**
	 * The date-time stamp.
	 */
	@JsonProperty("timestamp")
	@JsonDeserialize(using = CustomJacksonDeserializers.DateTime.class)
	@GraphQLScalar(fieldName = "timestamp", graphQLTypeSimpleName = "DateTime", javaClass = OffsetDateTime.class,
		listDepth = 0)
	OffsetDateTime timestamp;

	/**
	 * The user who made the change.
	 */
	@JsonProperty("user")
	@GraphQLNonScalar(fieldName = "user", graphQLTypeSimpleName = "User", javaClass = User.class, listDepth = 0)
	User user;

	/**
	 * The kind of transaction.
	 */
	@JsonProperty("transactionKind")
	@GraphQLInputParameters(names = { "format" }, types = { "FormatKind" }, mandatories = { false }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLScalar(fieldName = "transactionKind", graphQLTypeSimpleName = "String", javaClass = String.class,
		listDepth = 0)
	String transactionKind;

	/**
	 * The kind of entity affected.
	 */
	@JsonProperty("entityKind")
	@GraphQLInputParameters(names = { "format" }, types = { "FormatKind" }, mandatories = { false }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLScalar(fieldName = "entityKind", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String entityKind;

	/**
	 * The ID of the entity affected.
	 */
	@JsonProperty("entityId")
	@JsonDeserialize(using = CustomJacksonDeserializers.Long.class)
	@GraphQLScalar(fieldName = "entityId", graphQLTypeSimpleName = "Long", javaClass = Long.class, listDepth = 0)
	Long entityId;

	/**
	 * The kind of entity linked/unlinked (where applicable).
	 */
	@JsonProperty("linkedEntityKind")
	@GraphQLInputParameters(names = { "format" }, types = { "FormatKind" }, mandatories = { false }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLScalar(fieldName = "linkedEntityKind", graphQLTypeSimpleName = "String", javaClass = String.class,
		listDepth = 0)
	String linkedEntityKind;

	/**
	 * The ID of the entity linked/unlinked (where applicable).
	 */
	@JsonProperty("linkedEntityId")
	@JsonDeserialize(using = CustomJacksonDeserializers.Long.class)
	@GraphQLScalar(fieldName = "linkedEntityId", graphQLTypeSimpleName = "Long", javaClass = Long.class, listDepth = 0)
	Long linkedEntityId;

	/**
	 * The date-time stamp.
	 */
	@JsonProperty("timestamp")
	public void setTimestamp(OffsetDateTime timestamp) {
		this.timestamp = timestamp;
	}

	/**
	 * The date-time stamp.
	 */
	@JsonProperty("timestamp")
	public OffsetDateTime getTimestamp() {
		return this.timestamp;
	}

	/**
	 * The user who made the change.
	 */
	@JsonProperty("user")
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * The user who made the change.
	 */
	@JsonProperty("user")
	public User getUser() {
		return this.user;
	}

	/**
	 * The kind of transaction.
	 */
	@JsonProperty("transactionKind")
	public void setTransactionKind(String transactionKind) {
		this.transactionKind = transactionKind;
	}

	/**
	 * The kind of transaction.
	 */
	@JsonProperty("transactionKind")
	public String getTransactionKind() {
		return this.transactionKind;
	}

	/**
	 * The kind of entity affected.
	 */
	@JsonProperty("entityKind")
	public void setEntityKind(String entityKind) {
		this.entityKind = entityKind;
	}

	/**
	 * The kind of entity affected.
	 */
	@JsonProperty("entityKind")
	public String getEntityKind() {
		return this.entityKind;
	}

	/**
	 * The ID of the entity affected.
	 */
	@JsonProperty("entityId")
	public void setEntityId(Long entityId) {
		this.entityId = entityId;
	}

	/**
	 * The ID of the entity affected.
	 */
	@JsonProperty("entityId")
	public Long getEntityId() {
		return this.entityId;
	}

	/**
	 * The kind of entity linked/unlinked (where applicable).
	 */
	@JsonProperty("linkedEntityKind")
	public void setLinkedEntityKind(String linkedEntityKind) {
		this.linkedEntityKind = linkedEntityKind;
	}

	/**
	 * The kind of entity linked/unlinked (where applicable).
	 */
	@JsonProperty("linkedEntityKind")
	public String getLinkedEntityKind() {
		return this.linkedEntityKind;
	}

	/**
	 * The ID of the entity linked/unlinked (where applicable).
	 */
	@JsonProperty("linkedEntityId")
	public void setLinkedEntityId(Long linkedEntityId) {
		this.linkedEntityId = linkedEntityId;
	}

	/**
	 * The ID of the entity linked/unlinked (where applicable).
	 */
	@JsonProperty("linkedEntityId")
	public Long getLinkedEntityId() {
		return this.linkedEntityId;
	}

	public String toString() {
		return "Log {" //
			+ "id: " + this.id //
			+ ", " //
			+ "timestamp: " + this.timestamp //
			+ ", " //
			+ "user: " + this.user //
			+ ", " //
			+ "transactionKind: " + this.transactionKind //
			+ ", " //
			+ "entityKind: " + this.entityKind //
			+ ", " //
			+ "entityId: " + this.entityId //
			+ ", " //
			+ "linkedEntityKind: " + this.linkedEntityKind //
			+ ", " //
			+ "linkedEntityId: " + this.linkedEntityId //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((timestamp == null) ? 0 : timestamp.hashCode());
		result = prime * result + ((user == null) ? 0 : user.hashCode());
		result = prime * result + ((transactionKind == null) ? 0 : transactionKind.hashCode());
		result = prime * result + ((entityKind == null) ? 0 : entityKind.hashCode());
		result = prime * result + ((entityId == null) ? 0 : entityId.hashCode());
		result = prime * result + ((linkedEntityKind == null) ? 0 : linkedEntityKind.hashCode());
		result = prime * result + ((linkedEntityId == null) ? 0 : linkedEntityId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
        if (!super.equals(obj))
            return false;
		Log other = (Log)obj;
		if (timestamp == null) {
			if (other.timestamp != null)
				return false;
		} else if (!timestamp.equals(other.timestamp))
			return false;
		if (user == null) {
			if (other.user != null)
				return false;
		} else if (!user.equals(other.user))
			return false;
		if (transactionKind == null) {
			if (other.transactionKind != null)
				return false;
		} else if (!transactionKind.equals(other.transactionKind))
			return false;
		if (entityKind == null) {
			if (other.entityKind != null)
				return false;
		} else if (!entityKind.equals(other.entityKind))
			return false;
		if (entityId == null) {
			if (other.entityId != null)
				return false;
		} else if (!entityId.equals(other.entityId))
			return false;
		if (linkedEntityKind == null) {
			if (other.linkedEntityKind != null)
				return false;
		} else if (!linkedEntityKind.equals(other.linkedEntityKind))
			return false;
		if (linkedEntityId == null) {
			if (other.linkedEntityId != null)
				return false;
		} else if (!linkedEntityId.equals(other.linkedEntityId))
			return false;
		return true;
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractBaseEntity.Builder<Builder, Log> {

		private OffsetDateTime timestamp;
		private User user;
		private String transactionKind;
		private String entityKind;
		private Long entityId;
		private String linkedEntityKind;
		private Long linkedEntityId;

		/**
		 * The date-time stamp.
		 */
		public Builder withTimestamp(OffsetDateTime timestampParam) {
			this.timestamp = timestampParam;
			return this;
		}

		/**
		 * The user who made the change.
		 */
		public Builder withUser(io.github.demonfiddler.ee.client.User userParam) {
			this.user = userParam;
			return this;
		}

		/**
		 * The kind of transaction.
		 */
		public Builder withTransactionKind(String transactionKindParam) {
			this.transactionKind = transactionKindParam;
			return this;
		}

		/**
		 * The kind of entity affected.
		 */
		public Builder withEntityKind(String entityKindParam) {
			this.entityKind = entityKindParam;
			return this;
		}

		/**
		 * The ID of the entity affected.
		 */
		public Builder withEntityId(Long entityIdParam) {
			this.entityId = entityIdParam;
			return this;
		}

		/**
		 * The kind of entity linked/unlinked (where applicable).
		 */
		public Builder withLinkedEntityKind(String linkedEntityKindParam) {
			this.linkedEntityKind = linkedEntityKindParam;
			return this;
		}

		/**
		 * The ID of the entity linked/unlinked (where applicable).
		 */
		public Builder withLinkedEntityId(Long linkedEntityIdParam) {
			this.linkedEntityId = linkedEntityIdParam;
			return this;
		}

		@Override
		public Log build() {
			Log _object = build(new Log());
			_object.setTimestamp(this.timestamp);
			_object.setUser(this.user);
			_object.setTransactionKind(this.transactionKind);
			_object.setEntityKind(this.entityKind);
			_object.setEntityId(this.entityId);
			_object.setLinkedEntityKind(this.linkedEntityKind);
			_object.setLinkedEntityId(this.linkedEntityId);
			return _object;
		}

		@Override
		String getTypeName() {
			return "Log";
		}

	}

}
