/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.net.URL;
import java.time.LocalDate;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

import io.github.demonfiddler.ee.client.util.CustomJacksonSerializers;

/**
 * An input for creating or updating a publication.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("PublicationInput")
@JsonInclude(Include.NON_NULL)
public class PublicationInput extends AbstractTrackedEntityInput {

	public PublicationInput() {
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * The publication identifier, required if updating an existing record.
	 */
	@JsonProperty("id")
	@GraphQLScalar(fieldName = "id", graphQLTypeSimpleName = "ID", javaClass = Long.class, listDepth = 0)
	Long id;

	/**
	 * A five-star rating for the publication, indicative of impact, quality, credibility, citations, etc.
	 */
	@JsonProperty("rating")
	@GraphQLScalar(fieldName = "rating", graphQLTypeSimpleName = "Int", javaClass = Integer.class, listDepth = 0)
	Integer rating;

	/**
	 * The names of the author, one per line.
	 */
	@JsonProperty("authorNames")
	@GraphQLScalar(fieldName = "authorNames", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String authorNames;

	/**
	 * The identifier(s) of the author(s) of the publication.
	 */
	@JsonProperty("authorIds")
	@GraphQLScalar(fieldName = "authorIds", graphQLTypeSimpleName = "ID", javaClass = Long.class, listDepth = 1)
	List<Long> authorIds;

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	@GraphQLScalar(fieldName = "title", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String title;

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journal")
	@GraphQLScalar(fieldName = "journalId", graphQLTypeSimpleName = "Long", javaClass = Long.class, listDepth = 0)
	Long journalId;

	/**
	 * The publication type.
	 */
	@JsonProperty("kind")
	@GraphQLScalar(fieldName = "kind", graphQLTypeSimpleName = "PublicationKind", javaClass = PublicationKind.class,
		listDepth = 0)
	PublicationKind kind;

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	@JsonSerialize(using = CustomJacksonSerializers.Date.class)
	@GraphQLScalar(fieldName = "date", graphQLTypeSimpleName = "Date", javaClass = LocalDate.class, listDepth = 0)
	LocalDate date;

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	@GraphQLScalar(fieldName = "year", graphQLTypeSimpleName = "Int", javaClass = Integer.class, listDepth = 0)
	Integer year;

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	@GraphQLScalar(fieldName = "abstract", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String _abstract;

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	@GraphQLScalar(fieldName = "notes", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String notes;

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	@GraphQLScalar(fieldName = "peerReviewed", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
		listDepth = 0)
	Boolean peerReviewed;

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	@GraphQLScalar(fieldName = "doi", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String doi;

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	@GraphQLScalar(fieldName = "isbn", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String isbn;

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	@JsonSerialize(using = CustomJacksonSerializers.URL.class)
	@GraphQLScalar(fieldName = "url", graphQLTypeSimpleName = "URL", javaClass = URL.class, listDepth = 0)
	URL url;

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	@GraphQLScalar(fieldName = "cached", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class, listDepth = 0)
	Boolean cached;

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	@JsonSerialize(using = CustomJacksonSerializers.Date.class)
	@GraphQLScalar(fieldName = "accessed", graphQLTypeSimpleName = "Date", javaClass = LocalDate.class, listDepth = 0)
	LocalDate accessed;

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * The publication identifier, required if updating an existing record.
	 */
	@Override
	@JsonProperty("id")
	public void setId(Long id) {
		this.id = id;
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * The publication identifier, required if updating an existing record.
	 */
	@Override
	@JsonProperty("id")
	public Long getId() {
		return this.id;
	}

	/**
	 * A five-star rating for the publication, indicative of impact, quality, credibility, citations, etc.
	 */
	@JsonProperty("rating")
	public void setRating(Integer rating) {
		this.rating = rating;
	}

	/**
	 * A five-star rating for the publication, indicative of impact, quality, credibility, citations, etc.
	 */
	@JsonProperty("rating")
	public Integer getRating() {
		return this.rating;
	}

	/**
	 * The names of the author, one per line.
	 */
	@JsonProperty("authorNames")
	public void setAuthorNames(String authorNames) {
		this.authorNames = authorNames;
	}

	/**
	 * The names of the author, one per line.
	 */
	@JsonProperty("authorNames")
	public String getAuthorNames() {
		return this.authorNames;
	}

	/**
	 * The identifier(s) of the author(s) of the publication.
	 */
	@JsonProperty("authorIds")
	public void setAuthorIds(List<Long> authorIds) {
		this.authorIds = authorIds;
	}

	/**
	 * The identifier(s) of the author(s) of the publication.
	 */
	@JsonProperty("authorIds")
	public List<Long> getAuthorIds() {
		return this.authorIds;
	}

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	public String getTitle() {
		return this.title;
	}

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journalId")
	public void setJournalId(Long journalId) {
		this.journalId = journalId;
	}

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journalId")
	public Long getJournalId() {
		return this.journalId;
	}

	/**
	 * The publication type.
	 */
	@JsonProperty("kind")
	public void setKind(PublicationKind kind) {
		this.kind = kind;
	}

	/**
	 * The publication type.
	 */
	@JsonProperty("kind")
	public PublicationKind getKind() {
		return this.kind;
	}

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	public void setDate(LocalDate date) {
		this.date = date;
	}

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	public LocalDate getDate() {
		return this.date;
	}

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	public Integer getYear() {
		return this.year;
	}

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	public void setAbstract(String _abstract) {
		this._abstract = _abstract;
	}

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	public String getAbstract() {
		return this._abstract;
	}

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	public String getNotes() {
		return this.notes;
	}

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	public void setPeerReviewed(Boolean peerReviewed) {
		this.peerReviewed = peerReviewed;
	}

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	public Boolean getPeerReviewed() {
		return this.peerReviewed;
	}

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	public void setDoi(String doi) {
		this.doi = doi;
	}

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	public String getDoi() {
		return this.doi;
	}

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	public String getIsbn() {
		return this.isbn;
	}

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	public void setUrl(URL url) {
		this.url = url;
	}

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	public URL getUrl() {
		return this.url;
	}

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	public void setCached(Boolean cached) {
		this.cached = cached;
	}

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	public Boolean getCached() {
		return this.cached;
	}

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	public void setAccessed(LocalDate accessed) {
		this.accessed = accessed;
	}

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	public LocalDate getAccessed() {
		return this.accessed;
	}

	public String toString() {
		return "PublicationInput {" //
			+ "id: " + this.id //
			+ ", " //
			+ "rating: " + this.rating //
			+ ", " //
			+ "authorNames: " + this.authorNames //
			+ ", " //
			+ "authorIds: " + this.authorIds //
			+ ", " //
			+ "title: " + this.title //
			+ ", " //
			+ "journalId: " + this.journalId //
			+ ", " //
			+ "kind: " + this.kind //
			+ ", " //
			+ "date: " + this.date //
			+ ", " //
			+ "year: " + this.year //
			+ ", " //
			+ "_abstract: " + this._abstract //
			+ ", " //
			+ "notes: " + this.notes //
			+ ", " //
			+ "peerReviewed: " + this.peerReviewed //
			+ ", " //
			+ "doi: " + this.doi //
			+ ", " //
			+ "isbn: " + this.isbn //
			+ ", " //
			+ "url: " + this.url //
			+ ", " //
			+ "cached: " + this.cached //
			+ ", " //
			+ "accessed: " + this.accessed //
			+ "}";
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractTrackedEntityInput.Builder<Builder, PublicationInput> {

		private String authorNames;
		private List<Long> authorIds;
		private String title;
		private Long journalId;
		private PublicationKind kind;
		private LocalDate date;
		private Integer year;
		private String _abstract;
		private String notes;
		private Boolean peerReviewed;
		private String doi;
		private String isbn;
		private URL url;
		private Boolean cached;
		private LocalDate accessed;

		/**
		 * The names of the author, one per line.
		 */
		public Builder withAuthorNames(String authorNamesParam) {
			this.authorNames = authorNamesParam;
			return this;
		}

		/**
		 * The identifier(s) of the author(s) of the publication.
		 */
		public Builder withAuthorIds(List<Long> authorIdsParam) {
			this.authorIds = authorIdsParam;
			return this;
		}

		/**
		 * The publication title.
		 */
		public Builder withTitle(String titleParam) {
			this.title = titleParam;
			return this;
		}

		/**
		 * The name of the journal in which the publication appeared.
		 */
		public Builder withJournalId(Long journalIdParam) {
			this.journalId = journalIdParam;
			return this;
		}

		/**
		 * The publication type.
		 */
		public Builder withKind(PublicationKind kindParam) {
			this.kind = kindParam;
			return this;
		}

		/**
		 * The publication date.
		 */
		public Builder withDate(LocalDate dateParam) {
			this.date = dateParam;
			return this;
		}

		/**
		 * The publication year.
		 */
		public Builder withYear(Integer yearParam) {
			this.year = yearParam;
			return this;
		}

		/**
		 * The publication abstract.
		 */
		public Builder withAbstract(String _abstractParam) {
			this._abstract = _abstractParam;
			return this;
		}

		/**
		 * User notes about the publication.
		 */
		public Builder withNotes(String notesParam) {
			this.notes = notesParam;
			return this;
		}

		/**
		 * Whether the publication has been peer reviewed.
		 */
		public Builder withPeerReviewed(Boolean peerReviewedParam) {
			this.peerReviewed = peerReviewedParam;
			return this;
		}

		/**
		 * The digital object identifier.
		 */
		public Builder withDoi(String doiParam) {
			this.doi = doiParam;
			return this;
		}

		/**
		 * The International Standard Book Number.
		 */
		public Builder withIsbn(String isbnParam) {
			this.isbn = isbnParam;
			return this;
		}

		/**
		 * The URL for the publication online.
		 */
		public Builder withUrl(URL urlParam) {
			this.url = urlParam;
			return this;
		}

		/**
		 * Flag to indicate that url content is cached on this application server.
		 */
		public Builder withCached(Boolean cachedParam) {
			this.cached = cachedParam;
			return this;
		}

		/**
		 * The date the publication was accessed when compiling the database.
		 */
		public Builder withAccessed(LocalDate accessedParam) {
			this.accessed = accessedParam;
			return this;
		}

		@Override
		public PublicationInput build() {
			PublicationInput _object = build(new PublicationInput());
			_object.setAuthorNames(this.authorNames);
			_object.setAuthorIds(this.authorIds);
			_object.setTitle(this.title);
			_object.setJournalId(this.journalId);
			_object.setKind(this.kind);
			_object.setDate(this.date);
			_object.setYear(this.year);
			_object.setAbstract(this._abstract);
			_object.setNotes(this.notes);
			_object.setPeerReviewed(this.peerReviewed);
			_object.setDoi(this.doi);
			_object.setIsbn(this.isbn);
			_object.setUrl(this.url);
			_object.setCached(this.cached);
			_object.setAccessed(this.accessed);
			return _object;
		}

	}

}
