/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.net.URL;
import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;

import io.github.demonfiddler.ee.client.util.CustomJacksonDeserializers;

/**
 * A publication associated with given topics.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("Publication")
@JsonInclude(Include.NON_NULL)
public class Publication extends AbstractLinkableEntity {

	public Publication() {
	}

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	@GraphQLScalar(fieldName = "title", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String title;

	/**
	 * The names of the authors, one per line.
	 */
	@JsonProperty("authors")
	@GraphQLScalar(fieldName = "authors", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String authors;

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journal")
	@GraphQLNonScalar(fieldName = "journal", graphQLTypeSimpleName = "Journal", javaClass = Journal.class,
		listDepth = 0)
	Journal journal;

	/**
	 * The publication kind.
	 */
	@JsonProperty("kind")
	@GraphQLInputParameters(names = { "format" }, types = { "FormatKind" }, mandatories = { false }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLScalar(fieldName = "kind", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String kind;

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	@JsonDeserialize(using = CustomJacksonDeserializers.Date.class)
	@GraphQLScalar(fieldName = "date", graphQLTypeSimpleName = "Date", javaClass = LocalDate.class, listDepth = 0)
	LocalDate date;

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	@GraphQLScalar(fieldName = "year", graphQLTypeSimpleName = "Int", javaClass = Integer.class, listDepth = 0)
	Integer year;

	/**
	 * Keywords per publication metadata.
	 */
	@JsonProperty("keywords")
	@GraphQLScalar(fieldName = "keywords", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String keywords;

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	@GraphQLScalar(fieldName = "abstract", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String _abstract;

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	@GraphQLScalar(fieldName = "notes", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String notes;

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	@GraphQLScalar(fieldName = "peerReviewed", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
		listDepth = 0)
	Boolean peerReviewed;

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	@GraphQLScalar(fieldName = "doi", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String doi;

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	@GraphQLScalar(fieldName = "isbn", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String isbn;

	/**
	 * The U.S. National Library of Medicine's PubMed Central ID.
	 */
	@JsonProperty("pmcid")
	@GraphQLScalar(fieldName = "pmcid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String pmcid;

	/**
	 * The U.S. National Library of Medicine's PubMed ID.
	 */
	@JsonProperty("pmid")
	@GraphQLScalar(fieldName = "pmid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String pmid;

	/**
	 * The Corporation for National Research Initiatives's Handle System ID.
	 */
	@JsonProperty("hsid")
	@GraphQLScalar(fieldName = "hsid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String hsid;

	/**
	 * Cornell University Library's arXiv.org ID.
	 */
	@JsonProperty("arxivid")
	@GraphQLScalar(fieldName = "arxivid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String arxivid;

	/**
	 * Cold Spring Harbor Laboratory's bioRxiv.org ID.
	 */
	@JsonProperty("biorxivid")
	@GraphQLScalar(fieldName = "biorxivid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String biorxivid;

	/**
	 * Cold Spring Harbor Laboratory's medRxiv.org ID.
	 */
	@JsonProperty("medrxivid")
	@GraphQLScalar(fieldName = "medrxivid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String medrxivid;

	/**
	 * U.S. Department of Education's ERIC database ID (niche).
	 */
	@JsonProperty("ericid")
	@GraphQLScalar(fieldName = "ericid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String ericid;

	/**
	 * CERN's INSPIRE-HEP ID.
	 */
	@JsonProperty("ihepid")
	@GraphQLScalar(fieldName = "ihepid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String ihepid;

	/**
	 * Open Archives Initiative's OAI-PMH ID.
	 */
	@JsonProperty("oaipmhid")
	@GraphQLScalar(fieldName = "oaipmhid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String oaipmhid;

	/**
	 * CNRS (France)'s HAL ID.
	 */
	@JsonProperty("halid")
	@GraphQLScalar(fieldName = "halid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String halid;

	/**
	 * CERN's Zenodo Record ID.
	 */
	@JsonProperty("zenodoid")
	@GraphQLScalar(fieldName = "zenodoid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String zenodoid;

	/**
	 * Elsevier's SCOPUS database EID (proprietary).
	 */
	@JsonProperty("scopuseid")
	@GraphQLScalar(fieldName = "scopuseid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String scopuseid;

	/**
	 * Clarivate's Web of Science Accession Number (UT) (proprietary).
	 */
	@JsonProperty("wsan")
	@GraphQLScalar(fieldName = "wsan", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String wsan;

	/**
	 * American Psychological Association's PsycINFO Accession Number (proprietary/niche).
	 */
	@JsonProperty("pinfoan")
	@GraphQLScalar(fieldName = "pinfoan", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String pinfoan;

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	@JsonDeserialize(using = CustomJacksonDeserializers.URL.class)
	@GraphQLScalar(fieldName = "url", graphQLTypeSimpleName = "URL", javaClass = URL.class, listDepth = 0)
	URL url;

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	@GraphQLScalar(fieldName = "cached", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class, listDepth = 0)
	Boolean cached;

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	@JsonDeserialize(using = CustomJacksonDeserializers.Date.class)
	@GraphQLScalar(fieldName = "accessed", graphQLTypeSimpleName = "Date", javaClass = LocalDate.class, listDepth = 0)
	LocalDate accessed;

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	public String getTitle() {
		return this.title;
	}

	/**
	 * The names of the authors, one per line.
	 */
	@JsonProperty("authors")
	public void setAuthors(String authors) {
		this.authors = authors;
	}

	/**
	 * The names of the authors, one per line.
	 */
	@JsonProperty("authors")
	public String getAuthors() {
		return this.authors;
	}

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journal")
	public void setJournal(Journal journal) {
		this.journal = journal;
	}

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journal")
	public Journal getJournal() {
		return this.journal;
	}

	/**
	 * The publication kind.
	 */
	@JsonProperty("kind")
	public void setKind(String kind) {
		this.kind = kind;
	}

	/**
	 * The publication kind.
	 */
	@JsonProperty("kind")
	public String getKind() {
		return this.kind;
	}

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	public void setDate(LocalDate date) {
		this.date = date;
	}

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	public LocalDate getDate() {
		return this.date;
	}

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	public Integer getYear() {
		return this.year;
	}

	/**
	 * Keywords per publication metadata.
	 */
	@JsonProperty("keywords")
	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	/**
	 * Keywords per publication metadata.
	 */
	@JsonProperty("keywords")
	public String getKeywords() {
		return this.keywords;
	}

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	public void setAbstract(String _abstract) {
		this._abstract = _abstract;
	}

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	public String getAbstract() {
		return this._abstract;
	}

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	public String getNotes() {
		return this.notes;
	}

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	public void setPeerReviewed(Boolean peerReviewed) {
		this.peerReviewed = peerReviewed;
	}

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	public Boolean getPeerReviewed() {
		return this.peerReviewed;
	}

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	public void setDoi(String doi) {
		this.doi = doi;
	}

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	public String getDoi() {
		return this.doi;
	}

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	public void setIsbn(String issnIsbn) {
		this.isbn = issnIsbn;
	}

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	public String getIsbn() {
		return this.isbn;
	}

	/**
	 * The U.S. National Library of Medicine's PubMed Central ID.
	 */
	@JsonProperty("pmcid")
	public void setPmcid(String pmcid) {
		this.pmcid = pmcid;
	}

	/**
	 * The U.S. National Library of Medicine's PubMed Central ID.
	 */
	@JsonProperty("pmcid")
	public String getPmcid() {
		return this.pmcid;
	}

	/**
	 * The U.S. National Library of Medicine's PubMed ID.
	 */
	@JsonProperty("pmid")
	public void setPmid(String pmid) {
		this.pmid = pmid;
	}

	/**
	 * The U.S. National Library of Medicine's PubMed ID.
	 */
	@JsonProperty("pmid")
	public String getPmid() {
		return this.pmid;
	}

	/**
	 * The Corporation for National Research Initiatives's Handle System ID.
	 */
	@JsonProperty("hsid")
	public void setHsid(String hsid) {
		this.hsid = hsid;
	}

	/**
	 * The Corporation for National Research Initiatives's Handle System ID.
	 */
	@JsonProperty("hsid")
	public String getHsid() {
		return this.hsid;
	}

	/**
	 * Cornell University Library's arXiv.org ID.
	 */
	@JsonProperty("arxivid")
	public void setArxivid(String arxivid) {
		this.arxivid = arxivid;
	}

	/**
	 * Cornell University Library's arXiv.org ID.
	 */
	@JsonProperty("arxivid")
	public String getArxivid() {
		return this.arxivid;
	}

	/**
	 * Cold Spring Harbor Laboratory's bioRxiv.org ID.
	 */
	@JsonProperty("biorxivid")
	public void setBiorxivid(String biorxivid) {
		this.biorxivid = biorxivid;
	}

	/**
	 * Cold Spring Harbor Laboratory's bioRxiv.org ID.
	 */
	@JsonProperty("biorxivid")
	public String getBiorxivid() {
		return this.biorxivid;
	}

	/**
	 * Cold Spring Harbor Laboratory's medRxiv.org ID.
	 */
	@JsonProperty("medrxivid")
	public void setMedrxivid(String medrxivid) {
		this.medrxivid = medrxivid;
	}

	/**
	 * Cold Spring Harbor Laboratory's medRxiv.org ID.
	 */
	@JsonProperty("medrxivid")
	public String getMedrxivid() {
		return this.medrxivid;
	}

	/**
	 * U.S. Department of Education's ERIC database ID (niche).
	 */
	@JsonProperty("ericid")
	public void setEricid(String ericid) {
		this.ericid = ericid;
	}

	/**
	 * U.S. Department of Education's ERIC database ID (niche).
	 */
	@JsonProperty("ericid")
	public String getEricid() {
		return this.ericid;
	}

	/**
	 * CERN's INSPIRE-HEP ID.
	 */
	@JsonProperty("ihepid")
	public void setIhepid(String ihepid) {
		this.ihepid = ihepid;
	}

	/**
	 * CERN's INSPIRE-HEP ID.
	 */
	@JsonProperty("ihepid")
	public String getIhepid() {
		return this.ihepid;
	}

	/**
	 * Open Archives Initiative's OAI-PMH ID.
	 */
	@JsonProperty("oaipmhid")
	public void setOaipmhid(String oaipmhid) {
		this.oaipmhid = oaipmhid;
	}

	/**
	 * Open Archives Initiative's OAI-PMH ID.
	 */
	@JsonProperty("oaipmhid")
	public String getOaipmhid() {
		return this.oaipmhid;
	}

	/**
	 * CNRS (France)'s HAL ID.
	 */
	@JsonProperty("halid")
	public void setHalid(String halid) {
		this.halid = halid;
	}

	/**
	 * CNRS (France)'s HAL ID.
	 */
	@JsonProperty("halid")
	public String getHalid() {
		return this.halid;
	}

	/**
	 * CERN's Zenodo Record ID.
	 */
	@JsonProperty("zenodoid")
	public void setZenodoid(String zenodoid) {
		this.zenodoid = zenodoid;
	}

	/**
	 * CERN's Zenodo Record ID.
	 */
	@JsonProperty("zenodoid")
	public String getZenodoid() {
		return this.zenodoid;
	}

	/**
	 * Elsevier's SCOPUS database EID (proprietary).
	 */
	@JsonProperty("scopuseid")
	public void setScopuseid(String scopuseid) {
		this.scopuseid = scopuseid;
	}

	/**
	 * Elsevier's SCOPUS database EID (proprietary).
	 */
	@JsonProperty("scopuseid")
	public String getScopuseid() {
		return this.scopuseid;
	}

	/**
	 * Clarivate's Web of Science Accession Number (UT) (proprietary).
	 */
	@JsonProperty("wsan")
	public void setWsan(String wsan) {
		this.wsan = wsan;
	}

	/**
	 * Clarivate's Web of Science Accession Number (UT) (proprietary).
	 */
	@JsonProperty("wsan")
	public String getWsan() {
		return this.wsan;
	}

	/**
	 * American Psychological Association's PsycINFO Accession Number (proprietary/niche).
	 */
	@JsonProperty("pinfoan")
	public void setPinfoan(String pinfoan) {
		this.pinfoan = pinfoan;
	}

	/**
	 * American Psychological Association's PsycINFO Accession Number (proprietary/niche).
	 */
	@JsonProperty("pinfoan")
	public String getPinfoan() {
		return this.pinfoan;
	}

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	public void setUrl(URL url) {
		this.url = url;
	}

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	public URL getUrl() {
		return this.url;
	}

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	public void setCached(Boolean cached) {
		this.cached = cached;
	}

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	public Boolean getCached() {
		return this.cached;
	}

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	public void setAccessed(LocalDate accessed) {
		this.accessed = accessed;
	}

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	public LocalDate getAccessed() {
		return this.accessed;
	}

	public String toString() {
		return "Publication {" //
			+ "id: " + this.id //
			+ ", " //
			+ "entityKind: " + this.entityKind //
			+ ", " //
			+ "status: " + this.status //
			+ ", " //
			+ "rating: " + this.rating //
			+ ", " //
			+ "created: " + this.created //
			+ ", " //
			+ "createdByUser.id: " + (this.createdByUser == null ? null : this.createdByUser.getId()) //
			+ ", " //
			+ "updated: " + this.updated //
			+ ", " //
			+ "updatedByUser.id: " + (this.updatedByUser == null ? null : this.updatedByUser.getId()) //
			+ ", " //
			+ "log: " + this.log //
			+ ", " //
			+ "comments: " + this.comments //
			+ ", " //
			+ "fromEntityLinks: " + this.fromEntityLinks //
			+ ", " //
			+ "toEntityLinks: " + this.toEntityLinks //
			+ ", " //
			+ "title: " + this.title //
			+ ", " //
			+ "authors: " + this.authors //
			+ ", " //
			+ "journal: " + this.journal //
			+ ", " //
			+ "kind: " + this.kind //
			+ ", " //
			+ "date: " + this.date //
			+ ", " //
			+ "year: " + this.year //
			+ ", " //
			+ "keywords: " + this.keywords //
			+ ", " //
			+ "_abstract: " + this._abstract //
			+ ", " //
			+ "notes: " + this.notes //
			+ ", " //
			+ "peerReviewed: " + this.peerReviewed //
			+ ", " //
			+ "doi: " + this.doi //
			+ ", " //
			+ "isbn: " + this.isbn //
			+ ", " //
			+ "pmcid: " + this.pmcid //
			+ ", " //
			+ "pmid: " + this.pmid //
			+ ", " //
			+ "hsid: " + this.hsid //
			+ ", " //
			+ "arxivid: " + this.arxivid //
			+ ", " //
			+ "biorxivid: " + this.biorxivid //
			+ ", " //
			+ "medrxivid: " + this.medrxivid //
			+ ", " //
			+ "ericid: " + this.ericid //
			+ ", " //
			+ "ihepid: " + this.ihepid //
			+ ", " //
			+ "oaipmhid: " + this.oaipmhid //
			+ ", " //
			+ "halid: " + this.halid //
			+ ", " //
			+ "zenodoid: " + this.zenodoid //
			+ ", " //
			+ "scopuseid: " + this.scopuseid //
			+ ", " //
			+ "wsan: " + this.wsan //
			+ ", " //
			+ "pinfoan: " + this.pinfoan //
			+ ", " //
			+ "url: " + this.url //
			+ ", " //
			+ "cached: " + this.cached //
			+ ", " //
			+ "accessed: " + this.accessed //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		result = prime * result + ((authors == null) ? 0 : authors.hashCode());
		result = prime * result + ((journal == null) ? 0 : journal.hashCode());
		result = prime * result + ((kind == null) ? 0 : kind.hashCode());
		result = prime * result + ((date == null) ? 0 : date.hashCode());
		result = prime * result + ((year == null) ? 0 : year.hashCode());
		result = prime * result + ((keywords == null) ? 0 : keywords.hashCode());
		result = prime * result + ((_abstract == null) ? 0 : _abstract.hashCode());
		result = prime * result + ((notes == null) ? 0 : notes.hashCode());
		result = prime * result + ((peerReviewed == null) ? 0 : peerReviewed.hashCode());
		result = prime * result + ((doi == null) ? 0 : doi.hashCode());
		result = prime * result + ((isbn == null) ? 0 : isbn.hashCode());
		result = prime * result + ((pmcid == null) ? 0 : pmcid.hashCode());
		result = prime * result + ((pmid == null) ? 0 : pmid.hashCode());
		result = prime * result + ((hsid == null) ? 0 : hsid.hashCode());
		result = prime * result + ((arxivid == null) ? 0 : arxivid.hashCode());
		result = prime * result + ((biorxivid == null) ? 0 : biorxivid.hashCode());
		result = prime * result + ((medrxivid == null) ? 0 : medrxivid.hashCode());
		result = prime * result + ((ericid == null) ? 0 : ericid.hashCode());
		result = prime * result + ((ihepid == null) ? 0 : ihepid.hashCode());
		result = prime * result + ((oaipmhid == null) ? 0 : oaipmhid.hashCode());
		result = prime * result + ((halid == null) ? 0 : halid.hashCode());
		result = prime * result + ((zenodoid == null) ? 0 : zenodoid.hashCode());
		result = prime * result + ((scopuseid == null) ? 0 : scopuseid.hashCode());
		result = prime * result + ((wsan == null) ? 0 : wsan.hashCode());
		result = prime * result + ((pinfoan == null) ? 0 : pinfoan.hashCode());
		result = prime * result + ((url == null) ? 0 : url.hashCode());
		result = prime * result + ((cached == null) ? 0 : cached.hashCode());
		result = prime * result + ((accessed == null) ? 0 : accessed.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (!super.equals(obj))
			return false;
		Publication other = (Publication)obj;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		if (authors == null) {
			if (other.authors != null)
				return false;
		} else if (!authors.equals(other.authors))
			return false;
		if (journal == null) {
			if (other.journal != null)
				return false;
		} else if (!journal.equals(other.journal))
			return false;
		if (kind == null) {
			if (other.kind != null)
				return false;
		} else if (!kind.equals(other.kind))
			return false;
		if (date == null) {
			if (other.date != null)
				return false;
		} else if (!date.equals(other.date))
			return false;
		if (year == null) {
			if (other.year != null)
				return false;
		} else if (!year.equals(other.year))
			return false;
		if (keywords == null) {
			if (other.keywords != null)
				return false;
		} else if (!year.equals(other.year))
			return false;
		if (_abstract == null) {
			if (other._abstract != null)
				return false;
		} else if (!_abstract.equals(other._abstract))
			return false;
		if (notes == null) {
			if (other.notes != null)
				return false;
		} else if (!notes.equals(other.notes))
			return false;
		if (peerReviewed == null) {
			if (other.peerReviewed != null)
				return false;
		} else if (!peerReviewed.equals(other.peerReviewed))
			return false;
		if (doi == null) {
			if (other.doi != null)
				return false;
		} else if (!doi.equals(other.doi))
			return false;
		if (isbn == null) {
			if (other.isbn != null)
				return false;
		} else if (!isbn.equals(other.isbn))
			return false;
		if (pmcid == null) {
			if (other.pmcid != null)
				return false;
		} else if (!pmcid.equals(other.pmcid))
			return false;
		if (pmid == null) {
			if (other.pmid != null)
				return false;
		} else if (!pmid.equals(other.pmid))
			return false;
		if (hsid == null) {
			if (other.hsid != null)
				return false;
		} else if (!hsid.equals(other.hsid))
			return false;
		if (arxivid == null) {
			if (other.arxivid != null)
				return false;
		} else if (!arxivid.equals(other.arxivid))
			return false;
		if (biorxivid == null) {
			if (other.biorxivid != null)
				return false;
		} else if (!biorxivid.equals(other.biorxivid))
			return false;
		if (medrxivid == null) {
			if (other.medrxivid != null)
				return false;
		} else if (!medrxivid.equals(other.medrxivid))
			return false;
		if (ericid == null) {
			if (other.ericid != null)
				return false;
		} else if (!ericid.equals(other.ericid))
			return false;
		if (ihepid == null) {
			if (other.ihepid != null)
				return false;
		} else if (!ihepid.equals(other.ihepid))
			return false;
		if (oaipmhid == null) {
			if (other.oaipmhid != null)
				return false;
		} else if (!oaipmhid.equals(other.oaipmhid))
			return false;
		if (halid == null) {
			if (other.halid != null)
				return false;
		} else if (!halid.equals(other.halid))
			return false;
		if (zenodoid == null) {
			if (other.zenodoid != null)
				return false;
		} else if (!zenodoid.equals(other.zenodoid))
			return false;
		if (scopuseid == null) {
			if (other.scopuseid != null)
				return false;
		} else if (!scopuseid.equals(other.scopuseid))
			return false;
		if (wsan == null) {
			if (other.wsan != null)
				return false;
		} else if (!wsan.equals(other.wsan))
			return false;
		if (pinfoan == null) {
			if (other.pinfoan != null)
				return false;
		} else if (!pinfoan.equals(other.pinfoan))
			return false;
		if (url == null) {
			if (other.url != null)
				return false;
		} else if (!url.equals(other.url))
			return false;
		if (cached == null) {
			if (other.cached != null)
				return false;
		} else if (!cached.equals(other.cached))
			return false;
		if (accessed == null) {
			if (other.accessed != null)
				return false;
		} else if (!accessed.equals(other.accessed))
			return false;
		return true;
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractLinkableEntity.Builder<Builder, Publication> {

		private String title;
		private String authors;
		private Journal journal;
		private String kind;
		private LocalDate date;
		private Integer year;
		private String keywords;
		private String _abstract;
		private String notes;
		private Boolean peerReviewed;
		private String doi;
		private String isbn;
		private String pmcid;
		private String pmid;
		private String hsid;
		private String arxivid;
		private String biorxivid;
		private String medrxivid;
		private String ericid;
		private String ihepid;
		private String oaipmhid;
		private String halid;
		private String zenodoid;
		private String scopuseid;
		private String wsan;
		private String pinfoan;
		private URL url;
		private Boolean cached;
		private LocalDate accessed;

		/**
		 * The publication title.
		 */
		public Builder withTitle(String titleParam) {
			this.title = titleParam;
			return this;
		}

		/**
		 * The names of the authors, one per line.
		 */
		public Builder withAuthors(String authorsParam) {
			this.authors = authorsParam;
			return this;
		}

		/**
		 * The name of the journal in which the publication appeared.
		 */
		public Builder withJournal(Journal journalParam) {
			this.journal = journalParam;
			return this;
		}

		/**
		 * The publication kind.
		 */
		public Builder withKind(String kindParam) {
			this.kind = kindParam;
			return this;
		}

		/**
		 * The publication date.
		 */
		public Builder withDate(LocalDate dateParam) {
			this.date = dateParam;
			return this;
		}

		/**
		 * The publication year.
		 */
		public Builder withYear(Integer yearParam) {
			this.year = yearParam;
			return this;
		}

		/**
		 * Keywords per publication metadata.
		 */
		public Builder withKeywords(String keywordsParam) {
			this.keywords = keywordsParam;
			return this;
		}

		/**
		 * The publication abstract.
		 */
		public Builder withAbstract(String _abstractParam) {
			this._abstract = _abstractParam;
			return this;
		}

		/**
		 * User notes about the publication.
		 */
		public Builder withNotes(String notesParam) {
			this.notes = notesParam;
			return this;
		}

		/**
		 * Whether the publication has been peer reviewed.
		 */
		public Builder withPeerReviewed(Boolean peerReviewedParam) {
			this.peerReviewed = peerReviewedParam;
			return this;
		}

		/**
		 * The digital object identifier.
		 */
		public Builder withDoi(String doiParam) {
			this.doi = doiParam;
			return this;
		}

		/**
		 * The International Standard Book Number.
		 */
		public Builder withIsbn(String isbnParam) {
			this.isbn = isbnParam;
			return this;
		}

		/**
		 * The U.S. National Library of Medicine's PubMed Central ID.
		 */
		public Builder withPmcid(String pmcidParam) {
			this.pmcid = pmcidParam;
			return this;
		}

		/**
		 * The U.S. National Library of Medicine's PubMedID.
		 */
		public Builder withPmid(String pmidParam) {
			this.pmid = pmidParam;
			return this;
		}

		/**
		 * The Corporation for National Research Initiatives's Handle System ID.
		 */
		public Builder withHsid(String hsidParam) {
			this.hsid = hsidParam;
			return this;
		}

		/**
		 * Cornell University Library's arXiv.org ID.
		 */
		public Builder withArxivid(String arxividParam) {
			this.arxivid = arxividParam;
			return this;
		}

		/**
		 * Cold Spring Harbor Laboratory's bioRxiv.org ID.
		 */
		public Builder withBiorxivid(String biorxividParam) {
			this.biorxivid = biorxividParam;
			return this;
		}

		/**
		 * Cold Spring Harbor Laboratory's medRxiv.org ID.
		 */
		public Builder withMedrxivid(String medrxividParam) {
			this.medrxivid = medrxividParam;
			return this;
		}

		/**
		 * U.S. Department of Education's ERIC database ID (niche).
		 */
		public Builder withEricid(String ericidParam) {
			this.ericid = ericidParam;
			return this;
		}

		/**
		 * CERN's INSPIRE-HEP ID.
		 */
		public Builder withIhepid(String ihepidParam) {
			this.ihepid = ihepidParam;
			return this;
		}

		/**
		 * Open Archives Initiative's OAI-PMH ID.
		 */
		public Builder withOaipmhid(String oaipmhidParam) {
			this.oaipmhid = oaipmhidParam;
			return this;
		}

		/**
		 * CNRS (France)'s HAL ID.
		 */
		public Builder withHalid(String halidParam) {
			this.halid = halidParam;
			return this;
		}

		/**
		 * CERN's Zenodo Record ID.
		 */
		public Builder withZenodoid(String zenodoidParam) {
			this.zenodoid = zenodoidParam;
			return this;
		}

		/**
		 * Elsevier's SCOPUS database EID (proprietary).
		 */
		public Builder withScopuseid(String scopuseidParam) {
			this.scopuseid = scopuseidParam;
			return this;
		}

		/**
		 * Clarivate's Web of Science Accession Number (UT) (proprietary).
		 */
		public Builder withWsan(String wsanParam) {
			this.wsan = wsanParam;
			return this;
		}

		/**
		 * American Psychological Association's PsycINFO Accession Number (proprietary/niche).
		 */
		public Builder withPinfoan(String pinfoanParam) {
			this.pinfoan = pinfoanParam;
			return this;
		}

		/**
		 * The URL for the publication online.
		 */
		public Builder withUrl(URL urlParam) {
			this.url = urlParam;
			return this;
		}

		/**
		 * Flag to indicate that url content is cached on this application server.
		 */
		public Builder withCached(Boolean cachedParam) {
			this.cached = cachedParam;
			return this;
		}

		/**
		 * The date the publication was accessed when compiling the database.
		 */
		public Builder withAccessed(LocalDate accessedParam) {
			this.accessed = accessedParam;
			return this;
		}

		@Override
		public Publication build() {
			Publication _object = build(new Publication());
			_object.setTitle(this.title);
			_object.setAuthors(this.authors);
			_object.setJournal(this.journal);
			_object.setKind(this.kind);
			_object.setDate(this.date);
			_object.setYear(this.year);
			_object.setKeywords(this.keywords);
			_object.setAbstract(this._abstract);
			_object.setNotes(this.notes);
			_object.setPeerReviewed(this.peerReviewed);
			_object.setDoi(this.doi);
			_object.setIsbn(this.isbn);
			_object.setPmcid(this.pmcid);
			_object.setPmid(this.pmid);
			_object.setHsid(this.hsid);
			_object.setArxivid(this.arxivid);
			_object.setBiorxivid(this.biorxivid);
			_object.setMedrxivid(this.medrxivid);
			_object.setEricid(this.ericid);
			_object.setIhepid(this.ihepid);
			_object.setOaipmhid(this.oaipmhid);
			_object.setHalid(this.halid);
			_object.setZenodoid(this.zenodoid);
			_object.setScopuseid(this.scopuseid);
			_object.setWsan(this.wsan);
			_object.setPinfoan(this.pinfoan);
			_object.setUrl(this.url);
			_object.setCached(this.cached);
			_object.setAccessed(this.accessed);
			return _object;
		}

		@Override
		String getTypeName() {
			return "Publication";
		}

	}

}
