/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.net.URL;
import java.time.LocalDate;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.graphql_java_generator.annotation.GraphQLInputType;
import com.graphql_java_generator.annotation.GraphQLScalar;

import io.github.demonfiddler.ee.client.util.CustomJacksonSerializers;

/**
 * An input for creating or updating a publication.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLInputType("PublicationInput")
@JsonInclude(Include.NON_NULL)
public class PublicationInput extends AbstractTrackedEntityInput {

	public PublicationInput() {
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * The publication identifier, required if updating an existing record.
	 */
	@JsonProperty("id")
	@GraphQLScalar(fieldName = "id", graphQLTypeSimpleName = "ID", javaClass = Long.class, listDepth = 0)
	Long id;

	/**
	 * A five-star rating for the publication, indicative of impact, quality, credibility, citations, etc.
	 */
	@JsonProperty("rating")
	@GraphQLScalar(fieldName = "rating", graphQLTypeSimpleName = "Int", javaClass = Integer.class, listDepth = 0)
	Integer rating;

	/**
	 * The names of the author, one per line.
	 */
	@JsonProperty("authorNames")
	@GraphQLScalar(fieldName = "authorNames", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String authorNames;

	/**
	 * The identifier(s) of the author(s) of the publication.
	 */
	@JsonProperty("authorIds")
	@GraphQLScalar(fieldName = "authorIds", graphQLTypeSimpleName = "ID", javaClass = Long.class, listDepth = 1)
	List<Long> authorIds;

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	@GraphQLScalar(fieldName = "title", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String title;

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journal")
	@GraphQLScalar(fieldName = "journalId", graphQLTypeSimpleName = "Long", javaClass = Long.class, listDepth = 0)
	Long journalId;

	/**
	 * The publication type.
	 */
	@JsonProperty("kind")
	@GraphQLScalar(fieldName = "kind", graphQLTypeSimpleName = "PublicationKind", javaClass = PublicationKind.class,
		listDepth = 0)
	PublicationKind kind;

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	@JsonSerialize(using = CustomJacksonSerializers.Date.class)
	@GraphQLScalar(fieldName = "date", graphQLTypeSimpleName = "Date", javaClass = LocalDate.class, listDepth = 0)
	LocalDate date;

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	@GraphQLScalar(fieldName = "year", graphQLTypeSimpleName = "Int", javaClass = Integer.class, listDepth = 0)
	Integer year;

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	@GraphQLScalar(fieldName = "abstract", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String _abstract;

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	@GraphQLScalar(fieldName = "notes", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String notes;

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	@GraphQLScalar(fieldName = "peerReviewed", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class,
		listDepth = 0)
	Boolean peerReviewed;

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	@GraphQLScalar(fieldName = "doi", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String doi;

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	@GraphQLScalar(fieldName = "isbn", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String isbn;

	/**
	 * The U.S. National Library of Medicine's PubMedID.
	 */
	@JsonProperty("pmid")
	@GraphQLScalar(fieldName = "pmid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String pmid;

	/**
	 * The Corporation for National Research Initiatives's Handle System ID.
	 */
	@JsonProperty("hsid")
	@GraphQLScalar(fieldName = "hsid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String hsid;

	/**
	 * Cornell University Library's arXiv.org ID.
	 */
	@JsonProperty("arxivid")
	@GraphQLScalar(fieldName = "arxivid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String arxivid;

	/**
	 * Cold Spring Harbor Laboratory's bioRxiv.org ID.
	 */
	@JsonProperty("biorxivid")
	@GraphQLScalar(fieldName = "biorxivid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String biorxivid;

	/**
	 * Cold Spring Harbor Laboratory's medRxiv.org ID.
	 */
	@JsonProperty("medrxivid")
	@GraphQLScalar(fieldName = "medrxivid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String medrxivid;

	/**
	 * U.S. Department of Education's ERIC database ID (niche).
	 */
	@JsonProperty("ericid")
	@GraphQLScalar(fieldName = "ericid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String ericid;

	/**
	 * CERN's INSPIRE-HEP ID.
	 */
	@JsonProperty("ihepid")
	@GraphQLScalar(fieldName = "ihepid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String ihepid;

	/**
	 * Open Archives Initiative's OAI-PMH ID.
	 */
	@JsonProperty("oaipmhid")
	@GraphQLScalar(fieldName = "oaipmhid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String oaipmhid;

	/**
	 * CNRS (France)'s HAL ID.
	 */
	@JsonProperty("halid")
	@GraphQLScalar(fieldName = "halid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String halid;

	/**
	 * CERN's Zenodo Record ID.
	 */
	@JsonProperty("zenodoid")
	@GraphQLScalar(fieldName = "zenodoid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String zenodoid;

	/**
	 * Elsevier's SCOPUS database EID (proprietary).
	 */
	@JsonProperty("scopuseid")
	@GraphQLScalar(fieldName = "scopuseid", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String scopuseid;

	/**
	 * Clarivate's Web of Science Accession Number (UT) (proprietary).
	 */
	@JsonProperty("wsan")
	@GraphQLScalar(fieldName = "wsan", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String wsan;

	/**
	 * American Psychological Association's PsycINFO Accession Number (proprietary/niche).
	 */
	@JsonProperty("pinfoan")
	@GraphQLScalar(fieldName = "pinfoan", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String pinfoan;

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	@JsonSerialize(using = CustomJacksonSerializers.URL.class)
	@GraphQLScalar(fieldName = "url", graphQLTypeSimpleName = "URL", javaClass = URL.class, listDepth = 0)
	URL url;

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	@GraphQLScalar(fieldName = "cached", graphQLTypeSimpleName = "Boolean", javaClass = Boolean.class, listDepth = 0)
	Boolean cached;

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	@JsonSerialize(using = CustomJacksonSerializers.Date.class)
	@GraphQLScalar(fieldName = "accessed", graphQLTypeSimpleName = "Date", javaClass = LocalDate.class, listDepth = 0)
	LocalDate accessed;

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * The publication identifier, required if updating an existing record.
	 */
	@Override
	@JsonProperty("id")
	public void setId(Long id) {
		this.id = id;
	}

	// Uncommented, as InputParameter.getStringContentForAnInputTypeValue() doesn't check superclass fields.
	/**
	 * The publication identifier, required if updating an existing record.
	 */
	@Override
	@JsonProperty("id")
	public Long getId() {
		return this.id;
	}

	/**
	 * A five-star rating for the publication, indicative of impact, quality, credibility, citations, etc.
	 */
	@JsonProperty("rating")
	public void setRating(Integer rating) {
		this.rating = rating;
	}

	/**
	 * A five-star rating for the publication, indicative of impact, quality, credibility, citations, etc.
	 */
	@JsonProperty("rating")
	public Integer getRating() {
		return this.rating;
	}

	/**
	 * The names of the author, one per line.
	 */
	@JsonProperty("authorNames")
	public void setAuthorNames(String authorNames) {
		this.authorNames = authorNames;
	}

	/**
	 * The names of the author, one per line.
	 */
	@JsonProperty("authorNames")
	public String getAuthorNames() {
		return this.authorNames;
	}

	/**
	 * The identifier(s) of the author(s) of the publication.
	 */
	@JsonProperty("authorIds")
	public void setAuthorIds(List<Long> authorIds) {
		this.authorIds = authorIds;
	}

	/**
	 * The identifier(s) of the author(s) of the publication.
	 */
	@JsonProperty("authorIds")
	public List<Long> getAuthorIds() {
		return this.authorIds;
	}

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * The publication title.
	 */
	@JsonProperty("title")
	public String getTitle() {
		return this.title;
	}

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journalId")
	public void setJournalId(Long journalId) {
		this.journalId = journalId;
	}

	/**
	 * The name of the journal in which the publication appeared.
	 */
	@JsonProperty("journalId")
	public Long getJournalId() {
		return this.journalId;
	}

	/**
	 * The publication type.
	 */
	@JsonProperty("kind")
	public void setKind(PublicationKind kind) {
		this.kind = kind;
	}

	/**
	 * The publication type.
	 */
	@JsonProperty("kind")
	public PublicationKind getKind() {
		return this.kind;
	}

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	public void setDate(LocalDate date) {
		this.date = date;
	}

	/**
	 * The publication date.
	 */
	@JsonProperty("date")
	public LocalDate getDate() {
		return this.date;
	}

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	public void setYear(Integer year) {
		this.year = year;
	}

	/**
	 * The publication year.
	 */
	@JsonProperty("year")
	public Integer getYear() {
		return this.year;
	}

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	public void setAbstract(String _abstract) {
		this._abstract = _abstract;
	}

	/**
	 * The publication abstract.
	 */
	@JsonProperty("abstract")
	public String getAbstract() {
		return this._abstract;
	}

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * User notes about the publication.
	 */
	@JsonProperty("notes")
	public String getNotes() {
		return this.notes;
	}

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	public void setPeerReviewed(Boolean peerReviewed) {
		this.peerReviewed = peerReviewed;
	}

	/**
	 * Whether the publication has been peer reviewed.
	 */
	@JsonProperty("peerReviewed")
	public Boolean getPeerReviewed() {
		return this.peerReviewed;
	}

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	public void setDoi(String doi) {
		this.doi = doi;
	}

	/**
	 * The digital object identifier.
	 */
	@JsonProperty("doi")
	public String getDoi() {
		return this.doi;
	}

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	/**
	 * The International Standard Book Number.
	 */
	@JsonProperty("isbn")
	public String getIsbn() {
		return this.isbn;
	}

	/**
	 * The U.S. National Library of Medicine's PubMedID.
	 */
	@JsonProperty("pmid")
	public void setPmid(String pmid) {
		this.pmid = pmid;
	}

	/**
	 * The U.S. National Library of Medicine's PubMedID.
	 */
	@JsonProperty("pmid")
	public String getPmid() {
		return this.pmid;
	}

	/**
	 * The Corporation for National Research Initiatives's Handle System ID.
	 */
	@JsonProperty("hsid")
	public void setHsid(String hsid) {
		this.hsid = hsid;
	}

	/**
	 * The Corporation for National Research Initiatives's Handle System ID.
	 */
	@JsonProperty("hsid")
	public String getHsid() {
		return this.hsid;
	}

	/**
	 * Cornell University Library's arXiv.org ID.
	 */
	@JsonProperty("arxivid")
	public void setArxivid(String arxivid) {
		this.arxivid = arxivid;
	}

	/**
	 * Cornell University Library's arXiv.org ID.
	 */
	@JsonProperty("arxivid")
	public String getArxivid() {
		return this.arxivid;
	}

	/**
	 * Cold Spring Harbor Laboratory's bioRxiv.org ID.
	 */
	@JsonProperty("biorxivid")
	public void setBiorxivid(String biorxivid) {
		this.biorxivid = biorxivid;
	}

	/**
	 * Cold Spring Harbor Laboratory's bioRxiv.org ID.
	 */
	@JsonProperty("biorxivid")
	public String getBiorxivid() {
		return this.biorxivid;
	}

	/**
	 * Cold Spring Harbor Laboratory's medRxiv.org ID.
	 */
	@JsonProperty("medrxivid")
	public void setMedrxivid(String medrxivid) {
		this.medrxivid = medrxivid;
	}

	/**
	 * Cold Spring Harbor Laboratory's medRxiv.org ID.
	 */
	@JsonProperty("medrxivid")
	public String getMedrxivid() {
		return this.medrxivid;
	}

	/**
	 * U.S. Department of Education's ERIC database ID (niche).
	 */
	@JsonProperty("ericid")
	public void setEricid(String ericid) {
		this.ericid = ericid;
	}

	/**
	 * U.S. Department of Education's ERIC database ID (niche).
	 */
	@JsonProperty("ericid")
	public String getEricid() {
		return this.ericid;
	}

	/**
	 * CERN's INSPIRE-HEP ID.
	 */
	@JsonProperty("ihepid")
	public void setIhepid(String ihepid) {
		this.ihepid = ihepid;
	}

	/**
	 * CERN's INSPIRE-HEP ID.
	 */
	@JsonProperty("ihepid")
	public String getIhepid() {
		return this.ihepid;
	}

	/**
	 * Open Archives Initiative's OAI-PMH ID.
	 */
	@JsonProperty("oaipmhid")
	public void setOaipmhid(String oaipmhid) {
		this.oaipmhid = oaipmhid;
	}

	/**
	 * Open Archives Initiative's OAI-PMH ID.
	 */
	@JsonProperty("oaipmhid")
	public String getOaipmhid() {
		return this.oaipmhid;
	}

	/**
	 * CNRS (France)'s HAL ID.
	 */
	@JsonProperty("halid")
	public void setHalid(String halid) {
		this.halid = halid;
	}

	/**
	 * CNRS (France)'s HAL ID.
	 */
	@JsonProperty("halid")
	public String getHalid() {
		return this.halid;
	}

	/**
	 * CERN's Zenodo Record ID.
	 */
	@JsonProperty("zenodoid")
	public void setZenodoid(String zenodoid) {
		this.zenodoid = zenodoid;
	}

	/**
	 * CERN's Zenodo Record ID.
	 */
	@JsonProperty("zenodoid")
	public String getZenodoid() {
		return this.zenodoid;
	}

	/**
	 * Elsevier's SCOPUS database EID (proprietary).
	 */
	@JsonProperty("scopuseid")
	public void setScopuseid(String scopuseid) {
		this.scopuseid = scopuseid;
	}

	/**
	 * Elsevier's SCOPUS database EID (proprietary).
	 */
	@JsonProperty("scopuseid")
	public String getScopuseid() {
		return this.scopuseid;
	}

	/**
	 * Clarivate's Web of Science Accession Number (UT) (proprietary).
	 */
	@JsonProperty("wsan")
	public void setWsan(String wsan) {
		this.wsan = wsan;
	}

	/**
	 * Clarivate's Web of Science Accession Number (UT) (proprietary).
	 */
	@JsonProperty("wsan")
	public String getWsan() {
		return this.wsan;
	}

	/**
	 * American Psychological Association's PsycINFO Accession Number (proprietary/niche).
	 */
	@JsonProperty("pinfoan")
	public void setPinfoan(String pinfoan) {
		this.pinfoan = pinfoan;
	}

	/**
	 * American Psychological Association's PsycINFO Accession Number (proprietary/niche).
	 */
	@JsonProperty("pinfoan")
	public String getPinfoan() {
		return this.pinfoan;
	}

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	public void setUrl(URL url) {
		this.url = url;
	}

	/**
	 * The URL for the publication online.
	 */
	@JsonProperty("url")
	public URL getUrl() {
		return this.url;
	}

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	public void setCached(Boolean cached) {
		this.cached = cached;
	}

	/**
	 * Flag to indicate that url content is cached on this application server.
	 */
	@JsonProperty("cached")
	public Boolean getCached() {
		return this.cached;
	}

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	public void setAccessed(LocalDate accessed) {
		this.accessed = accessed;
	}

	/**
	 * The date the publication was accessed when compiling the database.
	 */
	@JsonProperty("accessed")
	public LocalDate getAccessed() {
		return this.accessed;
	}

	public String toString() {
		return "PublicationInput {" //
			+ "id: " + this.id //
			+ ", " //
			+ "rating: " + this.rating //
			+ ", " //
			+ "authorNames: " + this.authorNames //
			+ ", " //
			+ "authorIds: " + this.authorIds //
			+ ", " //
			+ "title: " + this.title //
			+ ", " //
			+ "journalId: " + this.journalId //
			+ ", " //
			+ "kind: " + this.kind //
			+ ", " //
			+ "date: " + this.date //
			+ ", " //
			+ "year: " + this.year //
			+ ", " //
			+ "_abstract: " + this._abstract //
			+ ", " //
			+ "notes: " + this.notes //
			+ ", " //
			+ "peerReviewed: " + this.peerReviewed //
			+ ", " //
			+ "doi: " + this.doi //
			+ ", " //
			+ "isbn: " + this.isbn //
			+ ", " //
			+ "pmid: " + this.pmid //
			+ ", " //
			+ "hsid: " + this.hsid //
			+ ", " //
			+ "arxivid: " + this.arxivid //
			+ ", " //
			+ "biorxivid: " + this.biorxivid //
			+ ", " //
			+ "medrxivid: " + this.medrxivid //
			+ ", " //
			+ "ericid: " + this.ericid //
			+ ", " //
			+ "ihepid: " + this.ihepid //
			+ ", " //
			+ "oaipmhid: " + this.oaipmhid //
			+ ", " //
			+ "halid: " + this.halid //
			+ ", " //
			+ "zenodoid: " + this.zenodoid //
			+ ", " //
			+ "scopuseid: " + this.scopuseid //
			+ ", " //
			+ "wsan: " + this.wsan //
			+ ", " //
			+ "pinfoan: " + this.pinfoan //
			+ ", " //
			+ "url: " + this.url //
			+ ", " //
			+ "cached: " + this.cached //
			+ ", " //
			+ "accessed: " + this.accessed //
			+ "}";
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractTrackedEntityInput.Builder<Builder, PublicationInput> {

		private String authorNames;
		private List<Long> authorIds;
		private String title;
		private Long journalId;
		private PublicationKind kind;
		private LocalDate date;
		private Integer year;
		private String _abstract;
		private String notes;
		private Boolean peerReviewed;
		private String doi;
		private String isbn;
		private String pmid;
		private String hsid;
		private String arxivid;
		private String biorxivid;
		private String medrxivid;
		private String ericid;
		private String ihepid;
		private String oaipmhid;
		private String halid;
		private String zenodoid;
		private String scopuseid;
		private String wsan;
		private String pinfoan;
		private URL url;
		private Boolean cached;
		private LocalDate accessed;

		/**
		 * The names of the author, one per line.
		 */
		public Builder withAuthorNames(String authorNamesParam) {
			this.authorNames = authorNamesParam;
			return this;
		}

		/**
		 * The identifier(s) of the author(s) of the publication.
		 */
		public Builder withAuthorIds(List<Long> authorIdsParam) {
			this.authorIds = authorIdsParam;
			return this;
		}

		/**
		 * The publication title.
		 */
		public Builder withTitle(String titleParam) {
			this.title = titleParam;
			return this;
		}

		/**
		 * The name of the journal in which the publication appeared.
		 */
		public Builder withJournalId(Long journalIdParam) {
			this.journalId = journalIdParam;
			return this;
		}

		/**
		 * The publication type.
		 */
		public Builder withKind(PublicationKind kindParam) {
			this.kind = kindParam;
			return this;
		}

		/**
		 * The publication date.
		 */
		public Builder withDate(LocalDate dateParam) {
			this.date = dateParam;
			return this;
		}

		/**
		 * The publication year.
		 */
		public Builder withYear(Integer yearParam) {
			this.year = yearParam;
			return this;
		}

		/**
		 * The publication abstract.
		 */
		public Builder withAbstract(String _abstractParam) {
			this._abstract = _abstractParam;
			return this;
		}

		/**
		 * User notes about the publication.
		 */
		public Builder withNotes(String notesParam) {
			this.notes = notesParam;
			return this;
		}

		/**
		 * Whether the publication has been peer reviewed.
		 */
		public Builder withPeerReviewed(Boolean peerReviewedParam) {
			this.peerReviewed = peerReviewedParam;
			return this;
		}

		/**
		 * The digital object identifier.
		 */
		public Builder withDoi(String doiParam) {
			this.doi = doiParam;
			return this;
		}

		/**
		 * The International Standard Book Number.
		 */
		public Builder withIsbn(String isbnParam) {
			this.isbn = isbnParam;
			return this;
		}

		/**
		 * The U.S. National Library of Medicine's PubMedID.
		 */
		public Builder withPmid(String pmidParam) {
			this.pmid = pmidParam;
			return this;
		}

		/**
		 * The Corporation for National Research Initiatives's Handle System ID.
		 */
		public Builder withHsid(String hsidParam) {
			this.hsid = hsidParam;
			return this;
		}

		/**
		 * Cornell University Library's arXiv.org ID.
		 */
		public Builder withArxivid(String arxividParam) {
			this.arxivid = arxividParam;
			return this;
		}

		/**
		 * Cold Spring Harbor Laboratory's bioRxiv.org ID.
		 */
		public Builder withBiorxivid(String biorxividParam) {
			this.biorxivid = biorxividParam;
			return this;
		}

		/**
		 * Cold Spring Harbor Laboratory's medRxiv.org ID.
		 */
		public Builder withMedrxivid(String medrxividParam) {
			this.medrxivid = medrxividParam;
			return this;
		}

		/**
		 * U.S. Department of Education's ERIC database ID (niche).
		 */
		public Builder withEricid(String ericidParam) {
			this.ericid = ericidParam;
			return this;
		}

		/**
		 * CERN's INSPIRE-HEP ID.
		 */
		public Builder withIhepid(String ihepidParam) {
			this.ihepid = ihepidParam;
			return this;
		}

		/**
		 * Open Archives Initiative's OAI-PMH ID.
		 */
		public Builder withOaipmhid(String oaipmhidParam) {
			this.oaipmhid = oaipmhidParam;
			return this;
		}

		/**
		 * CNRS (France)'s HAL ID.
		 */
		public Builder withHalid(String halidParam) {
			this.halid = halidParam;
			return this;
		}

		/**
		 * CERN's Zenodo Record ID.
		 */
		public Builder withZenodoid(String zenodoidParam) {
			this.zenodoid = zenodoidParam;
			return this;
		}

		/**
		 * Elsevier's SCOPUS database EID (proprietary).
		 */
		public Builder withScopuseid(String scopuseidParam) {
			this.scopuseid = scopuseidParam;
			return this;
		}

		/**
		 * Clarivate's Web of Science Accession Number (UT) (proprietary).
		 */
		public Builder withWsan(String wsanParam) {
			this.wsan = wsanParam;
			return this;
		}

		/**
		 * American Psychological Association's PsycINFO Accession Number (proprietary/niche).
		 */
		public Builder withPinfoan(String pinfoanParam) {
			this.pinfoan = pinfoanParam;
			return this;
		}

		/**
		 * The URL for the publication online.
		 */
		public Builder withUrl(URL urlParam) {
			this.url = urlParam;
			return this;
		}

		/**
		 * Flag to indicate that url content is cached on this application server.
		 */
		public Builder withCached(Boolean cachedParam) {
			this.cached = cachedParam;
			return this;
		}

		/**
		 * The date the publication was accessed when compiling the database.
		 */
		public Builder withAccessed(LocalDate accessedParam) {
			this.accessed = accessedParam;
			return this;
		}

		@Override
		public PublicationInput build() {
			PublicationInput _object = build(new PublicationInput());
			_object.setAuthorNames(this.authorNames);
			_object.setAuthorIds(this.authorIds);
			_object.setTitle(this.title);
			_object.setJournalId(this.journalId);
			_object.setKind(this.kind);
			_object.setDate(this.date);
			_object.setYear(this.year);
			_object.setAbstract(this._abstract);
			_object.setNotes(this.notes);
			_object.setPeerReviewed(this.peerReviewed);
			_object.setDoi(this.doi);
			_object.setIsbn(this.isbn);
			_object.setPmid(this.pmid);
			_object.setHsid(this.hsid);
			_object.setArxivid(this.arxivid);
			_object.setBiorxivid(this.biorxivid);
			_object.setMedrxivid(this.medrxivid);
			_object.setEricid(this.ericid);
			_object.setIhepid(this.ihepid);
			_object.setOaipmhid(this.oaipmhid);
			_object.setHalid(this.halid);
			_object.setZenodoid(this.zenodoid);
			_object.setScopuseid(this.scopuseid);
			_object.setWsan(this.wsan);
			_object.setPinfoan(this.pinfoan);
			_object.setUrl(this.url);
			_object.setCached(this.cached);
			_object.setAccessed(this.accessed);
			return _object;
		}

	}

}
