/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-26 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.util.List;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLInputParameters;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLQuery;
import com.graphql_java_generator.annotation.GraphQLScalar;
import com.graphql_java_generator.annotation.RequestType;
import com.graphql_java_generator.client.GraphQLRequestObject;

import io.github.demonfiddler.ee.client.util.CustomJacksonDeserializers;

/**
 * Available queries.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLQuery(name = "Query", type = RequestType.query)
@GraphQLObjectType("Query")
@JsonInclude(Include.NON_NULL)
public class Query extends AbstractGraphQLEntity implements GraphQLRequestObject {

	private ObjectMapper mapper = null;
	private JsonNode extensions;
	private Map<String, JsonNode> extensionsAsMap = null;

	public Query() {
	}

	/**
	 * Returns a paged list of claims.
	 */
	@JsonProperty("claims")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "LinkableEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "claims", graphQLTypeSimpleName = "ClaimPage", javaClass = ClaimPage.class,
		listDepth = 0)
	ClaimPage claims;

	/**
	 * Returns a claim given its identifier.
	 */
	@JsonProperty("claimById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "claimById", graphQLTypeSimpleName = "Claim", javaClass = Claim.class, listDepth = 0)
	Claim claimById;

	/**
	 * Returns a paged list of comments.
	 */
	@JsonProperty("comments")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "CommentQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "comments", graphQLTypeSimpleName = "CommentPage", javaClass = CommentPage.class,
		listDepth = 0)
	CommentPage comments;

	/**
	 * Returns a comment given its identifier.
	 */
	@JsonProperty("commentById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "commentById", graphQLTypeSimpleName = "Comment", javaClass = Comment.class,
		listDepth = 0)
	Comment commentById;

	/**
	 * Returns a paged list of declarations.
	 */
	@JsonProperty("declarations")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "LinkableEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "declarations", graphQLTypeSimpleName = "DeclarationPage",
		javaClass = DeclarationPage.class, listDepth = 0)
	DeclarationPage declarations;

	/**
	 * Returns a declaration given its identifier.
	 */
	@JsonProperty("declarationById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "declarationById", graphQLTypeSimpleName = "Declaration",
		javaClass = Declaration.class, listDepth = 0)
	Declaration declarationById;

	/**
	 * Returns a paged list of entity links.
	 */
	@JsonProperty("entityLinks")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "EntityLinkQueryFilter", "PageableInput" },
		mandatories = { true, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "entityLinks", graphQLTypeSimpleName = "EntityLinkPage",
		javaClass = EntityLinkPage.class, listDepth = 0)
	EntityLinkPage entityLinks;

	/**
	 * Returns an entity link given its identifier.
	 */
	@JsonProperty("entityLinkById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "entityLinkById", graphQLTypeSimpleName = "EntityLink", javaClass = EntityLink.class,
		listDepth = 0)
	EntityLink entityLinkById;

	/**
	 * Returns an entity link given its from- and to-entity identifiers.
	 */
	@JsonProperty("entityLinkByEntityIds")
	@GraphQLInputParameters(names = { "fromEntityId", "toEntityId" }, types = { "ID", "ID" },
		mandatories = { true, true }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "entityLinkByEntityIds", graphQLTypeSimpleName = "EntityLink",
		javaClass = EntityLink.class, listDepth = 0)
	EntityLink entityLinkByEntityIds;

	/**
	 * Returns a paged list of journals.
	 */
	@JsonProperty("journals")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "TrackedEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "journals", graphQLTypeSimpleName = "JournalPage", javaClass = JournalPage.class,
		listDepth = 0)
	JournalPage journals;

	/**
	 * Returns a journal given its identifier.
	 */
	@JsonProperty("journalById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "journalById", graphQLTypeSimpleName = "Journal", javaClass = Journal.class,
		listDepth = 0)
	Journal journalById;

	/**
	 * Returns a paged list of log entries.
	 */
	@JsonProperty("log")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "LogQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "log", graphQLTypeSimpleName = "LogPage", javaClass = LogPage.class, listDepth = 0)
	LogPage log;

	/**
	 * Returns a paged list of persons.
	 */
	@JsonProperty("persons")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "LinkableEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "persons", graphQLTypeSimpleName = "PersonPage", javaClass = PersonPage.class,
		listDepth = 0)
	PersonPage persons;

	/**
	 * Returns a person given its identifier.
	 */
	@JsonProperty("personById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "personById", graphQLTypeSimpleName = "Person", javaClass = Person.class,
		listDepth = 0)
	Person personById;

	/**
	 * Returns a paged list of publications.
	 */
	@JsonProperty("publications")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "LinkableEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "publications", graphQLTypeSimpleName = "PublicationPage",
		javaClass = PublicationPage.class, listDepth = 0)
	PublicationPage publications;

	/**
	 * Returns a publication given its identifier.
	 */
	@JsonProperty("publicationById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "publicationById", graphQLTypeSimpleName = "Publication",
		javaClass = Publication.class, listDepth = 0)
	Publication publicationById;

	/**
	 * Returns a paged list of publishers.
	 */
	@JsonProperty("publishers")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "TrackedEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "publishers", graphQLTypeSimpleName = "PublisherPage",
		javaClass = PublisherPage.class, listDepth = 0)
	PublisherPage publishers;

	/**
	 * Returns a publisher given its identifier.
	 */
	@JsonProperty("publisherById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "publisherById", graphQLTypeSimpleName = "Publisher", javaClass = Publisher.class,
		listDepth = 0)
	Publisher publisherById;

	/**
	 * Returns a paged list of quotations.
	 */
	@JsonProperty("quotations")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "LinkableEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "quotations", graphQLTypeSimpleName = "QuotationPage",
		javaClass = QuotationPage.class, listDepth = 0)
	QuotationPage quotations;

	/**
	 * Returns a quotation given its identifier.
	 */
	@JsonProperty("quotationById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "quotationById", graphQLTypeSimpleName = "Quotation", javaClass = Quotation.class,
		listDepth = 0)
	Quotation quotationById;

	/**
	 * Returns a paged list of topics or sub-topics.
	 */
	@JsonProperty("topics")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "TopicQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "topics", graphQLTypeSimpleName = "TopicPage", javaClass = TopicPage.class,
		listDepth = 0)
	TopicPage topics;

	/**
	 * Returns a topic given its identifier.
	 */
	@JsonProperty("topicById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "topicById", graphQLTypeSimpleName = "Topic", javaClass = Topic.class, listDepth = 0)
	Topic topicById;

	/**
	 * Returns a paged list of users.
	 */
	@JsonProperty("users")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "TrackedEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "users", graphQLTypeSimpleName = "UserPage", javaClass = UserPage.class,
		listDepth = 0)
	UserPage users;

	/**
	 * Returns a user given its identifier.
	 */
	@JsonProperty("userById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "userById", graphQLTypeSimpleName = "User", javaClass = User.class, listDepth = 0)
	User userById;

	/**
	 * Returns a user given its username.
	 */
	@JsonProperty("userByUsername")
	@GraphQLInputParameters(names = { "username" }, types = { "String" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "userByUsername", graphQLTypeSimpleName = "User", javaClass = User.class,
		listDepth = 0)
	User userByUsername;

	/**
	 * Returns the currently logged-in user.
	 */
	@JsonProperty("currentUser")
	@GraphQLNonScalar(fieldName = "currentUser", graphQLTypeSimpleName = "User", javaClass = User.class, listDepth = 0)
	User currentUser;

	/**
	 * Returns a paged list of groups.
	 */
	@JsonProperty("groups")
	@GraphQLInputParameters(names = { "filter", "pageSort" }, types = { "TrackedEntityQueryFilter", "PageableInput" },
		mandatories = { false, false }, listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "groups", graphQLTypeSimpleName = "GroupPage", javaClass = GroupPage.class,
		listDepth = 0)
	GroupPage groups;

	/**
	 * Returns a group given its identifier.
	 */
	@JsonProperty("groupById")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "groupById", graphQLTypeSimpleName = "Group", javaClass = Group.class, listDepth = 0)
	Group groupById;

	/**
	 * Returns a group given its groupname.
	 */
	@JsonProperty("groupByGroupname")
	@GraphQLInputParameters(names = { "groupname" }, types = { "String" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "groupByGroupname", graphQLTypeSimpleName = "Group", javaClass = Group.class,
		listDepth = 0)
	Group groupByGroupname;

	/**
	 * Returns statistics on the specified entity kinds.
	 */
	@JsonProperty("entityStatistics")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListEntityStatistics.class)
	@GraphQLInputParameters(names = { "filter" }, types = { "TrackedEntityQueryFilter" }, mandatories = { false },
		listDepths = { 0 }, itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "entityStatistics", graphQLTypeSimpleName = "EntityStatistics",
		javaClass = EntityStatistics.class, listDepth = 1)
	List<EntityStatistics> entityStatistics;

	/**
	 * Returns statistics on entities linked to the specified topic(s).
	 */
	@JsonProperty("topicStatistics")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListTopicStatistics.class)
	@GraphQLInputParameters(names = { "topicFilter", "entityFilter" },
		types = { "TopicQueryFilter", "TrackedEntityQueryFilter" }, mandatories = { false, false },
		listDepths = { 0, 0 }, itemsMandatory = { false, false })
	@GraphQLNonScalar(fieldName = "topicStatistics", graphQLTypeSimpleName = "TopicStatistics",
		javaClass = TopicStatistics.class, listDepth = 1)
	List<TopicStatistics> topicStatistics;

	/**
	 * Returns audit information on the specified entity.
	 */
	@JsonProperty("audit")
	@GraphQLInputParameters(names = { "id" }, types = { "ID" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "audit", graphQLTypeSimpleName = "EntityAudit", javaClass = EntityAudit.class,
		listDepth = 0)
	EntityAudit audit;

	@JsonProperty("__schema")
	@GraphQLNonScalar(fieldName = "__schema", graphQLTypeSimpleName = "__Schema", javaClass = __Schema.class,
		listDepth = 0)
	__Schema __schema;

	@JsonProperty("__type")
	@GraphQLInputParameters(names = { "name" }, types = { "String" }, mandatories = { true }, listDepths = { 0 },
		itemsMandatory = { false })
	@GraphQLNonScalar(fieldName = "__type", graphQLTypeSimpleName = "__Type", javaClass = __Type.class, listDepth = 0)
	__Type __type;

	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String __typename;

	/**
	 * Returns a paged list of claims.
	 */
	@JsonProperty("claims")
	public void setClaims(ClaimPage claims) {
		this.claims = claims;
	}

	/**
	 * Returns a paged list of claims.
	 */
	@JsonProperty("claims")
	public ClaimPage getClaims() {
		return this.claims;
	}

	/**
	 * Returns a claim given its identifier.
	 */
	@JsonProperty("claimById")
	public void setClaimById(Claim claimById) {
		this.claimById = claimById;
	}

	/**
	 * Returns a claim given its identifier.
	 */
	@JsonProperty("claimById")
	public Claim getClaimById() {
		return this.claimById;
	}

	/**
	 * Returns a paged list of comments.
	 */
	@JsonProperty("comments")
	public void setComments(CommentPage comments) {
		this.comments = comments;
	}

	/**
	 * Returns a paged list of comments.
	 */
	@JsonProperty("comments")
	public CommentPage getComments() {
		return this.comments;
	}

	/**
	 * Returns a comment given its identifier.
	 */
	@JsonProperty("commentById")
	public void setCommentById(Comment commentById) {
		this.commentById = commentById;
	}

	/**
	 * Returns a comment given its identifier.
	 */
	@JsonProperty("commentById")
	public Comment getCommentById() {
		return this.commentById;
	}

	/**
	 * Returns a paged list of declarations.
	 */
	@JsonProperty("declarations")
	public void setDeclarations(DeclarationPage declarations) {
		this.declarations = declarations;
	}

	/**
	 * Returns a paged list of declarations.
	 */
	@JsonProperty("declarations")
	public DeclarationPage getDeclarations() {
		return this.declarations;
	}

	/**
	 * Returns a declaration given its identifier.
	 */
	@JsonProperty("declarationById")
	public void setDeclarationById(Declaration declarationById) {
		this.declarationById = declarationById;
	}

	/**
	 * Returns a declaration given its identifier.
	 */
	@JsonProperty("declarationById")
	public Declaration getDeclarationById() {
		return this.declarationById;
	}

	/**
	 * Returns a paged list of entity links.
	 */
	@JsonProperty("entityLinks")
	public void setEntityLinks(EntityLinkPage entityLinks) {
		this.entityLinks = entityLinks;
	}

	/**
	 * Returns a paged list of entity links.
	 */
	@JsonProperty("entityLinks")
	public EntityLinkPage getEntityLinks() {
		return this.entityLinks;
	}

	/**
	 * Returns an entity link given its identifier.
	 */
	@JsonProperty("entityLinkById")
	public void setEntityLinkById(EntityLink entityLinkById) {
		this.entityLinkById = entityLinkById;
	}

	/**
	 * Returns an entity link given its identifier.
	 */
	@JsonProperty("entityLinkById")
	public EntityLink getEntityLinkById() {
		return this.entityLinkById;
	}

	/**
	 * Returns an entity link given its from- and to-entity identifiers.
	 */
	@JsonProperty("entityLinkByEntityIds")
	public void setEntityLinkByEntityIds(EntityLink entityLinkByEntityIds) {
		this.entityLinkByEntityIds = entityLinkByEntityIds;
	}

	/**
	 * Returns an entity link given its from- and to-entity identifiers.
	 */
	@JsonProperty("entityLinkByEntityIds")
	public EntityLink getEntityLinkByEntityIds() {
		return this.entityLinkByEntityIds;
	}

	/**
	 * Returns a paged list of journals.
	 */
	@JsonProperty("journals")
	public void setJournals(JournalPage journals) {
		this.journals = journals;
	}

	/**
	 * Returns a paged list of journals.
	 */
	@JsonProperty("journals")
	public JournalPage getJournals() {
		return this.journals;
	}

	/**
	 * Returns a journal given its identifier.
	 */
	@JsonProperty("journalById")
	public void setJournalById(Journal journalById) {
		this.journalById = journalById;
	}

	/**
	 * Returns a journal given its identifier.
	 */
	@JsonProperty("journalById")
	public Journal getJournalById() {
		return this.journalById;
	}

	/**
	 * Returns a paged list of log entries.
	 */
	@JsonProperty("log")
	public void setLog(LogPage log) {
		this.log = log;
	}

	/**
	 * Returns a paged list of log entries.
	 */
	@JsonProperty("log")
	public LogPage getLog() {
		return this.log;
	}

	/**
	 * Returns a paged list of persons.
	 */
	@JsonProperty("persons")
	public void setPersons(PersonPage persons) {
		this.persons = persons;
	}

	/**
	 * Returns a paged list of persons.
	 */
	@JsonProperty("persons")
	public PersonPage getPersons() {
		return this.persons;
	}

	/**
	 * Returns a person given its identifier.
	 */
	@JsonProperty("personById")
	public void setPersonById(Person personById) {
		this.personById = personById;
	}

	/**
	 * Returns a person given its identifier.
	 */
	@JsonProperty("personById")
	public Person getPersonById() {
		return this.personById;
	}

	/**
	 * Returns a paged list of publications.
	 */
	@JsonProperty("publications")
	public void setPublications(PublicationPage publications) {
		this.publications = publications;
	}

	/**
	 * Returns a paged list of publications.
	 */
	@JsonProperty("publications")
	public PublicationPage getPublications() {
		return this.publications;
	}

	/**
	 * Returns a publication given its identifier.
	 */
	@JsonProperty("publicationById")
	public void setPublicationById(Publication publicationById) {
		this.publicationById = publicationById;
	}

	/**
	 * Returns a publication given its identifier.
	 */
	@JsonProperty("publicationById")
	public Publication getPublicationById() {
		return this.publicationById;
	}

	/**
	 * Returns a paged list of publishers.
	 */
	@JsonProperty("publishers")
	public void setPublishers(PublisherPage publishers) {
		this.publishers = publishers;
	}

	/**
	 * Returns a paged list of publishers.
	 */
	@JsonProperty("publishers")
	public PublisherPage getPublishers() {
		return this.publishers;
	}

	/**
	 * Returns a publisher given its identifier.
	 */
	@JsonProperty("publisherById")
	public void setPublisherById(Publisher publisherById) {
		this.publisherById = publisherById;
	}

	/**
	 * Returns a publisher given its identifier.
	 */
	@JsonProperty("publisherById")
	public Publisher getPublisherById() {
		return this.publisherById;
	}

	/**
	 * Returns a paged list of quotations.
	 */
	@JsonProperty("quotations")
	public void setQuotations(QuotationPage quotations) {
		this.quotations = quotations;
	}

	/**
	 * Returns a paged list of quotations.
	 */
	@JsonProperty("quotations")
	public QuotationPage getQuotations() {
		return this.quotations;
	}

	/**
	 * Returns a quotation given its identifier.
	 */
	@JsonProperty("quotationById")
	public void setQuotationById(Quotation quotationById) {
		this.quotationById = quotationById;
	}

	/**
	 * Returns a quotation given its identifier.
	 */
	@JsonProperty("quotationById")
	public Quotation getQuotationById() {
		return this.quotationById;
	}

	/**
	 * Returns a paged list of topics or sub-topics.
	 */
	@JsonProperty("topics")
	public void setTopics(TopicPage topics) {
		this.topics = topics;
	}

	/**
	 * Returns a paged list of topics or sub-topics.
	 */
	@JsonProperty("topics")
	public TopicPage getTopics() {
		return this.topics;
	}

	/**
	 * Returns a topic given its identifier.
	 */
	@JsonProperty("topicById")
	public void setTopicById(Topic topicById) {
		this.topicById = topicById;
	}

	/**
	 * Returns a topic given its identifier.
	 */
	@JsonProperty("topicById")
	public Topic getTopicById() {
		return this.topicById;
	}

	/**
	 * Returns a paged list of users.
	 */
	@JsonProperty("users")
	public void setUsers(UserPage users) {
		this.users = users;
	}

	/**
	 * Returns a paged list of users.
	 */
	@JsonProperty("users")
	public UserPage getUsers() {
		return this.users;
	}

	/**
	 * Returns a user given its identifier.
	 */
	@JsonProperty("userById")
	public void setUserById(User userById) {
		this.userById = userById;
	}

	/**
	 * Returns a user given its identifier.
	 */
	@JsonProperty("userById")
	public User getUserById() {
		return this.userById;
	}

	/**
	 * Returns a user given its username.
	 */
	@JsonProperty("userByUsername")
	public void setUserByUsername(User userByUsername) {
		this.userByUsername = userByUsername;
	}

	/**
	 * Returns a user given its username.
	 */
	@JsonProperty("userByUsername")
	public User getUserByUsername() {
		return this.userByUsername;
	}

	/**
	 * Returns the currently logged-in user.
	 */
	@JsonProperty("currentUser")
	public void setCurrentUser(User currentUser) {
		this.currentUser = currentUser;
	}

	/**
	 * Returns the currently logged-in user.
	 */
	@JsonProperty("currentUser")
	public User getCurrentUser() {
		return this.currentUser;
	}

	/**
	 * Returns a paged list of groups.
	 */
	@JsonProperty("groups")
	public void setGroups(GroupPage groups) {
		this.groups = groups;
	}

	/**
	 * Returns a paged list of groups.
	 */
	@JsonProperty("groups")
	public GroupPage getGroups() {
		return this.groups;
	}

	/**
	 * Returns a group given its identifier.
	 */
	@JsonProperty("groupById")
	public void setGroupById(Group groupById) {
		this.groupById = groupById;
	}

	/**
	 * Returns a group given its identifier.
	 */
	@JsonProperty("groupById")
	public Group getGroupById() {
		return this.groupById;
	}

	/**
	 * Returns a group given its groupname.
	 */
	@JsonProperty("groupByGroupname")
	public void setGroupByGroupname(Group groupByGroupname) {
		this.groupByGroupname = groupByGroupname;
	}

	/**
	 * Returns a group given its groupname.
	 */
	@JsonProperty("groupByGroupname")
	public Group getGroupByGroupname() {
		return this.groupByGroupname;
	}

	/**
	 * Returns statistics on the specified entity kinds.
	 */
	@JsonProperty("entityStatistics")
	public void setEntityStatistics(List<EntityStatistics> entityStatistics) {
		this.entityStatistics = entityStatistics;
	}

	/**
	 * Returns statistics on the specified entity kinds.
	 */
	@JsonProperty("entityStatistics")
	public List<EntityStatistics> getEntityStatistics() {
		return this.entityStatistics;
	}

	/**
	 * Returns statistics on entities linked to the specified topic(s).
	 */
	@JsonProperty("topicStatistics")
	public void setTopicStatistics(List<TopicStatistics> topicStatistics) {
		this.topicStatistics = topicStatistics;
	}

	/**
	 * Returns statistics on entities linked to the specified topic(s).
	 */
	@JsonProperty("topicStatistics")
	public List<TopicStatistics> getTopicStatistics() {
		return this.topicStatistics;
	}

	/**
	 * Returns audit information on the specified entity.
	 */
	@JsonProperty("audit")
	public void setAudit(EntityAudit audit) {
		this.audit = audit;
	}

	/**
	 * Returns audit information on the specified entity.
	 */
	@JsonProperty("audit")
	public EntityAudit getAudit() {
		return this.audit;
	}

	@JsonProperty("__schema")
	public void set__schema(__Schema __schema) {
		this.__schema = __schema;
	}

	@JsonProperty("__schema")
	public __Schema get__schema() {
		return this.__schema;
	}

	@JsonProperty("__type")
	public void set__type(__Type __type) {
		this.__type = __type;
	}

	@JsonProperty("__type")
	public __Type get__type() {
		return this.__type;
	}

	public String toString() {
		return "Query {" //
			+ "claims: " + this.claims //
			+ ", " //
			+ "claimById: " + this.claimById //
			+ ", " //
			+ "comments: " + this.comments //
			+ ", " //
			+ "commentById: " + this.commentById //
			+ ", " //
			+ "declarations: " + this.declarations //
			+ ", " //
			+ "declarationById: " + this.declarationById //
			+ ", " //
			+ "entityLinks: " + this.entityLinks //
			+ ", " //
			+ "entityLinkById: " + this.entityLinkById //
			+ ", " //
			+ "entityLinkByEntityIds: " + this.entityLinkByEntityIds //
			+ ", " //
			+ "journals: " + this.journals //
			+ ", " //
			+ "journalById: " + this.journalById //
			+ ", " //
			+ "log: " + this.log //
			+ ", " //
			+ "persons: " + this.persons //
			+ ", " //
			+ "personById: " + this.personById //
			+ ", " //
			+ "publications: " + this.publications //
			+ ", " //
			+ "publicationById: " + this.publicationById //
			+ ", " //
			+ "publishers: " + this.publishers //
			+ ", " //
			+ "publisherById: " + this.publisherById //
			+ ", " //
			+ "quotations: " + this.quotations //
			+ ", " //
			+ "quotationById: " + this.quotationById //
			+ ", " //
			+ "topics: " + this.topics //
			+ ", " //
			+ "topicById: " + this.topicById //
			+ ", " //
			+ "users: " + this.users //
			+ ", " //
			+ "userById: " + this.userById //
			+ ", " //
			+ "userByUsername: " + this.userByUsername //
			+ ", " //
			+ "currentUser: " + this.currentUser //
			+ ", " //
			+ "groups: " + this.groups //
			+ ", " //
			+ "groupById: " + this.groupById //
			+ ", " //
			+ "groupByGroupname: " + this.groupByGroupname //
			+ ", " //
			+ "entityStatistics: " + this.entityStatistics //
			+ ", " //
			+ "topicStatistics: " + this.topicStatistics //
			+ ", " //
			+ "audit: " + this.audit //
			+ ", " //
			+ "__schema: " + this.__schema //
			+ ", " //
			+ "__type: " + this.__type //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}";
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder extends AbstractGraphQLEntity.Builder<Builder, Query> {

		private ClaimPage claims;
		private Claim claimById;
		private CommentPage comments;
		private Comment commentById;
		private DeclarationPage declarations;
		private Declaration declarationById;
		private EntityLinkPage entityLinks;
		private EntityLink entityLinkById;
		private EntityLink entityLinkByEntityIds;
		private JournalPage journals;
		private Journal journalById;
		private LogPage log;
		private PersonPage persons;
		private Person personById;
		private PublicationPage publications;
		private Publication publicationById;
		private PublisherPage publishers;
		private Publisher publisherById;
		private QuotationPage quotations;
		private Quotation quotationById;
		private TopicPage topics;
		private Topic topicById;
		private UserPage users;
		private User userById;
		private User userByUsername;
		private User currentUser;
		private GroupPage groups;
		private Group groupById;
		private Group groupByGroupname;
		private List<EntityStatistics> entityStatistics;
		private List<TopicStatistics> topicStatistics;
		private EntityAudit audit;
		private __Schema __schema;
		private __Type __type;

		/**
		 * Returns a paged list of claims.
		 */
		public Builder withClaims(ClaimPage claimsParam) {
			this.claims = claimsParam;
			return this;
		}

		/**
		 * Returns a claim given its identifier.
		 */
		public Builder withClaimById(Claim claimByIdParam) {
			this.claimById = claimByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of comments.
		 */
		public Builder withComments(io.github.demonfiddler.ee.client.CommentPage commentsParam) {
			this.comments = commentsParam;
			return this;
		}

		/**
		 * Returns a comment given its identifier.
		 */
		public Builder withCommentById(io.github.demonfiddler.ee.client.Comment commentByIdParam) {
			this.commentById = commentByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of declarations.
		 */
		public Builder withDeclarations(DeclarationPage declarationsParam) {
			this.declarations = declarationsParam;
			return this;
		}

		/**
		 * Returns a declaration given its identifier.
		 */
		public Builder withDeclarationById(Declaration declarationByIdParam) {
			this.declarationById = declarationByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of entity links.
		 */
		public Builder withEntityLinks(EntityLinkPage entityLinksParam) {
			this.entityLinks = entityLinksParam;
			return this;
		}

		/**
		 * Returns an entity link given its identifier.
		 */
		public Builder withEntityLinkById(EntityLink entityLinkByIdParam) {
			this.entityLinkById = entityLinkByIdParam;
			return this;
		}

		/**
		 * Returns an entity link given its from- and to-entity identifiers.
		 */
		public Builder withEntityLinkByEntityIds(EntityLink entityLinkByEntityIdsParam) {
			this.entityLinkByEntityIds = entityLinkByEntityIdsParam;
			return this;
		}

		/**
		 * Returns a paged list of journals.
		 */
		public Builder withJournals(JournalPage journalsParam) {
			this.journals = journalsParam;
			return this;
		}

		/**
		 * Returns a journal given its identifier.
		 */
		public Builder withJournalById(Journal journalByIdParam) {
			this.journalById = journalByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of log entries.
		 */
		public Builder withLog(LogPage logParam) {
			this.log = logParam;
			return this;
		}

		/**
		 * Returns a paged list of persons.
		 */
		public Builder withPersons(PersonPage personsParam) {
			this.persons = personsParam;
			return this;
		}

		/**
		 * Returns a person given its identifier.
		 */
		public Builder withPersonById(Person personByIdParam) {
			this.personById = personByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of publications.
		 */
		public Builder withPublications(PublicationPage publicationsParam) {
			this.publications = publicationsParam;
			return this;
		}

		/**
		 * Returns a publication given its identifier.
		 */
		public Builder withPublicationById(Publication publicationByIdParam) {
			this.publicationById = publicationByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of publishers.
		 */
		public Builder withPublishers(PublisherPage publishersParam) {
			this.publishers = publishersParam;
			return this;
		}

		/**
		 * Returns a publisher given its identifier.
		 */
		public Builder withPublisherById(Publisher publisherByIdParam) {
			this.publisherById = publisherByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of quotations.
		 */
		public Builder withQuotations(QuotationPage quotationsParam) {
			this.quotations = quotationsParam;
			return this;
		}

		/**
		 * Returns a quotation given its identifier.
		 */
		public Builder withQuotationById(Quotation quotationByIdParam) {
			this.quotationById = quotationByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of topics or sub-topics.
		 */
		public Builder withTopics(TopicPage topicsParam) {
			this.topics = topicsParam;
			return this;
		}

		/**
		 * Returns a topic given its identifier.
		 */
		public Builder withTopicById(Topic topicByIdParam) {
			this.topicById = topicByIdParam;
			return this;
		}

		/**
		 * Returns a paged list of users.
		 */
		public Builder withUsers(UserPage usersParam) {
			this.users = usersParam;
			return this;
		}

		/**
		 * Returns a user given its identifier.
		 */
		public Builder withUserById(User userByIdParam) {
			this.userById = userByIdParam;
			return this;
		}

		/**
		 * Returns a user given its username.
		 */
		public Builder withUserByUsername(User userByUsernameParam) {
			this.userByUsername = userByUsernameParam;
			return this;
		}

		/**
		 * Returns the currently logged-in user.
		 */
		public Builder withCurrentUser(User currentUserParam) {
			this.currentUser = currentUserParam;
			return this;
		}

		/**
		 * Returns a paged list of groups.
		 */
		public Builder withGroups(GroupPage groupsParam) {
			this.groups = groupsParam;
			return this;
		}

		/**
		 * Returns a group given its identifier.
		 */
		public Builder withGroupById(Group groupByIdParam) {
			this.groupById = groupByIdParam;
			return this;
		}

		/**
		 * Returns a group given its groupname.
		 */
		public Builder withGroupByGroupname(Group groupByGroupnameParam) {
			this.groupByGroupname = groupByGroupnameParam;
			return this;
		}

		/**
		 * Returns statistics on the specified entity kinds.
		 */
		public Builder withEntityStatistics(List<EntityStatistics> entityStatisticsParam) {
			this.entityStatistics = entityStatisticsParam;
			return this;
		}

		/**
		 * Returns statistics on entities linked to the specified topic(s).
		 */
		public Builder withTopicStatistics(List<TopicStatistics> topicStatisticsParam) {
			this.topicStatistics = topicStatisticsParam;
			return this;
		}

		/**
		 * Returns audit information on the specified entity.
		 */
		public Builder withAudit(EntityAudit auditParam) {
			this.audit = auditParam;
			return this;
		}

		public Builder with__schema(__Schema __schemaParam) {
			this.__schema = __schemaParam;
			return this;
		}

		public Builder with__type(__Type __typeParam) {
			this.__type = __typeParam;
			return this;
		}

		public Query build() {
			Query _object = build(new Query());
			_object.setClaims(this.claims);
			_object.setClaimById(this.claimById);
			_object.setComments(this.comments);
			_object.setCommentById(this.commentById);
			_object.setDeclarations(this.declarations);
			_object.setDeclarationById(this.declarationById);
			_object.setEntityLinks(this.entityLinks);
			_object.setEntityLinkById(this.entityLinkById);
			_object.setEntityLinkByEntityIds(this.entityLinkByEntityIds);
			_object.setJournals(this.journals);
			_object.setJournalById(this.journalById);
			_object.setLog(this.log);
			_object.setPersons(this.persons);
			_object.setPersonById(this.personById);
			_object.setPublications(this.publications);
			_object.setPublicationById(this.publicationById);
			_object.setPublishers(this.publishers);
			_object.setPublisherById(this.publisherById);
			_object.setQuotations(this.quotations);
			_object.setQuotationById(this.quotationById);
			_object.setTopics(this.topics);
			_object.setTopicById(this.topicById);
			_object.setUsers(this.users);
			_object.setUserById(this.userById);
			_object.setUserByUsername(this.userByUsername);
			_object.setCurrentUser(this.currentUser);
			_object.setGroups(this.groups);
			_object.setGroupById(this.groupById);
			_object.setGroupByGroupname(this.groupByGroupname);
			_object.setEntityStatistics(this.entityStatistics);
			_object.setTopicStatistics(this.topicStatistics);
			_object.setAudit(this.audit);
			_object.set__schema(this.__schema);
			_object.set__type(this.__type);
			return _object;
		}

		@Override
		String getTypeName() {
			return "Query";
		}

	}

	private ObjectMapper getMapper() {
		if (this.mapper == null) {
			this.mapper = new ObjectMapper();
		}
		return this.mapper;
	}

	public JsonNode getExtensions() {
		return this.extensions;
	}

	public void setExtensions(JsonNode extensionsParam) {
		this.extensions = extensionsParam;
	}

	/**
	 * Returns the extensions as a map. The values can't be deserialized, as their type is unknown.
	 * @return
	 */
	public Map<String, JsonNode> getExtensionsAsMap() {
		if (this.extensionsAsMap == null) {
			this.extensionsAsMap =
				new ObjectMapper().convertValue(this.extensions, new TypeReference<Map<String, JsonNode>>() {
				});
		}
		return this.extensionsAsMap;
	}

	/**
	 * Parse the value for the given _key_, as found in the <I>extensions</I> field of the GraphQL server's response,
	 * into the given _t_ class.
	 * @param <T>
	 * @param key
	 * @param t
	 * @return null if the key is not in the <I>extensions</I> map. Otherwise: the value for this _key_, as a _t_
	 * instance
	 * @throws JsonProcessingException When there is an error when converting the key's value into the _t_ class
	 */
	public <T> T getExtensionsField(String key, Class<T> t) throws JsonProcessingException {
		JsonNode node = getExtensionsAsMap().get(key);
		return (node == null) ? null : getMapper().treeToValue(node, t);
	}

}
