/*----------------------------------------------------------------------------------------------------------------------
 * Evidence Engine: A system for managing evidence on arbitrary scientific topics.
 * Comprises an SQL database, GraphQL public API, Java app server, Java and web clients.
 * Copyright © 2024-25 Adrian Price. All rights reserved.
 *
 * This file is part of Evidence Engine.
 *
 * Evidence Engine is free software: you can redistribute it and/or modify it under the terms of the
 * GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Evidence Engine is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License along with Evidence Engine.
 * If not, see <https://www.gnu.org/licenses/>. 
 *--------------------------------------------------------------------------------------------------------------------*/

package io.github.demonfiddler.ee.client;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

import org.dataloader.DataLoader;

import graphql.schema.DataFetchingEnvironment;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.graphql_java_generator.annotation.GraphQLNonScalar;
import com.graphql_java_generator.annotation.GraphQLObjectType;
import com.graphql_java_generator.annotation.GraphQLScalar;
import com.graphql_java_generator.client.GraphQLObjectMapper;

import io.github.demonfiddler.ee.client.util.CustomJacksonDeserializers;
import java.util.List;

import com.graphql_java_generator.annotation.GraphQLDirective;
import com.graphql_java_generator.annotation.GraphQLIgnore;

/**
 * Statistics about a given topic.
 * @author generated by graphql-java-generator
 * @see <a href=
 * "https://github.com/graphql-java-generator/graphql-java-generator">https://github.com/graphql-java-generator/graphql-java-generator</a>
 */
@GraphQLObjectType("TopicStatistics")
@JsonInclude(Include.NON_NULL)
@SuppressWarnings("unused")
public class TopicStatistics {

	/**
	 * This map contains the deserialized values for the alias, as parsed from the JSON response from the GraphQL
	 * server. The key is the alias name, the value is the deserialiazed value (taking into account custom scalars,
	 * lists, ...)
	 */
	@GraphQLIgnore
	Map<String, Object> aliasValues = new HashMap<>();

	/**
	 * The topic in question.
	 */
	@JsonProperty("topic")
	@GraphQLNonScalar(fieldName = "topic", graphQLTypeSimpleName = "Topic", javaClass = Topic.class, listDepth = 0)
	Topic topic;

	/**
	 * Statistics for the requested entities.
	 */
	@JsonProperty("entityStatistics")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListEntityStatistics.class)
	@GraphQLNonScalar(fieldName = "entityStatistics", graphQLTypeSimpleName = "EntityStatistics",
		javaClass = EntityStatistics.class, listDepth = 1)
	List<EntityStatistics> entityStatistics;

	/**
	 * Statistics for the immediate sub-topics.
	 */
	@JsonProperty("children")
	@JsonDeserialize(using = CustomJacksonDeserializers.ListTopicStatistics.class)
	@GraphQLNonScalar(fieldName = "children", graphQLTypeSimpleName = "TopicStatistics",
		javaClass = TopicStatistics.class, listDepth = 1)
	List<TopicStatistics> children;

	@JsonProperty("__typename")
	@GraphQLScalar(fieldName = "__typename", graphQLTypeSimpleName = "String", javaClass = String.class, listDepth = 0)
	String __typename;

	/**
	 * The topic in question.
	 */
	@JsonProperty("topic")
	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	/**
	 * The topic in question.
	 */
	@JsonProperty("topic")
	public Topic getTopic() {
		return this.topic;
	}

	/**
	 * Statistics for the requested entities.
	 */
	@JsonProperty("entityStatistics")
	public void setEntityStatistics(List<EntityStatistics> entityStatistics) {
		this.entityStatistics = entityStatistics;
	}

	/**
	 * Statistics for the requested entities.
	 */
	@JsonProperty("entityStatistics")
	public List<EntityStatistics> getEntityStatistics() {
		return this.entityStatistics;
	}

	/**
	 * Statistics for the immediate sub-topics.
	 */
	@JsonProperty("children")
	public void setChildren(List<TopicStatistics> children) {
		this.children = children;
	}

	/**
	 * Statistics for the immediate sub-topics.
	 */
	@JsonProperty("children")
	public List<TopicStatistics> getChildren() {
		return this.children;
	}

	@JsonProperty("__typename")
	public void set__typename(String __typename) {
		this.__typename = __typename;
	}

	@JsonProperty("__typename")
	public String get__typename() {
		return this.__typename;
	}

	/**
	 * This method is called during the JSON deserialization process, by the {@link GraphQLObjectMapper}, each time an
	 * alias value is read from the JSON.
	 * @param aliasName
	 * @param aliasDeserializedValue
	 */
	public void setAliasValue(String aliasName, Object aliasDeserializedValue) {
		this.aliasValues.put(aliasName, aliasDeserializedValue);
	}

	/**
	 * Retrieves the value for the given alias, as it has been received for this object in the GraphQL response. <BR/>
	 * This method <B>should not be used for Custom Scalars</B>, as the parser doesn't know if this alias is a custom
	 * scalar, and which custom scalar to use at deserialization time. In most case, a value will then be provided by
	 * this method with a basis JSON deserialization, but this value won't be the proper custom scalar value.
	 * @param alias
	 * @return
	 */
	public Object getAliasValue(String alias) {
		return this.aliasValues.get(alias);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((aliasValues == null) ? 0 : aliasValues.hashCode());
		result = prime * result + ((topic == null) ? 0 : topic.hashCode());
		result = prime * result + ((entityStatistics == null) ? 0 : entityStatistics.hashCode());
		result = prime * result + ((children == null) ? 0 : children.hashCode());
		result = prime * result + ((__typename == null) ? 0 : __typename.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TopicStatistics other = (TopicStatistics)obj;
		if (aliasValues == null) {
			if (other.aliasValues != null)
				return false;
		} else if (!aliasValues.equals(other.aliasValues))
			return false;
		if (topic == null) {
			if (other.topic != null)
				return false;
		} else if (!topic.equals(other.topic))
			return false;
		if (entityStatistics == null) {
			if (other.entityStatistics != null)
				return false;
		} else if (!entityStatistics.equals(other.entityStatistics))
			return false;
		if (children == null) {
			if (other.children != null)
				return false;
		} else if (!children.equals(other.children))
			return false;
		if (__typename == null) {
			if (other.__typename != null)
				return false;
		} else if (!__typename.equals(other.__typename))
			return false;
		return true;
	}

	public String toString() {
		return "TopicStatistics {" //
			+ "topic: " + this.topic //
			+ ", " //
			+ "entityStatistics: " + this.entityStatistics //
			+ ", " //
			+ "children: " + this.children //
			+ ", " //
			+ "__typename: " + this.__typename //
			+ "}"; //
	}

	public static Builder builder() {
		return new Builder();
	}

	/**
	 * The Builder that helps building instance of this POJO. You can get an instance of this class, by calling the
	 * {@link #builder()}
	 */
	public static class Builder {

		private Topic topic;
		private List<EntityStatistics> entityStatistics;
		private List<TopicStatistics> children;

		/**
		 * The topic in question.
		 */
		public Builder withTopic(Topic topicParam) {
			this.topic = topicParam;
			return this;
		}

		/**
		 * Statistics for the requested entities.
		 */
		public Builder withEntityStatistics(List<EntityStatistics> entityStatisticsParam) {
			this.entityStatistics = entityStatisticsParam;
			return this;
		}

		/**
		 * Statistics for the immediate sub-topics.
		 */
		public Builder withChildren(List<TopicStatistics> childrenParam) {
			this.children = childrenParam;
			return this;
		}

		public TopicStatistics build() {
			TopicStatistics _object = new TopicStatistics();
			_object.setTopic(this.topic);
			_object.setEntityStatistics(this.entityStatistics);
			_object.setChildren(this.children);
			_object.set__typename("TopicStatistics");
			return _object;
		}

	}

}
